# TP1

## Generacion de la clase_ternaria

In [ ]:
require( "data.table" )

# leo el dataset
dataset <- fread("/content/datasets/competencia_01_crudo.csv" )

# calculo el periodo0 consecutivo
dsimple <- dataset[, list(
    "pos" = .I,
    numero_de_cliente,
    periodo0 = as.integer(foto_mes/100)*12 +  foto_mes%%100 ) ]


# ordeno
setorder( dsimple, numero_de_cliente, periodo0 )

# calculo topes
periodo_ultimo <- dsimple[, max(periodo0) ]
periodo_anteultimo <- periodo_ultimo - 1


# calculo los leads de orden 1 y 2
dsimple[, c("periodo1", "periodo2") :=
    shift(periodo0, n=1:2, fill=NA, type="lead"),  numero_de_cliente ]

# assign most common class values = "CONTINUA"
dsimple[ periodo0 < periodo_anteultimo, clase_ternaria := "CONTINUA" ]

# calculo BAJA+1
dsimple[ periodo0 < periodo_ultimo &
    ( is.na(periodo1) | periodo0 + 1 < periodo1 ),
    clase_ternaria := "BAJA+1" ]

# calculo BAJA+2
dsimple[ periodo0 < periodo_anteultimo & (periodo0+1 == periodo1 )
    & ( is.na(periodo2) | periodo0 + 2 < periodo2 ),
    clase_ternaria := "BAJA+2" ]


# pego el resultado en el dataset original y grabo
setorder( dsimple, pos )
dataset[, clase_ternaria := dsimple$clase_ternaria ]

Loading required package: data.table

In [ ]:
setorder( dataset, foto_mes, clase_ternaria, numero_de_cliente)
dataset[, .N, list(foto_mes, clase_ternaria)]

   foto_mes clase_ternaria N
1  202101   BAJA+1            622
2  202101   BAJA+2            825
3  202101   CONTINUA       160080
4  202102   BAJA+1            831
5  202102   BAJA+2           1032
6  202102   CONTINUA       160292
7  202103   BAJA+1           1039
8  202103   BAJA+2            951
9  202103   CONTINUA       161119
10 202104   BAJA+1            955
11 202104   BAJA+2           1130
12 202104   CONTINUA       161333
13 202105   NA             162783
14 202105   BAJA+1           1134
15 202106   NA             164313

ESTABILIZACIÓN POR IPC

In [ ]:
# =================== ESTABILIZACIÓN POR IPC (base 202104 = 100) ===================

library(data.table)

# 1) Tabla IPC ( % ya convertidos a índice con base abril=100)
ipc <- data.table(
  foto_mes = c(202101L, 202102L, 202103L, 202104L, 202105L, 202106L),
  indice   = c(90.7,     92.1,     95.4,     100.0,    103.3,    106.6)
)

# 2) Merge por foto_mes
stopifnot("foto_mes" %in% names(dataset))
dataset <- merge(dataset, ipc, by = "foto_mes", all.x = TRUE, sort = FALSE)

# 3) Deflactor relativo a 202104
dataset[, defl_factor := indice / 100]


# 4) Detectar columnas de montos a deflactar
#    - Montos "generales": empiezan con 'm'
#    - Montos de tarjetas: nombres como 'Master_m...' o 'Visa_m...'
montos_m_prefix <- grep("^m", names(dataset), value = TRUE)
montos_card     <- grep("^(Master|Visa)_m", names(dataset), value = TRUE)

montos_all <- unique(c(montos_m_prefix, montos_card))

# por si alguna coincide pero no es numérica
montos_all <- montos_all[vapply(dataset[, ..montos_all], is.numeric, logical(1))]

# 5) Deflactar IN-PLACE: x := x / defl_factor  (expresado en pesos constantes 202104)
for (cn in montos_all) {
  dataset[, (cn) := get(cn) / pmax(defl_factor, 1e-9)]
}

# 6) (Opcional) dejar rastro
#dataset[, ipc_base := 202104L]


cat("IPC aplicado (base 202104). Columnas deflactadas:", length(montos_all), "\n")
# =================== /ESTABILIZACIÓN POR IPC ===================

✅ IPC aplicado (base 202104). Columnas deflactadas: 73

In [ ]:
# eliminar columnas de IPC para no laguearlas ni usarlas como features
drop_ipc <- intersect(c("indice","defl_factor","ipc_base"), names(dataset))
if (length(drop_ipc)) dataset[, (drop_ipc) := NULL]

In [ ]:
ncol(dataset)
colnames(dataset)

[1] 155

  [1] "foto_mes"
  [2] "numero_de_cliente"
  [3] "active_quarter"
  [4] "cliente_vip"
  [5] "internet"
  [6] "cliente_edad"
  [7] "cliente_antiguedad"
  [8] "mrentabilidad"
  [9] "mrentabilidad_annual"
 [10] "mcomisiones"
 [11] "mactivos_margen"
 [12] "mpasivos_margen"
 [13] "cproductos"
 [14] "tcuentas"
 [15] "ccuenta_corriente"
 [16] "mcuenta_corriente_adicional"
 [17] "mcuenta_corriente"
 [18] "ccaja_ahorro"
 [19] "mcaja_ahorro"
 [20] "mcaja_ahorro_adicional"
 [21] "mcaja_ahorro_dolares"
 [22] "cdescubierto_preacordado"
 [23] "mcuentas_saldo"
 [24] "ctarjeta_debito"
 [25] "ctarjeta_debito_transacciones"
 [26] "mautoservicio"
 [27] "ctarjeta_visa"
 [28] "ctarjeta_visa_transacciones"
 [29] "mtarjeta_visa_consumo"
 [30] "ctarjeta_master"
 [31] "ctarjeta_master_transacciones"
 [32] "mtarjeta_master_consumo"
 [33] "cprestamos_personales"
 [34] "mprestamos_personales"
 [35] "cprestamos_prendarios"
 [36] "mprestamos_prendarios"
 [37] "cprestamos_hipotecarios"
 [38] "mprestamos_hipotecarios"
 [39] "cplazo_fijo"
 [40] "mplazo_fijo_dolares"
 [41] "mplazo_fijo_pesos"
 [42] "cinversion1"
 [43] "minversion1_pesos"
 [44] "minversion1_dolares"
 [45] "cinversion2"
 [46] "minversion2"
 [47] "cseguro_vida"
 [48] "cseguro_auto"
 [49] "cseguro_vivienda"
 [50] "cseguro_accidentes_personales"
 [51] "ccaja_seguridad"
 [52] "cpayroll_trx"
 [53] "mpayroll"
 [54] "mpayroll2"
 [55] "cpayroll2_trx"
 [56] "ccuenta_debitos_automaticos"
 [57] "mcuenta_debitos_automaticos"
 [58] "ctarjeta_visa_debitos_automaticos"
 [59] "mttarjeta_visa_debitos_automaticos"
 [60] "ctarjeta_master_debitos_automaticos"
 [61] "mttarjeta_master_debitos_automaticos"
 [62] "cpagodeservicios"
 [63] "mpagodeservicios"
 [64] "cpagomiscuentas"
 [65] "mpagomiscuentas"
 [66] "ccajeros_propios_descuentos"
 [67] "mcajeros_propios_descuentos"
 [68] "ctarjeta_visa_descuentos"
 [69] "mtarjeta_visa_descuentos"
 [70] "ctarjeta_master_descuentos"
 [71] "mtarjeta_master_descuentos"
 [72] "ccomisiones_mantenimiento"
 [73] "mcomisiones_mantenimiento"
 [74] "ccomisiones_otras"
 [75] "mcomisiones_otras"
 [76] "cforex"
 [77] "cforex_buy"
 [78] "mforex_buy"
 [79] "cforex_sell"
 [80] "mforex_sell"
 [81] "ctransferencias_recibidas"
 [82] "mtransferencias_recibidas"
 [83] "ctransferencias_emitidas"
 [84] "mtransferencias_emitidas"
 [85] "cextraccion_autoservicio"
 [86] "mextraccion_autoservicio"
 [87] "ccheques_depositados"
 [88] "mcheques_depositados"
 [89] "ccheques_emitidos"
 [90] "mcheques_emitidos"
 [91] "ccheques_depositados_rechazados"
 [92] "mcheques_depositados_rechazados"
 [93] "ccheques_emitidos_rechazados"
 [94] "mcheques_emitidos_rechazados"
 [95] "tcallcenter"
 [96] "ccallcenter_transacciones"
 [97] "thomebanking"
 [98] "chomebanking_transacciones"
 [99] "ccajas_transacciones"
[100] "ccajas_consultas"
[101] "ccajas_depositos"
[102] "ccajas_extracciones"
[103] "ccajas_otras"
[104] "catm_trx"
[105] "matm"
[106] "catm_trx_other"
[107] "matm_other"
[108] "ctrx_quarter"
[109] "tmobile_app"
[110] "cmobile_app_trx"
[111] "Master_delinquency"
[112] "Master_status"
[113] "Master_mfinanciacion_limite"
[114] "Master_Fvencimiento"
[115] "Master_Finiciomora"
[116] "Master_msaldototal"
[117] "Master_msaldopesos"
[118] "Master_msaldodolares"
[119] "Master_mconsumospesos"
[120] "Master_mconsumosdolares"
[121] "Master_mlimitecompra"
[122] "Master_madelantopesos"
[123] "Master_madelantodolares"
[124] "Master_fultimo_cierre"
[125] "Master_mpagado"
[126] "Master_mpagospesos"
[127] "Master_mpagosdolares"
[128] "Master_fechaalta"
[129] "Master_mconsumototal"
[130] "Master_cconsumos"
[131] "Master_cadelantosefectivo"
[132] "Master_mpagominimo"
[133] "Visa_delinquency"
[134] "Visa_status"
[135] "Visa_mfinanciacion_limite"
[136] "Visa_Fvencimiento"
[137] "Visa_Finiciomora"
[138] "Visa_msaldototal"
[139] "Visa_msaldopesos"
[140] "Visa_msaldodolares"
[141] "Visa_mconsumospesos"
[142] "Visa_mconsumosdolares"
[143] "Visa_mlimitecompra"
[144] "Visa_madelantopesos"
[145] "Visa_madelantodolares"
[146] "Visa_fultimo_cierre"
[147] "Visa_mpagado"
[148] "Visa_mpagospesos"
[149] "Visa_mpagosdolares"
[150] "Visa_fechaalta"
[151] "Visa_mconsumototal"
[152] "Visa_cconsumos"
[153] "Visa_cadelantosefectivo"
[154] "Visa_mpagominimo"
[155] "clase_ternaria"

SAC

In [ ]:
# ====== AJUSTE DE AGUINALDO  ======

evento_aguinaldo <- 202106L
tau <- 0.45

# señales de haberes
dataset[, payroll_monto := fcoalesce(mpayroll, 0) + fcoalesce(mpayroll2, 0)]
dataset[, payroll_freq  := fcoalesce(cpayroll_trx, 0L) + fcoalesce(cpayroll2_trx, 0L)]
dataset[, has_payroll   := as.integer(payroll_monto > 0 | payroll_freq > 0)]

# lags para sueldos
dataset[, `:=`(
  mpayroll_lag1       = shift(mpayroll, 1L),
  mpayroll2_lag1      = shift(mpayroll2, 1L),
  pay_monto_lag1      = shift(payroll_monto, 1L),
  cpayroll_trx_lag1   = shift(cpayroll_trx, 1L),
  cpayroll2_trx_lag1  = shift(cpayroll2_trx, 1L)
), by = numero_de_cliente]

# rolling max 6m PREVIO (excluye el mes actual)
dataset[, pay_max6_prev := frollapply(shift(payroll_monto, 1L),
                                      6L, max, align = "right", na.rm = TRUE),
        by = numero_de_cliente]

# SAC teórico en base a histórico previo
dataset[, sac_teorico := 0.5 * pay_max6_prev]

# salto vs mayo
dataset[, inc_vs_may := payroll_monto - pay_monto_lag1]

# detectar SAC solo si hay haberes y el salto es “≈ media remuneración previa”
dataset[, sac_flag := (foto_mes == evento_aguinaldo) &
                      ((fcoalesce(mpayroll, 0) + fcoalesce(mpayroll2, 0)) > 0) &
                      is.finite(inc_vs_may) & is.finite(pay_max6_prev) &
                      (inc_vs_may >= tau * pay_max6_prev)]

# 1) Ajuste mpayroll / mpayroll2 proporcional sin crear columnas extra
dataset[sac_flag == TRUE, `:=`(
  mpayroll  = {
    total <- pmax(mpayroll + mpayroll2, 1e-9)
    desc  <- pmin(sac_teorico, payroll_monto)
    pmax(0, mpayroll  - desc * (mpayroll  / total))
  },
  mpayroll2 = {
    total <- pmax(mpayroll + mpayroll2, 1e-9)
    desc  <- pmin(sac_teorico, payroll_monto)
    pmax(0, mpayroll2 - desc * (mpayroll2 / total))
  }
)]

# 2) Ajuste de saldo (usa lag/roll existentes, pero no crea columnas nuevas)
# cuantiles del TRAIN para cap
idx_train <- dataset$foto_mes %in% c(202101L, 202102L, 202103L, 202104L)
q1_s  <- as.numeric(quantile(dataset[idx_train, mcuentas_saldo], 0.01, na.rm = TRUE, type = 7))
q99_s <- as.numeric(quantile(dataset[idx_train, mcuentas_saldo], 0.99, na.rm = TRUE, type = 7))


if (!"mcuentas_saldo_lag1" %in% names(dataset))
  dataset[, mcuentas_saldo_lag1 := shift(mcuentas_saldo, 1L), by = numero_de_cliente]
if (!"mcuentas_saldo_roll_mean3" %in% names(dataset))
  dataset[, mcuentas_saldo_roll_mean3 := frollmean(mcuentas_saldo, 3L, align = "right"), by = numero_de_cliente]

dataset[sac_flag == TRUE & foto_mes == evento_aguinaldo,
        mcuentas_saldo := {
          base <- fifelse(!is.na(mcuentas_saldo_lag1), mcuentas_saldo_lag1, mcuentas_saldo_roll_mean3)
          inc  <- pmax(0, mcuentas_saldo - base)
          desc <- pmin(sac_teorico, payroll_monto)
          nuevo <- mcuentas_saldo - pmin(inc, desc)
          pmin(q99_s, pmax(q1_s, nuevo))
        }]


# Limpieza mínima de auxiliares de este bloque
dataset[, `:=`(inc_vs_may = NULL, sac_teorico = NULL)]
# ====== /SAC ======

  # --- limpiar auxiliares del bloque SAC ---
cols_temp <- c(
  "payroll_monto","payroll_freq","has_payroll","pay_monto_lag1",
  "pay_max6","sac_teorico","inc_vs_may","sac_flag","mcuentas_saldo_roll_mean3","pay_max6_prev"
)
cols_temp <- intersect(cols_temp, names(dataset))
if (length(cols_temp)) dataset[, (cols_temp) := NULL]

aux <- intersect(c("mpayroll_lag1","mpayroll2_lag1","pay_monto_lag1",
                   "cpayroll_trx_lag1","cpayroll2_trx_lag1",
                   "mcuentas_saldo_lag1","mcuentas_saldo_roll_mean3",
                   "pay_max6_prev","inc_vs_may","sac_teorico","sac_flag"),
                 names(dataset))
if (length(aux)) dataset[, (aux) := NULL]

In [ ]:
ncol(dataset)
colnames(dataset)

[1] 155

  [1] "foto_mes"
  [2] "numero_de_cliente"
  [3] "active_quarter"
  [4] "cliente_vip"
  [5] "internet"
  [6] "cliente_edad"
  [7] "cliente_antiguedad"
  [8] "mrentabilidad"
  [9] "mrentabilidad_annual"
 [10] "mcomisiones"
 [11] "mactivos_margen"
 [12] "mpasivos_margen"
 [13] "cproductos"
 [14] "tcuentas"
 [15] "ccuenta_corriente"
 [16] "mcuenta_corriente_adicional"
 [17] "mcuenta_corriente"
 [18] "ccaja_ahorro"
 [19] "mcaja_ahorro"
 [20] "mcaja_ahorro_adicional"
 [21] "mcaja_ahorro_dolares"
 [22] "cdescubierto_preacordado"
 [23] "mcuentas_saldo"
 [24] "ctarjeta_debito"
 [25] "ctarjeta_debito_transacciones"
 [26] "mautoservicio"
 [27] "ctarjeta_visa"
 [28] "ctarjeta_visa_transacciones"
 [29] "mtarjeta_visa_consumo"
 [30] "ctarjeta_master"
 [31] "ctarjeta_master_transacciones"
 [32] "mtarjeta_master_consumo"
 [33] "cprestamos_personales"
 [34] "mprestamos_personales"
 [35] "cprestamos_prendarios"
 [36] "mprestamos_prendarios"
 [37] "cprestamos_hipotecarios"
 [38] "mprestamos_hipotecarios"
 [39] "cplazo_fijo"
 [40] "mplazo_fijo_dolares"
 [41] "mplazo_fijo_pesos"
 [42] "cinversion1"
 [43] "minversion1_pesos"
 [44] "minversion1_dolares"
 [45] "cinversion2"
 [46] "minversion2"
 [47] "cseguro_vida"
 [48] "cseguro_auto"
 [49] "cseguro_vivienda"
 [50] "cseguro_accidentes_personales"
 [51] "ccaja_seguridad"
 [52] "cpayroll_trx"
 [53] "mpayroll"
 [54] "mpayroll2"
 [55] "cpayroll2_trx"
 [56] "ccuenta_debitos_automaticos"
 [57] "mcuenta_debitos_automaticos"
 [58] "ctarjeta_visa_debitos_automaticos"
 [59] "mttarjeta_visa_debitos_automaticos"
 [60] "ctarjeta_master_debitos_automaticos"
 [61] "mttarjeta_master_debitos_automaticos"
 [62] "cpagodeservicios"
 [63] "mpagodeservicios"
 [64] "cpagomiscuentas"
 [65] "mpagomiscuentas"
 [66] "ccajeros_propios_descuentos"
 [67] "mcajeros_propios_descuentos"
 [68] "ctarjeta_visa_descuentos"
 [69] "mtarjeta_visa_descuentos"
 [70] "ctarjeta_master_descuentos"
 [71] "mtarjeta_master_descuentos"
 [72] "ccomisiones_mantenimiento"
 [73] "mcomisiones_mantenimiento"
 [74] "ccomisiones_otras"
 [75] "mcomisiones_otras"
 [76] "cforex"
 [77] "cforex_buy"
 [78] "mforex_buy"
 [79] "cforex_sell"
 [80] "mforex_sell"
 [81] "ctransferencias_recibidas"
 [82] "mtransferencias_recibidas"
 [83] "ctransferencias_emitidas"
 [84] "mtransferencias_emitidas"
 [85] "cextraccion_autoservicio"
 [86] "mextraccion_autoservicio"
 [87] "ccheques_depositados"
 [88] "mcheques_depositados"
 [89] "ccheques_emitidos"
 [90] "mcheques_emitidos"
 [91] "ccheques_depositados_rechazados"
 [92] "mcheques_depositados_rechazados"
 [93] "ccheques_emitidos_rechazados"
 [94] "mcheques_emitidos_rechazados"
 [95] "tcallcenter"
 [96] "ccallcenter_transacciones"
 [97] "thomebanking"
 [98] "chomebanking_transacciones"
 [99] "ccajas_transacciones"
[100] "ccajas_consultas"
[101] "ccajas_depositos"
[102] "ccajas_extracciones"
[103] "ccajas_otras"
[104] "catm_trx"
[105] "matm"
[106] "catm_trx_other"
[107] "matm_other"
[108] "ctrx_quarter"
[109] "tmobile_app"
[110] "cmobile_app_trx"
[111] "Master_delinquency"
[112] "Master_status"
[113] "Master_mfinanciacion_limite"
[114] "Master_Fvencimiento"
[115] "Master_Finiciomora"
[116] "Master_msaldototal"
[117] "Master_msaldopesos"
[118] "Master_msaldodolares"
[119] "Master_mconsumospesos"
[120] "Master_mconsumosdolares"
[121] "Master_mlimitecompra"
[122] "Master_madelantopesos"
[123] "Master_madelantodolares"
[124] "Master_fultimo_cierre"
[125] "Master_mpagado"
[126] "Master_mpagospesos"
[127] "Master_mpagosdolares"
[128] "Master_fechaalta"
[129] "Master_mconsumototal"
[130] "Master_cconsumos"
[131] "Master_cadelantosefectivo"
[132] "Master_mpagominimo"
[133] "Visa_delinquency"
[134] "Visa_status"
[135] "Visa_mfinanciacion_limite"
[136] "Visa_Fvencimiento"
[137] "Visa_Finiciomora"
[138] "Visa_msaldototal"
[139] "Visa_msaldopesos"
[140] "Visa_msaldodolares"
[141] "Visa_mconsumospesos"
[142] "Visa_mconsumosdolares"
[143] "Visa_mlimitecompra"
[144] "Visa_madelantopesos"
[145] "Visa_madelantodolares"
[146] "Visa_fultimo_cierre"
[147] "Visa_mpagado"
[148] "Visa_mpagospesos"
[149] "Visa_mpagosdolares"
[150] "Visa_fechaalta"
[151] "Visa_mconsumototal"
[152] "Visa_cconsumos"
[153] "Visa_cadelantosefectivo"
[154] "Visa_mpagominimo"
[155] "clase_ternaria"

LAGS

In [ ]:
library(data.table)
setorder(dataset, numero_de_cliente, foto_mes)
setDTthreads(0L)




# Feature Engineering Historico
cols_lagueables <- copy( setdiff(
    colnames(dataset),
    c("numero_de_cliente","foto_mes","clase_ternaria","clase01",
                  "training","azar","cliente_antiguedad","cliente_edad",
                  "Master_status","Visa_status")
) )

#Prealocar (ahora que ya sabemos cuántas lagueables hay)
alloc.col(dataset, ncol(dataset) + 4L * length(cols_lagueables) + 50L)



dataset[,
    paste0(cols_lagueables, "_lag1") := shift(.SD, 1, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

dataset[,
    paste0(cols_lagueables, "_lag2") := shift(.SD, 2, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# agrego los delta lags de orden 1
for (vcol in cols_lagueables)
{
    dataset[, paste0(vcol, "_delta1") := get(vcol) - get(paste0(vcol, "_lag1"))]
    dataset[, paste0(vcol, "_delta2") := get(vcol) - get(paste0(vcol, "_lag2"))]
}





# Limpiar auxiliares (una sola vez)
dataset[, c("mes_id","mes_id_lag1","mes_id_lag2","cons1","cons2") := NULL]
gc()

# sanity check
faltan_lag2 <- setdiff(paste0(cols_lagueables, "_lag2"), names(dataset))
if (length(faltan_lag2)) stop("No se crearon estas _lag2: ", paste(faltan_lag2, collapse=", "))

cat(" LAGS/DELTAS OK — lag1:", length(cols_lagueables),
    " lag2:", length(cols_lagueables),
    " delta1:", length(cols_lagueables),
    " delta2:", length(cols_lagueables), "\n")

       foto_mes numero_de_cliente active_quarter cliente_vip internet
1      202101   249221323         1              0           0
2      202102   249221323         1              0           0
3      202103   249221323         1              0           0
4      202104   249221323         1              0           0
5      202105   249221323         1              0           0
6      202106   249221323         1              0           0
7      202101   249227600         1              0           0
8      202102   249227600         1              0           0
9      202103   249227600         1              0           0
10     202104   249227600         1              0           0
11     202105   249227600         1              0           0
12     202106   249227600         1              0           0
13     202101   249234235         1              0           0
14     202102   249234235         1              0           0
15     202103   249234235         1              0           0
16     202104   249234235         1              0           0
17     202105   249234235         1              0           0
18     202106   249234235         1              0           0
19     202101   249244449         1              0           0
20     202102   249244449         1              0           0
21     202103   249244449         1              0           0
22     202104   249244449         1              0           0
23     202105   249244449         1              0           0
24     202106   249244449         1              0           0
25     202101   249244739         1              0           0
26     202102   249244739         1              0           0
27     202103   249244739         1              0           0
28     202104   249244739         1              0           0
29     202105   249244739         1              0           0
30     202106   249244739         1              0           0
⋮      ⋮        ⋮                 ⋮              ⋮           ⋮
978410 202106   1597251555        0              0           0
978411 202106   1597272563        1              0           0
978412 202106   1597445254        1              0           0
978413 202106   1597466842        1              0           0
978414 202106   1597472675        1              0           0
978415 202106   1597503887        0              0           0
978416 202106   1597522333        0              0           0
978417 202106   1597542829        1              0           0
978418 202106   1597560771        0              0           0
978419 202106   1597582940        0              0           0
978420 202106   1597645801        0              0           0
978421 202106   1597703999        1              0           0
978422 202106   1597704144        1              0           0
978423 202106   1597704366        1              0           0
978424 202106   1597769268        1              0           0
978425 202106   1597771164        0              0           0
978426 202106   1597799678        1              0           0
978427 202106   1597913368        0              0           0
978428 202106   1598106408        0              0           0
978429 202106   1598127775        0              0           0
978430 202106   1598157023        0              0           0
978431 202106   1598163070        1              0           0
978432 202106   1598187647        1              0           0
978433 202106   1598190935        1              0           0
978434 202106   1598246212        0              0           0
978435 202106   1598368433        1              0           0
978436 202106   1598419415        1              0           0
978437 202106   1598425905        1              0           0
978438 202106   1598470389        1              0           0
978439 202106   1598550167        0              0           0
       cliente_edad cliente_antiguedad mrentabilidad mrentabilidad_annual
1      46            93                 3385.0496    17300.00
2      46            94                 3676.2758    20742.30
3      46            95                 5598.7212    25178.42
4      46            96                 5356.6200    29189.81
5      46            97                 2409.7289    30499.30
6      46            98                 2099.7280    30120.82
7      42           278                  547.0893    16892.83
8      42           279                  785.9935    15910.45
9      42           280                  825.9958    14466.54
10     42           281                 1113.2700    14121.64
11     42           282                  675.6438    13031.53
12     42           283                 1192.5797    12834.03
13     54            17                  889.2613    11631.53
14     54            18                 2949.0337    13210.13
15     54            19                 3003.7631    14567.45
16     55            20                 2990.7800    15628.07
17     55            21                 3356.8732    17750.53
18     55            22                 3413.0769    19840.50
19     61           290                30303.9802    72350.32
20     61           291                 4968.0782    74371.66
21     62           292                17869.4654    87473.75
22     62           293                 -766.2600    80440.93
23     62           294                -1727.2217    73864.24
24     62           295                 1383.9118    70644.91
25     66           320                 3645.8875    53790.51
26     66           321                 5016.2866    54145.53
27     66           322                 6511.7925    55595.30
28     66           323                 4590.3400    55070.10
29     66           324                 2792.8751    53333.88
30     66           325                 4728.2645    52798.14
⋮      ⋮            ⋮                  ⋮             ⋮
978410 28           1                      0.0000000     0.0000000
978411 36           1                    148.4333959   148.4333959
978412 24           1                    399.3808630   399.3808630
978413 30           1                    461.6979362   461.6979362
978414 25           1                     50.1969981    50.1969981
978415 30           1                      0.0000000     0.0000000
978416 24           1                      0.0000000     0.0000000
978417 21           1                      0.1782364     0.1782364
978418 25           1                     -4.1838649    -4.1838649
978419 42           1                      0.0000000     0.0000000
978420 34           1                      0.0000000     0.0000000
978421 33           1                     59.0900563    59.0900563
978422 40           1                  13264.9437148 13264.9437148
978423 19           1                     79.2307692    79.2307692
978424 20           1                      5.3189493     5.3189493
978425 27           1                      0.0000000     0.0000000
978426 30           1                    204.8499062   204.8499062
978427 27           1                      0.8161351     0.8161351
978428 34           1                    119.1369606   119.1369606
978429 53           1                      0.0000000     0.0000000
978430 24           1                      0.0000000     0.0000000
978431 25           1                     11.1163227    11.1163227
978432 51           1                      0.1594747     0.1594747
978433 33           1                      0.2814259     0.2814259
978434 26           1                      0.0000000     0.0000000
978435 58           1                   3867.8142589  3867.8142589
978436 30           1                     -2.1200750    -2.1200750
978437 28           1                      5.5534709     5.5534709
978438 78           1                    229.7936210   229.7936210
978439 59           1                      0.0000000     0.0000000
       mcomisiones  ⋯ Visa_fultimo_cierre Visa_mpagado Visa_mpagospesos
1       1409.1621   ⋯  4                      0.000    -22969.647
2       1336.0152   ⋯ -3                  55085.168    -55085.168
3        792.2956   ⋯  1                      0.000    -53179.706
4       1470.2000   ⋯  2                      0.000         0.000
5        976.5731   ⋯  5                      0.000    -16516.989
6       1151.2852   ⋯  0                      0.000    -18777.617
7        461.9294   ⋯ 11                  14627.883    -10653.264
8        298.3931   ⋯  4                      0.000    -14405.527
9        478.4696   ⋯  7                      0.000    -18429.067
10       746.8400   ⋯  9                      0.000    -13664.520
11       484.4530   ⋯ 12                  16359.981    -18663.795
12       760.2533   ⋯  7                      0.000    -15853.527
13       192.1279   ⋯  4                      0.000     -5173.098
14      1951.6938   ⋯ -3                      0.000     -8915.309
15      4001.1635   ⋯  1                      0.000    -34151.226
16      2355.7100   ⋯  2                      0.000    -54837.750
17      2307.1152   ⋯  5                      0.000    -14046.476
18      2234.0338   ⋯  0                      0.000     -3631.238
19     26009.5700   ⋯ 25                  26240.540    -22435.744
20      2234.5820   ⋯ 18                   2700.065    -25841.661
21     16744.1405   ⋯ 21                      0.000    -28161.237
22       716.6400   ⋯ 23                  54901.100         0.000
23       632.2265   ⋯ 26                  27713.398    -53147.241
24      2142.6923   ⋯ 21                  40078.443    -26855.478
25      3610.7497   ⋯  4                      0.000    -97219.813
26      3090.2497   ⋯ -3                      0.000    -41881.107
27      3116.5199   ⋯  1                      0.000    -60262.055
28      1338.6100   ⋯  2                      0.000    -59377.260
29      1137.8122   ⋯  5                      0.000    -58045.944
30      3238.7992   ⋯  0                      0.000    -40251.135
⋮      ⋮            ⋱ ⋮                   ⋮            ⋮
978410     0.000000 ⋯  7                  0            NA
978411     0.000000 ⋯  7                  0            NA
978412    26.538462 ⋯  7                  0            NA
978413    22.307692 ⋯  0                  0             0
978414     0.000000 ⋯  0                  0            NA
978415     0.000000 ⋯  0                  0            NA
978416     0.000000 ⋯  0                  0            NA
978417     0.000000 ⋯  0                  0            NA
978418     0.000000 ⋯  7                  0            NA
978419     0.000000 ⋯  0                  0            NA
978420     0.000000 ⋯  0                  0            NA
978421     0.000000 ⋯  0                  0            NA
978422 13225.253283 ⋯  0                  0             0
978423     3.602251 ⋯ 21                  0            NA
978424     0.000000 ⋯  7                  0            NA
978425     0.000000 ⋯  0                  0            NA
978426   124.746717 ⋯  0                  0             0
978427     0.000000 ⋯  0                  0            NA
978428     0.000000 ⋯  0                  0            NA
978429     0.000000 ⋯  0                  0            NA
978430     0.000000 ⋯  7                  0            NA
978431     0.000000 ⋯  0                  0            NA
978432     0.000000 ⋯  0                  0            NA
978433     0.000000 ⋯  0                  0            NA
978434     0.000000 ⋯ NA                  0            NA
978435  2103.667917 ⋯  7                  0             0
978436     0.000000 ⋯  7                  0            NA
978437     0.000000 ⋯  0                  0            NA
978438     0.000000 ⋯  7                  0            NA
978439     0.000000 ⋯ NA                  0            NA
       Visa_mpagosdolares Visa_fechaalta Visa_mconsumototal Visa_cconsumos
1        0.00000          2814            7434.8181          6
2        0.00000          2842            8377.0467          8
3        0.00000          2873           11219.0776          7
4        0.00000          2903            8094.7300          6
5        0.00000          2934            8762.8074          6
6        0.00000          2964           15104.7655          7
7        0.00000          5541           10385.7773          8
8        0.00000          5569           12972.3453          9
9        0.00000          5600            7237.1803          5
10       0.00000          5630            9515.7000         10
11       0.00000          5661            8010.8519          6
12       0.00000          5691            6901.6792          7
13       0.00000           577            3110.6064          2
14       0.00000           605            5226.5038          4
15      55.06289           636           70266.0377         14
16     586.50000           666            3511.9600          5
17       0.00000           697             374.7241          1
18       0.00000           727            9636.0507         10
19       0.00000          7916           25920.2977          8
20       0.00000          7944           26165.2769          9
21       0.00000          7975           25258.9727          9
22       0.00000          8005           31249.2100          9
23       0.00000          8036           24985.0242          8
24       0.00000          8066           24377.7861          8
25       0.00000          1958           22489.0187          8
26       0.00000          1986           33911.4007         14
27       0.00000          2017           36394.4759         14
28       0.00000          2047           48587.0400         14
29       0.00000          2078           29877.3475         14
30       0.00000          2108           38076.6979         14
⋮      ⋮                  ⋮              ⋮                  ⋮
978410 NA                 17                     NA         NA
978411 NA                 14                     NA         NA
978412 NA                 28                     NA         NA
978413  0                 28                 0.0000          0
978414 NA                 21                     NA         NA
978415 NA                 23                     NA         NA
978416 NA                 15                     NA         NA
978417 NA                  7                     NA         NA
978418 NA                 16                     NA         NA
978419 NA                  7                     NA         NA
978420 NA                  1                     NA         NA
978421 NA                 29                     NA         NA
978422  0                 29              1667.9362          1
978423 NA                 28                     NA         NA
978424 NA                 22                     NA         NA
978425 NA                  7                     NA         NA
978426  0                 20               660.2251          1
978427 NA                  7                     NA         NA
978428 NA                 20                     NA         NA
978429 NA                 16                     NA         NA
978430 NA                 15                     NA         NA
978431 NA                  7                     NA         NA
978432 NA                  8                     NA         NA
978433 NA                  9                     NA         NA
978434 NA                  2                     NA         NA
978435  0                 28             11746.4916          2
978436 NA                  9                     NA         NA
978437 NA                 20                     NA         NA
978438 NA                 15                     NA         NA
978439 NA                  3                     NA         NA
       Visa_cadelantosefectivo Visa_mpagominimo clase_ternaria
1      0                       10540.187        CONTINUA
2      0                        8049.251        CONTINUA
3      0                           0.000        CONTINUA
4      0                           0.000        CONTINUA
5      0                        2043.950        NA
6      0                        2321.792        NA
7      0                        2095.105        CONTINUA
8      0                        2419.870        CONTINUA
9      0                        2200.912        CONTINUA
10     0                        2803.470        CONTINUA
11     0                        2293.766        NA
12     0                        2519.859        NA
13     0                        7591.521        CONTINUA
14     0                       11628.111        CONTINUA
15     0                       53080.094        CONTINUA
16     0                        4539.510        CONTINUA
17     0                        3747.241        NA
18     0                        6789.315        NA
19     0                        1345.006        CONTINUA
20     0                        1350.033        CONTINUA
21     0                           0.000        CONTINUA
22     0                        3413.430        CONTINUA
23     0                        1021.975        NA
24     0                        1617.552        NA
25     0                        2896.935        CONTINUA
26     0                        5043.518        CONTINUA
27     0                        7992.138        CONTINUA
28     0                        3354.780        CONTINUA
29     0                        2395.963        NA
30     0                        2684.916        NA
⋮      ⋮                       ⋮                ⋮
978410 NA                         0.00000       NA
978411 NA                         0.00000       NA
978412 NA                         0.00000       NA
978413  0                       209.07129       NA
978414 NA                         0.00000       NA
978415 NA                         0.00000       NA
978416 NA                         0.00000       NA
978417 NA                         0.00000       NA
978418 NA                         0.00000       NA
978419 NA                         0.00000       NA
978420 NA                         0.00000       NA
978421 NA                         0.00000       NA
978422  0                        77.02627       NA
978423 NA                         0.00000       NA
978424 NA                         0.00000       NA
978425 NA                         0.00000       NA
978426  0                        33.01126       NA
978427 NA                         0.00000       NA
978428 NA                         0.00000       NA
978429 NA                         0.00000       NA
978430 NA                         0.00000       NA
978431 NA                         0.00000       NA
978432 NA                         0.00000       NA
978433 NA                         0.00000       NA
978434 NA                         0.00000       NA
978435  0                      1639.55910       NA
978436 NA                         0.00000       NA
978437 NA                         0.00000       NA
978438 NA                         0.00000       NA
978439 NA                         0.00000       NA

Warning message in `[.data.table`(dataset, , `:=`(c("mes_id", "mes_id_lag1", "mes_id_lag2", :
“Tried to assign NULL to column 'mes_id', but this column does not exist to remove”
Warning message in `[.data.table`(dataset, , `:=`(c("mes_id", "mes_id_lag1", "mes_id_lag2", :
“Tried to assign NULL to column 'mes_id_lag1', but this column does not exist to remove”
Warning message in `[.data.table`(dataset, , `:=`(c("mes_id", "mes_id_lag1", "mes_id_lag2", :
“Tried to assign NULL to column 'mes_id_lag2', but this column does not exist to remove”
Warning message in `[.data.table`(dataset, , `:=`(c("mes_id", "mes_id_lag1", "mes_id_lag2", :
“Tried to assign NULL to column 'cons1', but this column does not exist to remove”
Warning message in `[.data.table`(dataset, , `:=`(c("mes_id", "mes_id_lag1", "mes_id_lag2", :
“Tried to assign NULL to column 'cons2', but this column does not exist to remove”

       used      (Mb)   gc trigger (Mb)   max used  (Mb)
Ncells    742529   39.7   1454657    77.7   1454657   77.7
Vcells 551315774 4206.3 914777998  6979.3 551653961 4208.8

✅ LAGS/DELTAS OK — lag1: 148  lag2: 148  delta1: 148  delta2: 148

In [ ]:
ncol(dataset)
colnames(dataset)

[1] 747

  [1] "foto_mes"
  [2] "numero_de_cliente"
  [3] "active_quarter"
  [4] "cliente_vip"
  [5] "internet"
  [6] "cliente_edad"
  [7] "cliente_antiguedad"
  [8] "mrentabilidad"
  [9] "mrentabilidad_annual"
 [10] "mcomisiones"
 [11] "mactivos_margen"
 [12] "mpasivos_margen"
 [13] "cproductos"
 [14] "tcuentas"
 [15] "ccuenta_corriente"
 [16] "mcuenta_corriente_adicional"
 [17] "mcuenta_corriente"
 [18] "ccaja_ahorro"
 [19] "mcaja_ahorro"
 [20] "mcaja_ahorro_adicional"
 [21] "mcaja_ahorro_dolares"
 [22] "cdescubierto_preacordado"
 [23] "mcuentas_saldo"
 [24] "ctarjeta_debito"
 [25] "ctarjeta_debito_transacciones"
 [26] "mautoservicio"
 [27] "ctarjeta_visa"
 [28] "ctarjeta_visa_transacciones"
 [29] "mtarjeta_visa_consumo"
 [30] "ctarjeta_master"
 [31] "ctarjeta_master_transacciones"
 [32] "mtarjeta_master_consumo"
 [33] "cprestamos_personales"
 [34] "mprestamos_personales"
 [35] "cprestamos_prendarios"
 [36] "mprestamos_prendarios"
 [37] "cprestamos_hipotecarios"
 [38] "mprestamos_hipotecarios"
 [39] "cplazo_fijo"
 [40] "mplazo_fijo_dolares"
 [41] "mplazo_fijo_pesos"
 [42] "cinversion1"
 [43] "minversion1_pesos"
 [44] "minversion1_dolares"
 [45] "cinversion2"
 [46] "minversion2"
 [47] "cseguro_vida"
 [48] "cseguro_auto"
 [49] "cseguro_vivienda"
 [50] "cseguro_accidentes_personales"
 [51] "ccaja_seguridad"
 [52] "cpayroll_trx"
 [53] "mpayroll"
 [54] "mpayroll2"
 [55] "cpayroll2_trx"
 [56] "ccuenta_debitos_automaticos"
 [57] "mcuenta_debitos_automaticos"
 [58] "ctarjeta_visa_debitos_automaticos"
 [59] "mttarjeta_visa_debitos_automaticos"
 [60] "ctarjeta_master_debitos_automaticos"
 [61] "mttarjeta_master_debitos_automaticos"
 [62] "cpagodeservicios"
 [63] "mpagodeservicios"
 [64] "cpagomiscuentas"
 [65] "mpagomiscuentas"
 [66] "ccajeros_propios_descuentos"
 [67] "mcajeros_propios_descuentos"
 [68] "ctarjeta_visa_descuentos"
 [69] "mtarjeta_visa_descuentos"
 [70] "ctarjeta_master_descuentos"
 [71] "mtarjeta_master_descuentos"
 [72] "ccomisiones_mantenimiento"
 [73] "mcomisiones_mantenimiento"
 [74] "ccomisiones_otras"
 [75] "mcomisiones_otras"
 [76] "cforex"
 [77] "cforex_buy"
 [78] "mforex_buy"
 [79] "cforex_sell"
 [80] "mforex_sell"
 [81] "ctransferencias_recibidas"
 [82] "mtransferencias_recibidas"
 [83] "ctransferencias_emitidas"
 [84] "mtransferencias_emitidas"
 [85] "cextraccion_autoservicio"
 [86] "mextraccion_autoservicio"
 [87] "ccheques_depositados"
 [88] "mcheques_depositados"
 [89] "ccheques_emitidos"
 [90] "mcheques_emitidos"
 [91] "ccheques_depositados_rechazados"
 [92] "mcheques_depositados_rechazados"
 [93] "ccheques_emitidos_rechazados"
 [94] "mcheques_emitidos_rechazados"
 [95] "tcallcenter"
 [96] "ccallcenter_transacciones"
 [97] "thomebanking"
 [98] "chomebanking_transacciones"
 [99] "ccajas_transacciones"
[100] "ccajas_consultas"
[101] "ccajas_depositos"
[102] "ccajas_extracciones"
[103] "ccajas_otras"
[104] "catm_trx"
[105] "matm"
[106] "catm_trx_other"
[107] "matm_other"
[108] "ctrx_quarter"
[109] "tmobile_app"
[110] "cmobile_app_trx"
[111] "Master_delinquency"
[112] "Master_status"
[113] "Master_mfinanciacion_limite"
[114] "Master_Fvencimiento"
[115] "Master_Finiciomora"
[116] "Master_msaldototal"
[117] "Master_msaldopesos"
[118] "Master_msaldodolares"
[119] "Master_mconsumospesos"
[120] "Master_mconsumosdolares"
[121] "Master_mlimitecompra"
[122] "Master_madelantopesos"
[123] "Master_madelantodolares"
[124] "Master_fultimo_cierre"
[125] "Master_mpagado"
[126] "Master_mpagospesos"
[127] "Master_mpagosdolares"
[128] "Master_fechaalta"
[129] "Master_mconsumototal"
[130] "Master_cconsumos"
[131] "Master_cadelantosefectivo"
[132] "Master_mpagominimo"
[133] "Visa_delinquency"
[134] "Visa_status"
[135] "Visa_mfinanciacion_limite"
[136] "Visa_Fvencimiento"
[137] "Visa_Finiciomora"
[138] "Visa_msaldototal"
[139] "Visa_msaldopesos"
[140] "Visa_msaldodolares"
[141] "Visa_mconsumospesos"
[142] "Visa_mconsumosdolares"
[143] "Visa_mlimitecompra"
[144] "Visa_madelantopesos"
[145] "Visa_madelantodolares"
[146] "Visa_fultimo_cierre"
[147] "Visa_mpagado"
[148] "Visa_mpagospesos"
[149] "Visa_mpagosdolares"
[150] "Visa_fechaalta"
[151] "Visa_mconsumototal"
[152] "Visa_cconsumos"
[153] "Visa_cadelantosefectivo"
[154] "Visa_mpagominimo"
[155] "clase_ternaria"
[156] "active_quarter_lag1"
[157] "cliente_vip_lag1"
[158] "internet_lag1"
[159] "mrentabilidad_lag1"
[160] "mrentabilidad_annual_lag1"
[161] "mcomisiones_lag1"
[162] "mactivos_margen_lag1"
[163] "mpasivos_margen_lag1"
[164] "cproductos_lag1"
[165] "tcuentas_lag1"
[166] "ccuenta_corriente_lag1"
[167] "mcuenta_corriente_adicional_lag1"
[168] "mcuenta_corriente_lag1"
[169] "ccaja_ahorro_lag1"
[170] "mcaja_ahorro_lag1"
[171] "mcaja_ahorro_adicional_lag1"
[172] "mcaja_ahorro_dolares_lag1"
[173] "cdescubierto_preacordado_lag1"
[174] "mcuentas_saldo_lag1"
[175] "ctarjeta_debito_lag1"
[176] "ctarjeta_debito_transacciones_lag1"
[177] "mautoservicio_lag1"
[178] "ctarjeta_visa_lag1"
[179] "ctarjeta_visa_transacciones_lag1"
[180] "mtarjeta_visa_consumo_lag1"
[181] "ctarjeta_master_lag1"
[182] "ctarjeta_master_transacciones_lag1"
[183] "mtarjeta_master_consumo_lag1"
[184] "cprestamos_personales_lag1"
[185] "mprestamos_personales_lag1"
[186] "cprestamos_prendarios_lag1"
[187] "mprestamos_prendarios_lag1"
[188] "cprestamos_hipotecarios_lag1"
[189] "mprestamos_hipotecarios_lag1"
[190] "cplazo_fijo_lag1"
[191] "mplazo_fijo_dolares_lag1"
[192] "mplazo_fijo_pesos_lag1"
[193] "cinversion1_lag1"
[194] "minversion1_pesos_lag1"
[195] "minversion1_dolares_lag1"
[196] "cinversion2_lag1"
[197] "minversion2_lag1"
[198] "cseguro_vida_lag1"
[199] "cseguro_auto_lag1"
[200] "cseguro_vivienda_lag1"
[201] "cseguro_accidentes_personales_lag1"
[202] "ccaja_seguridad_lag1"
[203] "cpayroll_trx_lag1"
[204] "mpayroll_lag1"
[205] "mpayroll2_lag1"
[206] "cpayroll2_trx_lag1"
[207] "ccuenta_debitos_automaticos_lag1"
[208] "mcuenta_debitos_automaticos_lag1"
[209] "ctarjeta_visa_debitos_automaticos_lag1"
[210] "mttarjeta_visa_debitos_automaticos_lag1"
[211] "ctarjeta_master_debitos_automaticos_lag1"
[212] "mttarjeta_master_debitos_automaticos_lag1"
[213] "cpagodeservicios_lag1"
[214] "mpagodeservicios_lag1"
[215] "cpagomiscuentas_lag1"
[216] "mpagomiscuentas_lag1"
[217] "ccajeros_propios_descuentos_lag1"
[218] "mcajeros_propios_descuentos_lag1"
[219] "ctarjeta_visa_descuentos_lag1"
[220] "mtarjeta_visa_descuentos_lag1"
[221] "ctarjeta_master_descuentos_lag1"
[222] "mtarjeta_master_descuentos_lag1"
[223] "ccomisiones_mantenimiento_lag1"
[224] "mcomisiones_mantenimiento_lag1"
[225] "ccomisiones_otras_lag1"
[226] "mcomisiones_otras_lag1"
[227] "cforex_lag1"
[228] "cforex_buy_lag1"
[229] "mforex_buy_lag1"
[230] "cforex_sell_lag1"
[231] "mforex_sell_lag1"
[232] "ctransferencias_recibidas_lag1"
[233] "mtransferencias_recibidas_lag1"
[234] "ctransferencias_emitidas_lag1"
[235] "mtransferencias_emitidas_lag1"
[236] "cextraccion_autoservicio_lag1"
[237] "mextraccion_autoservicio_lag1"
[238] "ccheques_depositados_lag1"
[239] "mcheques_depositados_lag1"
[240] "ccheques_emitidos_lag1"
[241] "mcheques_emitidos_lag1"
[242] "ccheques_depositados_rechazados_lag1"
[243] "mcheques_depositados_rechazados_lag1"
[244] "ccheques_emitidos_rechazados_lag1"
[245] "mcheques_emitidos_rechazados_lag1"
[246] "tcallcenter_lag1"
[247] "ccallcenter_transacciones_lag1"
[248] "thomebanking_lag1"
[249] "chomebanking_transacciones_lag1"
[250] "ccajas_transacciones_lag1"
[251] "ccajas_consultas_lag1"
[252] "ccajas_depositos_lag1"
[253] "ccajas_extracciones_lag1"
[254] "ccajas_otras_lag1"
[255] "catm_trx_lag1"
[256] "matm_lag1"
[257] "catm_trx_other_lag1"
[258] "matm_other_lag1"
[259] "ctrx_quarter_lag1"
[260] "tmobile_app_lag1"
[261] "cmobile_app_trx_lag1"
[262] "Master_delinquency_lag1"
[263] "Master_mfinanciacion_limite_lag1"
[264] "Master_Fvencimiento_lag1"
[265] "Master_Finiciomora_lag1"
[266] "Master_msaldototal_lag1"
[267] "Master_msaldopesos_lag1"
[268] "Master_msaldodolares_lag1"
[269] "Master_mconsumospesos_lag1"
[270] "Master_mconsumosdolares_lag1"
[271] "Master_mlimitecompra_lag1"
[272] "Master_madelantopesos_lag1"
[273] "Master_madelantodolares_lag1"
[274] "Master_fultimo_cierre_lag1"
[275] "Master_mpagado_lag1"
[276] "Master_mpagospesos_lag1"
[277] "Master_mpagosdolares_lag1"
[278] "Master_fechaalta_lag1"
[279] "Master_mconsumototal_lag1"
[280] "Master_cconsumos_lag1"
[281] "Master_cadelantosefectivo_lag1"
[282] "Master_mpagominimo_lag1"
[283] "Visa_delinquency_lag1"
[284] "Visa_mfinanciacion_limite_lag1"
[285] "Visa_Fvencimiento_lag1"
[286] "Visa_Finiciomora_lag1"
[287] "Visa_msaldototal_lag1"
[288] "Visa_msaldopesos_lag1"
[289] "Visa_msaldodolares_lag1"
[290] "Visa_mconsumospesos_lag1"
[291] "Visa_mconsumosdolares_lag1"
[292] "Visa_mlimitecompra_lag1"
[293] "Visa_madelantopesos_lag1"
[294] "Visa_madelantodolares_lag1"
[295] "Visa_fultimo_cierre_lag1"
[296] "Visa_mpagado_lag1"
[297] "Visa_mpagospesos_lag1"
[298] "Visa_mpagosdolares_lag1"
[299] "Visa_fechaalta_lag1"
[300] "Visa_mconsumototal_lag1"
[301] "Visa_cconsumos_lag1"
[302] "Visa_cadelantosefectivo_lag1"
[303] "Visa_mpagominimo_lag1"
[304] "active_quarter_lag2"
[305] "cliente_vip_lag2"
[306] "internet_lag2"
[307] "mrentabilidad_lag2"
[308] "mrentabilidad_annual_lag2"
[309] "mcomisiones_lag2"
[310] "mactivos_margen_lag2"
[311] "mpasivos_margen_lag2"
[312] "cproductos_lag2"
[313] "tcuentas_lag2"
[314] "ccuenta_corriente_lag2"
[315] "mcuenta_corriente_adicional_lag2"
[316] "mcuenta_corriente_lag2"
[317] "ccaja_ahorro_lag2"
[318] "mcaja_ahorro_lag2"
[319] "mcaja_ahorro_adicional_lag2"
[320] "mcaja_ahorro_dolares_lag2"
[321] "cdescubierto_preacordado_lag2"
[322] "mcuentas_saldo_lag2"
[323] "ctarjeta_debito_lag2"
[324] "ctarjeta_debito_transacciones_lag2"
[325] "mautoservicio_lag2"
[326] "ctarjeta_visa_lag2"
[327] "ctarjeta_visa_transacciones_lag2"
[328] "mtarjeta_visa_consumo_lag2"
[329] "ctarjeta_master_lag2"
[330] "ctarjeta_master_transacciones_lag2"
[331] "mtarjeta_master_consumo_lag2"
[332] "cprestamos_personales_lag2"
[333] "mprestamos_personales_lag2"
[334] "cprestamos_prendarios_lag2"
[335] "mprestamos_prendarios_lag2"
[336] "cprestamos_hipotecarios_lag2"
[337] "mprestamos_hipotecarios_lag2"
[338] "cplazo_fijo_lag2"
[339] "mplazo_fijo_dolares_lag2"
[340] "mplazo_fijo_pesos_lag2"
[341] "cinversion1_lag2"
[342] "minversion1_pesos_lag2"
[343] "minversion1_dolares_lag2"
[344] "cinversion2_lag2"
[345] "minversion2_lag2"
[346] "cseguro_vida_lag2"
[347] "cseguro_auto_lag2"
[348] "cseguro_vivienda_lag2"
[349] "cseguro_accidentes_personales_lag2"
[350] "ccaja_seguridad_lag2"
[351] "cpayroll_trx_lag2"
[352] "mpayroll_lag2"
[353] "mpayroll2_lag2"
[354] "cpayroll2_trx_lag2"
[355] "ccuenta_debitos_automaticos_lag2"
[356] "mcuenta_debitos_automaticos_lag2"
[357] "ctarjeta_visa_debitos_automaticos_lag2"
[358] "mttarjeta_visa_debitos_automaticos_lag2"
[359] "ctarjeta_master_debitos_automaticos_lag2"
[360] "mttarjeta_master_debitos_automaticos_lag2"
[361] "cpagodeservicios_lag2"
[362] "mpagodeservicios_lag2"
[363] "cpagomiscuentas_lag2"
[364] "mpagomiscuentas_lag2"
[365] "ccajeros_propios_descuentos_lag2"
[366] "mcajeros_propios_descuentos_lag2"
[367] "ctarjeta_visa_descuentos_lag2"
[368] "mtarjeta_visa_descuentos_lag2"
[369] "ctarjeta_master_descuentos_lag2"
[370] "mtarjeta_master_descuentos_lag2"
[371] "ccomisiones_mantenimiento_lag2"
[372] "mcomisiones_mantenimiento_lag2"
[373] "ccomisiones_otras_lag2"
[374] "mcomisiones_otras_lag2"
[375] "cforex_lag2"
[376] "cforex_buy_lag2"
[377] "mforex_buy_lag2"
[378] "cforex_sell_lag2"
[379] "mforex_sell_lag2"
[380] "ctransferencias_recibidas_lag2"
[381] "mtransferencias_recibidas_lag2"
[382] "ctransferencias_emitidas_lag2"
[383] "mtransferencias_emitidas_lag2"
[384] "cextraccion_autoservicio_lag2"
[385] "mextraccion_autoservicio_lag2"
[386] "ccheques_depositados_lag2"
[387] "mcheques_depositados_lag2"
[388] "ccheques_emitidos_lag2"
[389] "mcheques_emitidos_lag2"
[390] "ccheques_depositados_rechazados_lag2"
[391] "mcheques_depositados_rechazados_lag2"
[392] "ccheques_emitidos_rechazados_lag2"
[393] "mcheques_emitidos_rechazados_lag2"
[394] "tcallcenter_lag2"
[395] "ccallcenter_transacciones_lag2"
[396] "thomebanking_lag2"
[397] "chomebanking_transacciones_lag2"
[398] "ccajas_transacciones_lag2"
[399] "ccajas_consultas_lag2"
[400] "ccajas_depositos_lag2"
[401] "ccajas_extracciones_lag2"
[402] "ccajas_otras_lag2"
[403] "catm_trx_lag2"
[404] "matm_lag2"
[405] "catm_trx_other_lag2"
[406] "matm_other_lag2"
[407] "ctrx_quarter_lag2"
[408] "tmobile_app_lag2"
[409] "cmobile_app_trx_lag2"
[410] "Master_delinquency_lag2"
[411] "Master_mfinanciacion_limite_lag2"
[412] "Master_Fvencimiento_lag2"
[413] "Master_Finiciomora_lag2"
[414] "Master_msaldototal_lag2"
[415] "Master_msaldopesos_lag2"
[416] "Master_msaldodolares_lag2"
[417] "Master_mconsumospesos_lag2"
[418] "Master_mconsumosdolares_lag2"
[419] "Master_mlimitecompra_lag2"
[420] "Master_madelantopesos_lag2"
[421] "Master_madelantodolares_lag2"
[422] "Master_fultimo_cierre_lag2"
[423] "Master_mpagado_lag2"
[424] "Master_mpagospesos_lag2"
[425] "Master_mpagosdolares_lag2"
[426] "Master_fechaalta_lag2"
[427] "Master_mconsumototal_lag2"
[428] "Master_cconsumos_lag2"
[429] "Master_cadelantosefectivo_lag2"
[430] "Master_mpagominimo_lag2"
[431] "Visa_delinquency_lag2"
[432] "Visa_mfinanciacion_limite_lag2"
[433] "Visa_Fvencimiento_lag2"
[434] "Visa_Finiciomora_lag2"
[435] "Visa_msaldototal_lag2"
[436] "Visa_msaldopesos_lag2"
[437] "Visa_msaldodolares_lag2"
[438] "Visa_mconsumospesos_lag2"
[439] "Visa_mconsumosdolares_lag2"
[440] "Visa_mlimitecompra_lag2"
[441] "Visa_madelantopesos_lag2"
[442] "Visa_madelantodolares_lag2"
[443] "Visa_fultimo_cierre_lag2"
[444] "Visa_mpagado_lag2"
[445] "Visa_mpagospesos_lag2"
[446] "Visa_mpagosdolares_lag2"
[447] "Visa_fechaalta_lag2"
[448] "Visa_mconsumototal_lag2"
[449] "Visa_cconsumos_lag2"
[450] "Visa_cadelantosefectivo_lag2"
[451] "Visa_mpagominimo_lag2"
[452] "active_quarter_delta1"
[453] "active_quarter_delta2"
[454] "cliente_vip_delta1"
[455] "cliente_vip_delta2"
[456] "internet_delta1"
[457] "internet_delta2"
[458] "mrentabilidad_delta1"
[459] "mrentabilidad_delta2"
[460] "mrentabilidad_annual_delta1"
[461] "mrentabilidad_annual_delta2"
[462] "mcomisiones_delta1"
[463] "mcomisiones_delta2"
[464] "mactivos_margen_delta1"
[465] "mactivos_margen_delta2"
[466] "mpasivos_margen_delta1"
[467] "mpasivos_margen_delta2"
[468] "cproductos_delta1"
[469] "cproductos_delta2"
[470] "tcuentas_delta1"
[471] "tcuentas_delta2"
[472] "ccuenta_corriente_delta1"
[473] "ccuenta_corriente_delta2"
[474] "mcuenta_corriente_adicional_delta1"
[475] "mcuenta_corriente_adicional_delta2"
[476] "mcuenta_corriente_delta1"
[477] "mcuenta_corriente_delta2"
[478] "ccaja_ahorro_delta1"
[479] "ccaja_ahorro_delta2"
[480] "mcaja_ahorro_delta1"
[481] "mcaja_ahorro_delta2"
[482] "mcaja_ahorro_adicional_delta1"
[483] "mcaja_ahorro_adicional_delta2"
[484] "mcaja_ahorro_dolares_delta1"
[485] "mcaja_ahorro_dolares_delta2"
[486] "cdescubierto_preacordado_delta1"
[487] "cdescubierto_preacordado_delta2"
[488] "mcuentas_saldo_delta1"
[489] "mcuentas_saldo_delta2"
[490] "ctarjeta_debito_delta1"
[491] "ctarjeta_debito_delta2"
[492] "ctarjeta_debito_transacciones_delta1"
[493] "ctarjeta_debito_transacciones_delta2"
[494] "mautoservicio_delta1"
[495] "mautoservicio_delta2"
[496] "ctarjeta_visa_delta1"
[497] "ctarjeta_visa_delta2"
[498] "ctarjeta_visa_transacciones_delta1"
[499] "ctarjeta_visa_transacciones_delta2"
[500] "mtarjeta_visa_consumo_delta1"
[501] "mtarjeta_visa_consumo_delta2"
[502] "ctarjeta_master_delta1"
[503] "ctarjeta_master_delta2"
[504] "ctarjeta_master_transacciones_delta1"
[505] "ctarjeta_master_transacciones_delta2"
[506] "mtarjeta_master_consumo_delta1"
[507] "mtarjeta_master_consumo_delta2"
[508] "cprestamos_personales_delta1"
[509] "cprestamos_personales_delta2"
[510] "mprestamos_personales_delta1"
[511] "mprestamos_personales_delta2"
[512] "cprestamos_prendarios_delta1"
[513] "cprestamos_prendarios_delta2"
[514] "mprestamos_prendarios_delta1"
[515] "mprestamos_prendarios_delta2"
[516] "cprestamos_hipotecarios_delta1"
[517] "cprestamos_hipotecarios_delta2"
[518] "mprestamos_hipotecarios_delta1"
[519] "mprestamos_hipotecarios_delta2"
[520] "cplazo_fijo_delta1"
[521] "cplazo_fijo_delta2"
[522] "mplazo_fijo_dolares_delta1"
[523] "mplazo_fijo_dolares_delta2"
[524] "mplazo_fijo_pesos_delta1"
[525] "mplazo_fijo_pesos_delta2"
[526] "cinversion1_delta1"
[527] "cinversion1_delta2"
[528] "minversion1_pesos_delta1"
[529] "minversion1_pesos_delta2"
[530] "minversion1_dolares_delta1"
[531] "minversion1_dolares_delta2"
[532] "cinversion2_delta1"
[533] "cinversion2_delta2"
[534] "minversion2_delta1"
[535] "minversion2_delta2"
[536] "cseguro_vida_delta1"
[537] "cseguro_vida_delta2"
[538] "cseguro_auto_delta1"
[539] "cseguro_auto_delta2"
[540] "cseguro_vivienda_delta1"
[541] "cseguro_vivienda_delta2"
[542] "cseguro_accidentes_personales_delta1"
[543] "cseguro_accidentes_personales_delta2"
[544] "ccaja_seguridad_delta1"
[545] "ccaja_seguridad_delta2"
[546] "cpayroll_trx_delta1"
[547] "cpayroll_trx_delta2"
[548] "mpayroll_delta1"
[549] "mpayroll_delta2"
[550] "mpayroll2_delta1"
[551] "mpayroll2_delta2"
[552] "cpayroll2_trx_delta1"
[553] "cpayroll2_trx_delta2"
[554] "ccuenta_debitos_automaticos_delta1"
[555] "ccuenta_debitos_automaticos_delta2"
[556] "mcuenta_debitos_automaticos_delta1"
[557] "mcuenta_debitos_automaticos_delta2"
[558] "ctarjeta_visa_debitos_automaticos_delta1"
[559] "ctarjeta_visa_debitos_automaticos_delta2"
[560] "mttarjeta_visa_debitos_automaticos_delta1"
[561] "mttarjeta_visa_debitos_automaticos_delta2"
[562] "ctarjeta_master_debitos_automaticos_delta1"
[563] "ctarjeta_master_debitos_automaticos_delta2"
[564] "mttarjeta_master_debitos_automaticos_delta1"
[565] "mttarjeta_master_debitos_automaticos_delta2"
[566] "cpagodeservicios_delta1"
[567] "cpagodeservicios_delta2"
[568] "mpagodeservicios_delta1"
[569] "mpagodeservicios_delta2"
[570] "cpagomiscuentas_delta1"
[571] "cpagomiscuentas_delta2"
[572] "mpagomiscuentas_delta1"
[573] "mpagomiscuentas_delta2"
[574] "ccajeros_propios_descuentos_delta1"
[575] "ccajeros_propios_descuentos_delta2"
[576] "mcajeros_propios_descuentos_delta1"
[577] "mcajeros_propios_descuentos_delta2"
[578] "ctarjeta_visa_descuentos_delta1"
[579] "ctarjeta_visa_descuentos_delta2"
[580] "mtarjeta_visa_descuentos_delta1"
[581] "mtarjeta_visa_descuentos_delta2"
[582] "ctarjeta_master_descuentos_delta1"
[583] "ctarjeta_master_descuentos_delta2"
[584] "mtarjeta_master_descuentos_delta1"
[585] "mtarjeta_master_descuentos_delta2"
[586] "ccomisiones_mantenimiento_delta1"
[587] "ccomisiones_mantenimiento_delta2"
[588] "mcomisiones_mantenimiento_delta1"
[589] "mcomisiones_mantenimiento_delta2"
[590] "ccomisiones_otras_delta1"
[591] "ccomisiones_otras_delta2"
[592] "mcomisiones_otras_delta1"
[593] "mcomisiones_otras_delta2"
[594] "cforex_delta1"
[595] "cforex_delta2"
[596] "cforex_buy_delta1"
[597] "cforex_buy_delta2"
[598] "mforex_buy_delta1"
[599] "mforex_buy_delta2"
[600] "cforex_sell_delta1"
[601] "cforex_sell_delta2"
[602] "mforex_sell_delta1"
[603] "mforex_sell_delta2"
[604] "ctransferencias_recibidas_delta1"
[605] "ctransferencias_recibidas_delta2"
[606] "mtransferencias_recibidas_delta1"
[607] "mtransferencias_recibidas_delta2"
[608] "ctransferencias_emitidas_delta1"
[609] "ctransferencias_emitidas_delta2"
[610] "mtransferencias_emitidas_delta1"
[611] "mtransferencias_emitidas_delta2"
[612] "cextraccion_autoservicio_delta1"
[613] "cextraccion_autoservicio_delta2"
[614] "mextraccion_autoservicio_delta1"
[615] "mextraccion_autoservicio_delta2"
[616] "ccheques_depositados_delta1"
[617] "ccheques_depositados_delta2"
[618] "mcheques_depositados_delta1"
[619] "mcheques_depositados_delta2"
[620] "ccheques_emitidos_delta1"
[621] "ccheques_emitidos_delta2"
[622] "mcheques_emitidos_delta1"
[623] "mcheques_emitidos_delta2"
[624] "ccheques_depositados_rechazados_delta1"
[625] "ccheques_depositados_rechazados_delta2"
[626] "mcheques_depositados_rechazados_delta1"

In [ ]:
fwrite( dataset,
    file =  "/content/datasets/competencia_01.csv.gz",
    sep = ","
)

### 2.2 Optimizacion Hiperparámetros

limpio el ambiente de R

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Oct 12 00:10:34 2025"

In [ ]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb)   max used  (Mb)
Ncells  743978 39.8   1454657    77.7   1454657   77.7
Vcells 1413991 10.8 731822399  5583.4 552236412 4213.3

### 2.2.2 Carga de Librerias

In [ ]:
# cargo las librerias que necesito
require("data.table")
require("parallel")

if(!require("R.utils")) install.packages("R.utils")
require("R.utils")

if( !require("primes") ) install.packages("primes")
require("primes")

if( !require("utils") ) install.packages("utils")
require("utils")

if( !require("rlist") ) install.packages("rlist")
require("rlist")

if( !require("yaml")) install.packages("yaml")
require("yaml")

if( !require("lightgbm") ) install.packages("lightgbm")
require("lightgbm")

if( !require("DiceKriging") ) install.packages("DiceKriging")
require("DiceKriging")

if( !require("mlrMBO") ) install.packages("mlrMBO")
require("mlrMBO")

Loading required package: parallel

Loading required package: R.utils

Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.


Attaching package: ‘R.oo’


The following object is masked from ‘package:R.methodsS3’:

    throw


The following objects are masked from ‘package:methods’:

    getClasses, getMethods


The following objects are masked from ‘package:base’:

    attach, detach, load, save


R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.


Attaching package: ‘R.utils’


The following object is masked from ‘package:utils’:

    timestamp


The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings


Loading required package: primes

Loading required package: rlist

Loading required package: yaml

Loading required package: lightgbm

Loading required package: DiceKriging

Loading required package: mlrMBO

Loading required package: mlr

Loading required package: ParamHelpers


Attaching package: ‘ParamHelpers’


The following object is masked from ‘package:R.utils’:

    isVector



Attaching package: ‘mlr’


The following objects are masked from ‘package:R.utils’:

    resample, setThreshold


Loading required package: smoof

Loading required package: checkmate


Attaching package: ‘checkmate’


The following object is masked from ‘package:DiceKriging’:

    checkNames


The following object is masked from ‘package:R.utils’:

    asInt



Attaching package: ‘smoof’


The following objects are masked from ‘package:R.oo’:

    getDescription, getName

### 2.2.3 Definicion de Parametros

In [ ]:
PARAM <- list()
PARAM$experimento <- "TP1_11_4"
PARAM$semilla_primigenia <- 102191

In [ ]:
# training y future
# BO: 202103 completo + 202101, 202102 solo BAJAS
PARAM$train_full    <- c(202103L)
PARAM$train_posonly <- c(202101L, 202102L)

PARAM$train <- c(202101, 202102,202103)
PARAM$valid <- c(202104)
PARAM$train_final <- c(202101, 202102, 202103, 202104)
PARAM$future <- c(202106)
PARAM$semilla_kaggle <- 314159
PARAM$cortes <- seq(6000, 19000, by= 250)

In [ ]:
# un undersampling de 0.1  toma solo el 10% de los CONTINUA
# undersampling de 1.0  implica tomar TODOS los datos

PARAM$trainingstrategy$undersampling <- 1.0

In [ ]:
# Parametros LightGBM

PARAM$hyperparametertuning$xval_folds <- 5

# parametros fijos del LightGBM que se pisaran con la parte variable de la BO
PARAM$lgbm$param_fijos <-  list(
  boosting= "gbdt", # puede ir  dart  , ni pruebe random_forest
  objective= "binary",
  metric= "auc",
  first_metric_only= FALSE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  force_row_wise= TRUE, # para reducir warnings
  verbosity= -100,

  seed= PARAM$semilla_primigenia,

  max_depth= -1L, # -1 significa no limitar,  por ahora lo dejo fijo
  min_gain_to_split= 0, # min_gain_to_split >= 0
  min_sum_hessian_in_leaf= 0.001, #  min_sum_hessian_in_leaf >= 0.0
  lambda_l1= 0.0, # lambda_l1 >= 0.0
  lambda_l2= 0.0, # lambda_l2 >= 0.0
  max_bin= 31L, # lo debo dejar fijo, no participa de la BO

  bagging_fraction= 1.0, # 0.0 < bagging_fraction <= 1.0
  pos_bagging_fraction= 1.0, # 0.0 < pos_bagging_fraction <= 1.0
  neg_bagging_fraction= 1.0, # 0.0 < neg_bagging_fraction <= 1.0
  is_unbalance= FALSE, #
  scale_pos_weight= 1.0, # scale_pos_weight > 0.0

  drop_rate= 0.1, # 0.0 < neg_bagging_fraction <= 1.0
  max_drop= 50, # <=0 means no limit
  skip_drop= 0.5, # 0.0 <= skip_drop <= 1.0

  extra_trees= FALSE,

  num_iterations= 1200,
  learning_rate= 0.02,
  feature_fraction= 0.5,
  num_leaves= 750,
  min_data_in_leaf= 5000
)

In [ ]:
# Aqui se cargan los bordes de los hiperparametros de la BO
PARAM$hyperparametertuning$hs <- makeParamSet(
  makeIntegerParam("num_iterations", lower= 8L, upper= 2048L),
  makeNumericParam("learning_rate", lower= 0.01, upper= 0.3),
  makeNumericParam("feature_fraction", lower= 0.1, upper= 1.0),
  makeIntegerParam("num_leaves", lower= 8L, upper= 2048L),
  makeIntegerParam("min_data_in_leaf", lower= 1L, upper= 8000L),
  #makeNumericParam("min_gain_to_split", lower=0.0, upper=5.0),
  makeNumericParam("lambda_l1", lower=0.0, upper=50.0),
  makeNumericParam("lambda_l2", lower=0.0, upper=50.0)

)

In [ ]:
PARAM$hyperparametertuning$iteraciones <- 50 # iteraciones bayesianas

In [ ]:
# particionar agrega una columna llamada fold a un dataset
#   que consiste en una particion estratificada segun agrupa
# particionar( data=dataset, division=c(70,30),
#  agrupa=clase_ternaria, seed=semilla)   crea una particion 70, 30

particionar <- function(data, division, agrupa= "", campo= "fold", start= 1, seed= NA) {
  if (!is.na(seed)) set.seed(seed, "L'Ecuyer-CMRG")

  bloque <- unlist(mapply(
    function(x, y) {rep(y, x)},division, seq(from= start, length.out= length(division))))

  data[, (campo) := sample(rep(bloque,ceiling(.N / length(bloque))))[1:.N],by= agrupa]
}

In [ ]:
# iniciliazo el dataset de realidad, para medir ganancia
realidad_inicializar <- function( pfuture, pparam) {

  # datos para verificar la ganancia
  drealidad <- pfuture[, list(numero_de_cliente, foto_mes, clase_ternaria)]

  particionar(drealidad,
    division= c(3, 7),
    agrupa= "clase_ternaria",
    seed= PARAM$semilla_kaggle
  )

  return( drealidad )
}

In [ ]:
# evaluo ganancia en los datos de la realidad

realidad_evaluar <- function( prealidad, pprediccion) {

  prealidad[ pprediccion,
    on= c("numero_de_cliente", "foto_mes"),
    predicted:= i.Predicted
  ]

  tbl <- prealidad[, list("qty"=.N), list(fold, predicted, clase_ternaria)]

  res <- list()
  res$public  <- tbl[fold==1 & predicted==1L, sum(qty*ifelse(clase_ternaria=="BAJA+2", 780000, -20000))]/0.3
  res$private <- tbl[fold==2 & predicted==1L, sum(qty*ifelse(clase_ternaria=="BAJA+2", 780000, -20000))]/0.7
  res$total <- tbl[predicted==1L, sum(qty*ifelse(clase_ternaria=="BAJA+2", 780000, -20000))]

  prealidad[, predicted:=NULL]
  return( res )
}

### 2.2.4  Preprocesamiento

In [ ]:
# carpeta de trabajo

setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("HT", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

In [ ]:
# lectura del dataset
dataset <- fread("/content/datasets/competencia_01.csv.gz", stringsAsFactors= TRUE)

In [ ]:
idx_train <- (dataset$foto_mes %in% c(PARAM$train_full, PARAM$train_posonly))
dataset_train <- dataset[idx_train]

In [ ]:
# paso la clase a binaria que tome valores {0,1}  enteros
#  BAJA+1 y BAJA+2  son  1,   CONTINUA es 0
#  a partir de ahora ya NO puedo cortar  por prob(BAJA+2) > 1/40

dataset_train[,
  clase01 := ifelse(clase_ternaria %in% c("BAJA+2","BAJA+1"), 1L, 0L)
]

In [ ]:
# defino los datos que forma parte del training
# aqui se hace el undersampling de los CONTINUA
# notar que para esto utilizo la SEGUNDA semilla

set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset_train[, azar := runif(nrow(dataset_train))]
dataset_train[, training := 0L]


dataset_train[
  (foto_mes %in% PARAM$train_full) |
  (foto_mes %in% PARAM$train_posonly &  clase01==1L),
  training := 1L
]

In [ ]:
# los campos que se van a utilizar

campos_buenos <- setdiff(
  colnames(dataset_train),
  c("numero_de_cliente", "clase_ternaria", "clase01", "azar", "training")
)

In [ ]:
# dejo los datos en el formato que necesita LightGBM

dtrain <- lgb.Dataset(
  data= data.matrix(dataset_train[training == 1L, campos_buenos, with= FALSE]),
  label= dataset_train[training == 1L, clase01],
  free_raw_data= FALSE
)

nrow(dtrain)
ncol(dtrain)

[1] 166419

[1] 745

2.2.5 Configuracion Bayesian Optimization

In [ ]:
# En el argumento x llegan los parmaetros de la bayesiana
#  devuelve la AUC en cross validation del modelo entrenado

EstimarGanancia_AUC_lightgbm <- function(x) {

  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)
  nrounds_es <- if (!is.null(param_completo$num_iterations)) as.integer(param_completo$num_iterations) else 1200L
  es_rounds  <- max(50L, round(nrounds_es * 0.15))
  param_completo$data_random_seed <- NULL

  # entreno LightGBM
  modelocv <- lgb.cv(
    data= dtrain,
    nfold= PARAM$hyperparametertuning$xval_folds,
    stratified= TRUE,
    param= param_completo,
    nrounds = nrounds_es,
    early_stopping_rounds = es_rounds,
    verbose = -1
  )

  # obtengo la ganancia
  AUC <- modelocv$best_score

  # hago espacio en la memoria
  rm(modelocv)
  gc(full= TRUE, verbose= FALSE)

  message(format(Sys.time(), "%a %b %d %X %Y"), " AUC ", AUC)

  return(AUC)
}

In [ ]:
# Aqui comienza la configuracion de la Bayesian Optimization

# en este archivo quedan la evolucion binaria de la BO
kbayesiana <- "bayesiana.RDATA"

funcion_optimizar <- EstimarGanancia_AUC_lightgbm # la funcion que voy a maximizar

configureMlr(show.learner.output= FALSE)

# configuro la busqueda bayesiana,  los hiperparametros que se van a optimizar
# por favor, no desesperarse por lo complejo

obj.fun <- makeSingleObjectiveFunction(
  fn= funcion_optimizar, # la funcion que voy a maximizar
  minimize= FALSE, # estoy Maximizando la ganancia
  noisy= TRUE,
  par.set= PARAM$hyperparametertuning$hs, # definido al comienzo del programa
  has.simple.signature= FALSE # paso los parametros en una lista
)

# cada 600 segundos guardo el resultado intermedio
ctrl <- makeMBOControl(
  save.on.disk.at.time= 600, # se graba cada 600 segundos
  save.file.path= kbayesiana
) # se graba cada 600 segundos

# indico la cantidad de iteraciones que va a tener la Bayesian Optimization
ctrl <- setMBOControlTermination(
  ctrl,
  iters= PARAM$hyperparametertuning$iteraciones
) # cantidad de iteraciones

# defino el método estandar para la creacion de los puntos iniciales,
# los "No Inteligentes"
ctrl <- setMBOControlInfill(ctrl, crit= makeMBOInfillCritEI())

# establezco la funcion que busca el maximo
surr.km <- makeLearner(
  "regr.km",
  predict.type= "se",
  covtype= "matern3_2",
  control= list(trace= TRUE)
)

2.2.6 Corrida Bayesian Optimization

In [ ]:
# inicio la optimizacion bayesiana, retomando si ya existe
# es la celda mas lenta de todo el notebook

if (!file.exists(kbayesiana)) {
  bayesiana_salida <- mbo(obj.fun, learner= surr.km, control= ctrl)
} else {
  bayesiana_salida <- mboContinue(kbayesiana) # retomo en caso que ya exista
}

Computing y column(s) for design. Not provided.

Sun Oct 12 00:12:22 2025 AUC 0.969267768569759

Sun Oct 12 00:14:06 2025 AUC 0.971513928172447

Sun Oct 12 00:14:37 2025 AUC 0.969875745487902

Sun Oct 12 00:16:10 2025 AUC 0.970965720081404

Sun Oct 12 00:17:17 2025 AUC 0.970540638988469

Sun Oct 12 00:18:43 2025 AUC 0.971692466545159

Sun Oct 12 00:20:32 2025 AUC 0.97148403296034

Sun Oct 12 00:22:45 2025 AUC 0.972031725043802

Sun Oct 12 00:23:50 2025 AUC 0.972219845479454

Sun Oct 12 00:25:23 2025 AUC 0.970001415292683

Sun Oct 12 00:30:28 2025 AUC 0.97037587703066

Sun Oct 12 00:32:25 2025 AUC 0.970862366944886

Sun Oct 12 00:33:09 2025 AUC 0.972843843967818

Sun Oct 12 00:33:46 2025 AUC 0.970740326256383

Sun Oct 12 00:34:28 2025 AUC 0.971451267639534

Sun Oct 12 00:38:14 2025 AUC 0.973638645172364

Sun Oct 12 00:38:28 2025 AUC 0.955642263191653

Sun Oct 12 00:40:06 2025 AUC 0.971488608915034

Sun Oct 12 00:40:35 2025 AUC 0.970610184998523

Sun Oct 12 00:42:54 2025 AUC 0.971139516704923

Sun Oct 12 00:44:06 2025 AUC 0.971176344926204

Sun Oct 12 00:44:45 2025 AUC 0.970764692888296

Sun Oct 12 00:45:56 2025 AUC 0.970850343557031

Sun Oct 12 00:51:34 2025 AUC 0.972918486280864

Sun Oct 12 00:52:11 2025 AUC 0.970054326169722

Sun Oct 12 00:52:50 2025 AUC 0.971707202126607

Sun Oct 12 00:54:30 2025 AUC 0.971267912989205

Sun Oct 12 00:54:57 2025 AUC 0.970012469404183

[mbo] 0: num_iterations=348; learning_rate=0.199; feature_fraction=0.742; num_leaves=1206; min_data_in_leaf=6309; lambda_l1=46; lambda_l2=18 : y = 0.969 : 63.8 secs : initdesign

[mbo] 0: num_iterations=697; learning_rate=0.177; feature_fraction=0.388; num_leaves=858; min_data_in_leaf=4688; lambda_l1=16.7; lambda_l2=36.3 : y = 0.972 : 103.4 secs : initdesign

[mbo] 0: num_iterations=1443; learning_rate=0.189; feature_fraction=0.671; num_leaves=715; min_data_in_leaf=2854; lambda_l1=42.3; lambda_l2=25.2 : y = 0.97 : 31.4 secs : initdesign

[mbo] 0: num_iterations=1020; learning_rate=0.218; feature_fraction=0.287; num_leaves=1130; min_data_in_leaf=4267; lambda_l1=24.6; lambda_l2=12.3 : y = 0.971 : 92.3 secs : initdesign

[mbo] 0: num_iterations=1213; learning_rate=0.0915; feature_fraction=0.619; num_leaves=1574; min_data_in_leaf=7407; lambda_l1=29.1; lambda_l2=16 : y = 0.971 : 67.7 secs : initdesign

[mbo] 0: num_iterations=1069; learning_rate=0.276; feature_fraction=0.544; num_leaves=1627; min_data_in_leaf=2017; lambda_l1=26.4; lambda_l2=27.4 : y = 0.972 : 85.5 secs : initdesign

[mbo] 0: num_iterations=532; learning_rate=0.0931; feature_fraction=0.134; num_leaves=315; min_data_in_leaf=1942; lambda_l1=26.8; lambda_l2=31.9 : y = 0.971 : 109.0 secs : initdesign

[mbo] 0: num_iterations=1979; learning_rate=0.0565; feature_fraction=0.778; num_leaves=1066; min_data_in_leaf=6818; lambda_l1=5; lambda_l2=0.627 : y = 0.972 : 132.9 secs : initdesign

[mbo] 0: num_iterations=652; learning_rate=0.131; feature_fraction=0.614; num_leaves=1718; min_data_in_leaf=3079; lambda_l1=13.5; lambda_l2=5.5 : y = 0.972 : 64.9 secs : initdesign

[mbo] 0: num_iterations=860; learning_rate=0.152; feature_fraction=0.479; num_leaves=1381; min_data_in_leaf=5085; lambda_l1=38.7; lambda_l2=32.7 : y = 0.97 : 93.9 secs : initdesign

[mbo] 0: num_iterations=1375; learning_rate=0.0108; feature_fraction=0.167; num_leaves=60; min_data_in_leaf=5195; lambda_l1=31.3; lambda_l2=34.6 : y = 0.97 : 304.7 secs : initdesign

[mbo] 0: num_iterations=1500; learning_rate=0.253; feature_fraction=0.201; num_leaves=424; min_data_in_leaf=5625; lambda_l1=20.1; lambda_l2=42.3 : y = 0.971 : 116.4 secs : initdesign

[mbo] 0: num_iterations=460; learning_rate=0.171; feature_fraction=0.902; num_leaves=1441; min_data_in_leaf=2529; lambda_l1=19.4; lambda_l2=49.1 : y = 0.973 : 44.8 secs : initdesign

[mbo] 0: num_iterations=1585; learning_rate=0.137; feature_fraction=0.84; num_leaves=1851; min_data_in_leaf=860; lambda_l1=39.7; lambda_l2=7.38 : y = 0.971 : 36.7 secs : initdesign

[mbo] 0: num_iterations=224; learning_rate=0.243; feature_fraction=0.751; num_leaves=802; min_data_in_leaf=4560; lambda_l1=14.9; lambda_l2=17 : y = 0.971 : 42.1 secs : initdesign

[mbo] 0: num_iterations=1742; learning_rate=0.0495; feature_fraction=0.498; num_leaves=109; min_data_in_leaf=1312; lambda_l1=2.23; lambda_l2=43.5 : y = 0.974 : 225.9 secs : initdesign

[mbo] 0: num_iterations=37; learning_rate=0.0334; feature_fraction=0.327; num_leaves=533; min_data_in_leaf=5976; lambda_l1=47.3; lambda_l2=10.5 : y = 0.956 : 13.6 secs : initdesign

[mbo] 0: num_iterations=901; learning_rate=0.064; feature_fraction=0.919; num_leaves=513; min_data_in_leaf=6247; lambda_l1=22.2; lambda_l2=40.9 : y = 0.971 : 98.1 secs : initdesign

[mbo] 0: num_iterations=797; learning_rate=0.116; feature_fraction=0.83; num_leaves=261; min_data_in_leaf=444; lambda_l1=48.7; lambda_l2=13.5 : y = 0.971 : 29.7 secs : initdesign

[mbo] 0: num_iterations=1809; learning_rate=0.236; feature_fraction=0.429; num_leaves=1943; min_data_in_leaf=6934; lambda_l1=1.11; lambda_l2=48.1 : y = 0.971 : 138.4 secs : initdesign

[mbo] 0: num_iterations=1132; learning_rate=0.28; feature_fraction=0.394; num_leaves=1814; min_data_in_leaf=1665; lambda_l1=10.1; lambda_l2=4.18 : y = 0.971 : 72.0 secs : initdesign

[mbo] 0: num_iterations=383; learning_rate=0.291; feature_fraction=0.558; num_leaves=974; min_data_in_leaf=738; lambda_l1=43.7; lambda_l2=29.2 : y = 0.971 : 39.1 secs : initdesign

[mbo] 0: num_iterations=1846; learning_rate=0.261; feature_fraction=0.997; num_leaves=642; min_data_in_leaf=3782; lambda_l1=11.2; lambda_l2=38.2 : y = 0.971 : 70.7 secs : initdesign

[mbo] 0: num_iterations=1279; learning_rate=0.0246; feature_fraction=0.249; num_leaves=1509; min_data_in_leaf=3438; lambda_l1=6.58; lambda_l2=20.5 : y = 0.973 : 338.5 secs : initdesign

[mbo] 0: num_iterations=1630; learning_rate=0.209; feature_fraction=0.692; num_leaves=1248; min_data_in_leaf=7989; lambda_l1=36.5; lambda_l2=2.89 : y = 0.97 : 37.3 secs : initdesign

[mbo] 0: num_iterations=261; learning_rate=0.0812; feature_fraction=0.959; num_leaves=2031; min_data_in_leaf=3218; lambda_l1=33.2; lambda_l2=21.8 : y = 0.972 : 38.5 secs : initdesign

[mbo] 0: num_iterations=1905; learning_rate=0.156; feature_fraction=0.118; num_leaves=937; min_data_in_leaf=43; lambda_l1=35; lambda_l2=45.4 : y = 0.971 : 99.7 secs : initdesign

[mbo] 0: num_iterations=82; learning_rate=0.113; feature_fraction=0.325; num_leaves=201; min_data_in_leaf=7550; lambda_l1=7.43; lambda_l2=23.7 : y = 0.97 : 27.6 secs : initdesign

Saved the current state after iteration 1 in the file bayesiana.RDATA.

Sun Oct 12 01:02:38 2025 AUC 0.973234587474938

[mbo] 1: num_iterations=2040; learning_rate=0.0104; feature_fraction=0.744; num_leaves=1470; min_data_in_leaf=715; lambda_l1=19.6; lambda_l2=50 : y = 0.973 : 457.7 secs : infill_ei

Sun Oct 12 01:03:34 2025 AUC 0.972748502427421

[mbo] 2: num_iterations=1106; learning_rate=0.0888; feature_fraction=0.945; num_leaves=30; min_data_in_leaf=22; lambda_l1=20.9; lambda_l2=40.4 : y = 0.973 : 55.1 secs : infill_ei

Sun Oct 12 01:09:21 2025 AUC 0.973784087942415

[mbo] 3: num_iterations=1716; learning_rate=0.0193; feature_fraction=0.1; num_leaves=522; min_data_in_leaf=921; lambda_l1=11.9; lambda_l2=49.7 : y = 0.974 : 346.2 secs : infill_ei

Saved the current state after iteration 4 in the file bayesiana.RDATA.

Sun Oct 12 01:11:13 2025 AUC 0.972657312167048

[mbo] 4: num_iterations=1170; learning_rate=0.0695; feature_fraction=0.991; num_leaves=2020; min_data_in_leaf=3029; lambda_l1=17.8; lambda_l2=49.4 : y = 0.973 : 109.0 secs : infill_ei

Sun Oct 12 01:13:23 2025 AUC 0.972549776739855

[mbo] 5: num_iterations=913; learning_rate=0.088; feature_fraction=0.101; num_leaves=308; min_data_in_leaf=3; lambda_l1=0.539; lambda_l2=42.7 : y = 0.973 : 129.2 secs : infill_ei

Sun Oct 12 01:23:49 2025 AUC 0.972807241910167

[mbo] 6: num_iterations=1992; learning_rate=0.0102; feature_fraction=0.343; num_leaves=233; min_data_in_leaf=3685; lambda_l1=12.7; lambda_l2=48.8 : y = 0.973 : 625.5 secs : infill_ei

Saved the current state after iteration 7 in the file bayesiana.RDATA.

Sun Oct 12 01:31:52 2025 AUC 0.973438347241715

[mbo] 7: num_iterations=1376; learning_rate=0.0108; feature_fraction=0.666; num_leaves=1196; min_data_in_leaf=328; lambda_l1=4.27; lambda_l2=49.5 : y = 0.973 : 479.9 secs : infill_ei

Sun Oct 12 01:38:47 2025 AUC 0.97295510240512

[mbo] 8: num_iterations=2048; learning_rate=0.0278; feature_fraction=0.159; num_leaves=1837; min_data_in_leaf=2; lambda_l1=6.22; lambda_l2=37.6 : y = 0.973 : 414.3 secs : infill_ei

Saved the current state after iteration 9 in the file bayesiana.RDATA.

Sun Oct 12 01:39:09 2025 AUC 0.970974848472927

[mbo] 9: num_iterations=379; learning_rate=0.258; feature_fraction=0.988; num_leaves=1395; min_data_in_leaf=53; lambda_l1=38.4; lambda_l2=49.6 : y = 0.971 : 19.6 secs : infill_ei

Sun Oct 12 01:39:55 2025 AUC 0.972058259273008

[mbo] 10: num_iterations=502; learning_rate=0.108; feature_fraction=0.924; num_leaves=1927; min_data_in_leaf=549; lambda_l1=25.9; lambda_l2=29.1 : y = 0.972 : 44.5 secs : infill_ei

Sun Oct 12 01:46:18 2025 AUC 0.973039797578084

[mbo] 11: num_iterations=1591; learning_rate=0.0101; feature_fraction=0.93; num_leaves=82; min_data_in_leaf=1492; lambda_l1=9.57; lambda_l2=24.6 : y = 0.973 : 382.4 secs : infill_ei

Sun Oct 12 01:55:35 2025 AUC 0.971772298328751

[mbo] 12: num_iterations=2027; learning_rate=0.0105; feature_fraction=0.288; num_leaves=9; min_data_in_leaf=52; lambda_l1=23.4; lambda_l2=46.8 : y = 0.972 : 556.2 secs : infill_ei

Saved the current state after iteration 13 in the file bayesiana.RDATA.

Sun Oct 12 01:58:45 2025 AUC 0.972708336220063

[mbo] 13: num_iterations=1528; learning_rate=0.0728; feature_fraction=0.102; num_leaves=1471; min_data_in_leaf=2184; lambda_l1=13.7; lambda_l2=49.9 : y = 0.973 : 187.2 secs : infill_ei

Sun Oct 12 02:10:12 2025 AUC 0.973114050116775

[mbo] 14: num_iterations=1764; learning_rate=0.0101; feature_fraction=0.568; num_leaves=991; min_data_in_leaf=2302; lambda_l1=0.481; lambda_l2=44.5 : y = 0.973 : 685.7 secs : infill_ei

Saved the current state after iteration 15 in the file bayesiana.RDATA.

Sun Oct 12 02:15:39 2025 AUC 0.972938367082105

[mbo] 15: num_iterations=1688; learning_rate=0.0103; feature_fraction=0.102; num_leaves=19; min_data_in_leaf=1594; lambda_l1=7.5; lambda_l2=26.6 : y = 0.973 : 325.0 secs : infill_ei

Sun Oct 12 02:19:03 2025 AUC 0.973292164785161

[mbo] 16: num_iterations=1683; learning_rate=0.0389; feature_fraction=0.716; num_leaves=700; min_data_in_leaf=1089; lambda_l1=9.92; lambda_l2=49.7 : y = 0.973 : 202.7 secs : infill_ei

Sun Oct 12 02:26:00 2025 AUC 0.97309382835169

[mbo] 17: num_iterations=1166; learning_rate=0.01; feature_fraction=0.61; num_leaves=1679; min_data_in_leaf=45; lambda_l1=15.4; lambda_l2=44.2 : y = 0.973 : 416.3 secs : infill_ei

Saved the current state after iteration 18 in the file bayesiana.RDATA.

Sun Oct 12 02:36:00 2025 AUC 0.973265771087675

[mbo] 18: num_iterations=1269; learning_rate=0.01; feature_fraction=0.382; num_leaves=758; min_data_in_leaf=71; lambda_l1=4.82; lambda_l2=49.9 : y = 0.973 : 597.1 secs : infill_ei

Sun Oct 12 02:37:38 2025 AUC 0.973222019522817

[mbo] 19: num_iterations=1326; learning_rate=0.065; feature_fraction=0.988; num_leaves=176; min_data_in_leaf=1697; lambda_l1=0.847; lambda_l2=23.2 : y = 0.973 : 96.9 secs : infill_ei

Saved the current state after iteration 20 in the file bayesiana.RDATA.

Sun Oct 12 02:38:18 2025 AUC 0.971722968031572

[mbo] 20: num_iterations=308; learning_rate=0.22; feature_fraction=1; num_leaves=2047; min_data_in_leaf=7781; lambda_l1=21.9; lambda_l2=44.1 : y = 0.972 : 37.9 secs : infill_ei

Sun Oct 12 02:43:07 2025 AUC 0.973273625983456

[mbo] 21: num_iterations=1738; learning_rate=0.0278; feature_fraction=0.881; num_leaves=1217; min_data_in_leaf=88; lambda_l1=2.31; lambda_l2=0.0634 : y = 0.973 : 287.7 secs : infill_ei

Sun Oct 12 02:49:13 2025 AUC 0.973219627662246

[mbo] 22: num_iterations=1701; learning_rate=0.0101; feature_fraction=1; num_leaves=2039; min_data_in_leaf=2476; lambda_l1=11.7; lambda_l2=20.6 : y = 0.973 : 365.4 secs : infill_ei

Saved the current state after iteration 23 in the file bayesiana.RDATA.

Sun Oct 12 02:50:13 2025 AUC 0.972556493737576

[mbo] 23: num_iterations=679; learning_rate=0.134; feature_fraction=0.783; num_leaves=8; min_data_in_leaf=101; lambda_l1=2.65; lambda_l2=44.2 : y = 0.973 : 56.3 secs : infill_ei

Sun Oct 12 02:52:01 2025 AUC 0.972719325961108

[mbo] 24: num_iterations=1962; learning_rate=0.13; feature_fraction=0.138; num_leaves=107; min_data_in_leaf=1178; lambda_l1=0.605; lambda_l2=48.5 : y = 0.973 : 107.6 secs : infill_ei

Sun Oct 12 02:53:55 2025 AUC 0.972307394568699

[mbo] 25: num_iterations=2014; learning_rate=0.151; feature_fraction=0.999; num_leaves=2031; min_data_in_leaf=1043; lambda_l1=1.48; lambda_l2=10.4 : y = 0.972 : 113.1 secs : infill_ei

Sun Oct 12 02:55:58 2025 AUC 0.972410956258475

[mbo] 26: num_iterations=1324; learning_rate=0.064; feature_fraction=0.793; num_leaves=8; min_data_in_leaf=5481; lambda_l1=2.43; lambda_l2=49.9 : y = 0.972 : 121.6 secs : infill_ei

Sun Oct 12 02:56:30 2025 AUC 0.971488396606254

[mbo] 27: num_iterations=1056; learning_rate=0.182; feature_fraction=0.895; num_leaves=75; min_data_in_leaf=25; lambda_l1=32.7; lambda_l2=22.6 : y = 0.971 : 31.3 secs : infill_ei

Sun Oct 12 02:59:40 2025 AUC 0.972546251644239

[mbo] 28: num_iterations=1779; learning_rate=0.0219; feature_fraction=0.997; num_leaves=1269; min_data_in_leaf=1464; lambda_l1=17.2; lambda_l2=0.128 : y = 0.973 : 189.0 secs : infill_ei

Saved the current state after iteration 29 in the file bayesiana.RDATA.

Sun Oct 12 03:01:56 2025 AUC 0.972917812210151

[mbo] 29: num_iterations=575; learning_rate=0.0118; feature_fraction=0.998; num_leaves=2045; min_data_in_leaf=1782; lambda_l1=0.186; lambda_l2=7.35 : y = 0.973 : 133.1 secs : infill_ei

Sun Oct 12 03:02:04 2025 AUC 0.968954165882254

[mbo] 30: num_iterations=23; learning_rate=0.167; feature_fraction=0.998; num_leaves=1693; min_data_in_leaf=3721; lambda_l1=0.148; lambda_l2=26.6 : y = 0.969 : 7.0 secs : infill_ei

Sun Oct 12 03:06:27 2025 AUC 0.973554061435532

[mbo] 31: num_iterations=1376; learning_rate=0.0103; feature_fraction=0.83; num_leaves=1964; min_data_in_leaf=1388; lambda_l1=0.0922; lambda_l2=4.97 : y = 0.974 : 261.5 secs : infill_ei

Sun Oct 12 03:07:59 2025 AUC 0.972826729720863

[mbo] 32: num_iterations=1674; learning_rate=0.108; feature_fraction=0.607; num_leaves=9; min_data_in_leaf=34; lambda_l1=3.29; lambda_l2=4.01 : y = 0.973 : 91.6 secs : infill_ei

Sun Oct 12 03:09:56 2025 AUC 0.973695034909762

[mbo] 33: num_iterations=1140; learning_rate=0.0446; feature_fraction=0.986; num_leaves=1980; min_data_in_leaf=1053; lambda_l1=4.48; lambda_l2=0.228 : y = 0.974 : 115.7 secs : infill_ei

Saved the current state after iteration 34 in the file bayesiana.RDATA.

Sun Oct 12 03:15:46 2025 AUC 0.973653834296717

[mbo] 34: num_iterations=1353; learning_rate=0.01; feature_fraction=0.812; num_leaves=1634; min_data_in_leaf=1163; lambda_l1=5.54; lambda_l2=12.8 : y = 0.974 : 346.7 secs : infill_ei

Sun Oct 12 03:19:05 2025 AUC 0.973102297961984

[mbo] 35: num_iterations=2014; learning_rate=0.032; feature_fraction=0.683; num_leaves=2043; min_data_in_leaf=972; lambda_l1=3.94; lambda_l2=21.3 : y = 0.973 : 197.9 secs : infill_ei

Sun Oct 12 03:22:10 2025 AUC 0.973069487794004

[mbo] 36: num_iterations=1308; learning_rate=0.0166; feature_fraction=0.976; num_leaves=1956; min_data_in_leaf=2046; lambda_l1=4.84; lambda_l2=0.917 : y = 0.973 : 184.9 secs : infill_ei

Saved the current state after iteration 37 in the file bayesiana.RDATA.

Sun Oct 12 03:28:27 2025 AUC 0.972900338540171

[mbo] 37: num_iterations=1269; learning_rate=0.0499; feature_fraction=0.765; num_leaves=1583; min_data_in_leaf=6; lambda_l1=0.786; lambda_l2=13 : y = 0.973 : 374.2 secs : infill_ei

Sun Oct 12 03:33:57 2025 AUC 0.972588573965065

[mbo] 38: num_iterations=1594; learning_rate=0.01; feature_fraction=0.112; num_leaves=1429; min_data_in_leaf=1476; lambda_l1=11.2; lambda_l2=45 : y = 0.973 : 328.5 secs : infill_ei

Saved the current state after iteration 39 in the file bayesiana.RDATA.

Sun Oct 12 03:47:36 2025 AUC 0.973032571307474

[mbo] 39: num_iterations=1731; learning_rate=0.0108; feature_fraction=0.858; num_leaves=2046; min_data_in_leaf=22; lambda_l1=8.34; lambda_l2=48.8 : y = 0.973 : 816.0 secs : infill_ei

Saved the current state after iteration 40 in the file bayesiana.RDATA.

Sun Oct 12 03:49:12 2025 AUC 0.97288536752721

[mbo] 40: num_iterations=2047; learning_rate=0.112; feature_fraction=0.955; num_leaves=288; min_data_in_leaf=425; lambda_l1=13.8; lambda_l2=46.5 : y = 0.973 : 92.8 secs : infill_ei

Sun Oct 12 03:53:36 2025 AUC 0.972964074964585

[mbo] 41: num_iterations=969; learning_rate=0.0105; feature_fraction=0.962; num_leaves=370; min_data_in_leaf=832; lambda_l1=2.67; lambda_l2=31.1 : y = 0.973 : 262.9 secs : infill_ei

Sun Oct 12 03:56:53 2025 AUC 0.972866636805507

[mbo] 42: num_iterations=1813; learning_rate=0.0675; feature_fraction=0.105; num_leaves=351; min_data_in_leaf=577; lambda_l1=12.1; lambda_l2=49.9 : y = 0.973 : 195.9 secs : infill_ei

Sun Oct 12 03:58:41 2025 AUC 0.973277359228228

[mbo] 43: num_iterations=1294; learning_rate=0.0792; feature_fraction=0.991; num_leaves=1987; min_data_in_leaf=698; lambda_l1=8.53; lambda_l2=3.85 : y = 0.973 : 107.4 secs : infill_ei

Saved the current state after iteration 44 in the file bayesiana.RDATA.

Sun Oct 12 04:01:34 2025 AUC 0.973323897008295

[mbo] 44: num_iterations=1534; learning_rate=0.0342; feature_fraction=0.111; num_leaves=325; min_data_in_leaf=1012; lambda_l1=1.95; lambda_l2=14.2 : y = 0.973 : 170.3 secs : infill_ei

Sun Oct 12 04:02:37 2025 AUC 0.972358452601461

[mbo] 45: num_iterations=1312; learning_rate=0.147; feature_fraction=0.962; num_leaves=495; min_data_in_leaf=64; lambda_l1=16.7; lambda_l2=49.9 : y = 0.972 : 61.5 secs : infill_ei

Sun Oct 12 04:03:36 2025 AUC 0.973070275978535

[mbo] 46: num_iterations=620; learning_rate=0.0748; feature_fraction=0.999; num_leaves=2005; min_data_in_leaf=2951; lambda_l1=7.78; lambda_l2=0.66 : y = 0.973 : 57.7 secs : infill_ei

Sun Oct 12 04:06:02 2025 AUC 0.973807278028103

[mbo] 47: num_iterations=994; learning_rate=0.0448; feature_fraction=0.165; num_leaves=2047; min_data_in_leaf=832; lambda_l1=6.77; lambda_l2=5.83 : y = 0.974 : 145.2 secs : infill_ei

Sun Oct 12 04:12:40 2025 AUC 0.973607894208931

[mbo] 48: num_iterations=1017; learning_rate=0.0115; feature_fraction=0.598; num_leaves=2024; min_data_in_leaf=604; lambda_l1=5.97; lambda_l2=1.26 : y = 0.974 : 396.6 secs : infill_ei

Saved the current state after iteration 49 in the file bayesiana.RDATA.

Sun Oct 12 04:14:29 2025 AUC 0.973173054036442

[mbo] 49: num_iterations=767; learning_rate=0.0742; feature_fraction=0.43; num_leaves=1783; min_data_in_leaf=1124; lambda_l1=4.74; lambda_l2=6.35 : y = 0.973 : 106.4 secs : infill_ei

Sun Oct 12 04:18:08 2025 AUC 0.97321812285777

[mbo] 50: num_iterations=1042; learning_rate=0.0307; feature_fraction=0.107; num_leaves=514; min_data_in_leaf=774; lambda_l1=13.1; lambda_l2=16.8 : y = 0.973 : 217.0 secs : infill_ei

Saved the final state in the file bayesiana.RDATA

In [ ]:

tb_bayesiana <- as.data.table(bayesiana_salida$opt.path)
colnames( tb_bayesiana)

 [1] "num_iterations"   "learning_rate"    "feature_fraction" "num_leaves"
 [5] "min_data_in_leaf" "lambda_l1"        "lambda_l2"        "y"
 [9] "dob"              "eol"              "error.message"    "exec.time"
[13] "ei"               "error.model"      "train.time"       "prop.type"
[17] "propose.time"     "se"               "mean"

In [ ]:
# almaceno los resultados de la Bayesian Optimization
# y capturo los mejores hiperparametros encontrados

tb_bayesiana <- as.data.table(bayesiana_salida$opt.path)

tb_bayesiana[, iter := .I]

# ordeno en forma descendente por AUC = y
setorder(tb_bayesiana, -y)

# grabo para eventualmente poder utilizarlos en OTRA corrida
fwrite( tb_bayesiana,
  file= "BO_log.txt",
  sep= "\t"
)

# los mejores hiperparámetros son los que quedaron en el registro 1 de la tabla
PARAM$out$lgbm$mejores_hiperparametros <- tb_bayesiana[
  1, # el primero es el de mejor AUC
  setdiff(colnames(tb_bayesiana),
    c("y","dob","eol","error.message","exec.time","ei","error.model",
      "train.time","prop.type","propose.time","se","mean","iter")),
  with= FALSE
]


PARAM$out$lgbm$y <- tb_bayesiana[1, y]

In [ ]:
write_yaml( PARAM, file="PARAM.yml")

In [ ]:
print(PARAM$out$lgbm$mejores_hiperparametros)
print(PARAM$out$lgbm$y)

   num_iterations learning_rate feature_fraction num_leaves min_data_in_leaf
            <int>         <num>            <num>      <int>            <int>
1:            994    0.04483601        0.1651085       2047              832
   lambda_l1 lambda_l2
       <num>     <num>
1:  6.771127  5.828662
[1] 0.9738073

## 2.3  VALID

In [ ]:
setwd("/content/buckets/b1/exp")
experimento <- paste0("exp", PARAM$experimento)
dir.create(experimento, showWarnings= FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento ))

In [ ]:
# clase01
dataset[, clase01 := ifelse(clase_ternaria %in% c("BAJA+1", "BAJA+2"), 1L, 0L)]

In [ ]:
dataset_train <- dataset[foto_mes %in% PARAM$train]
dataset_train[,.N,clase_ternaria]

  clase_ternaria N
1 CONTINUA       481491
2 BAJA+2           2808
3 BAJA+1           2492

In [ ]:
# dejo los datos en el formato que necesita LightGBM

dtrain_valid <- lgb.Dataset(
  data= data.matrix(dataset_train[, campos_buenos, with= FALSE]),
  label= dataset_train[, clase01]
)

#### Hyperparameters

In [ ]:
param_final <- modifyList(PARAM$lgbm$param_fijos,
  PARAM$out$lgbm$mejores_hiperparametros)

param_final

$boosting
[1] "gbdt"

$objective
[1] "binary"

$metric
[1] "auc"

$first_metric_only
[1] FALSE

$boost_from_average
[1] TRUE

$feature_pre_filter
[1] FALSE

$force_row_wise
[1] TRUE

$verbosity
[1] -100

$seed
[1] 102191

$max_depth
[1] -1

$min_gain_to_split
[1] 0

$min_sum_hessian_in_leaf
[1] 0.001

$lambda_l1
[1] 6.771127

$lambda_l2
[1] 5.828662

$max_bin
[1] 31

$bagging_fraction
[1] 1

$pos_bagging_fraction
[1] 1

$neg_bagging_fraction
[1] 1

$is_unbalance
[1] FALSE

$scale_pos_weight
[1] 1

$drop_rate
[1] 0.1

$max_drop
[1] 50

$skip_drop
[1] 0.5

$extra_trees
[1] FALSE

$num_iterations
[1] 994

$learning_rate
[1] 0.04483601

$feature_fraction
[1] 0.1651085

$num_leaves
[1] 2047

$min_data_in_leaf
[1] 832

In [ ]:
# este punto es muy SUTIL  y será revisado en la Clase 05

param_normalizado <- copy(param_final)
param_normalizado$min_data_in_leaf <-  round(param_final$min_data_in_leaf / PARAM$trainingstrategy$undersampling)

In [ ]:
# Entrenar en TRAIN y predecir en VALID

modelo_valid <- lgb.train(
  data= dtrain_valid,
  param= param_normalizado
)

In [ ]:
# Conjunto de validación
valid_set <- dataset[ foto_mes %in% PARAM$valid ]

pred_valid <- predict(
  modelo_valid,
  data.matrix(valid_set[, campos_buenos, with = FALSE])
)

In [ ]:
# 4) Tabla valid con probas y ganancia por fila
tb_valid <- valid_set[, .(numero_de_cliente, clase_ternaria)]
tb_valid[, prob := pred_valid]
setorder(tb_valid, -prob)

In [ ]:
# Ganancia por “invitar” fila a fila (ordenada por prob desc)
tb_valid[, gain_row := fifelse(clase_ternaria=="BAJA+2", 780000, -20000)]
tb_valid[, gain_cum := cumsum(gain_row)]

In [ ]:
# 5) Imprimir TODOS los cortes K y elegir el mejor
K_grid <- PARAM$cortes                     # ej. seq(6000, 19000, by=250)
k_eff  <- pmin(K_grid, nrow(tb_valid))
res_k  <- data.table(K = K_grid, Ganancia = tb_valid$gain_cum[k_eff])

print(res_k)                               # <<--- todos los K con su ganancia

        K  Ganancia
    <num>     <num>
 1:  6000 344000000
 2:  6250 346200000
 3:  6500 348400000
 4:  6750 356200000
 5:  7000 356800000
 6:  7250 358200000
 7:  7500 360400000
 8:  7750 363400000
 9:  8000 363200000
10:  8250 364600000
11:  8500 362800000
12:  8750 364200000
13:  9000 368000000
14:  9250 369400000
15:  9500 370000000
16:  9750 365800000
17: 10000 367200000
18: 10250 367000000
19: 10500 370000000
20: 10750 372200000
21: 11000 372000000
22: 11250 375800000
23: 11500 374800000
24: 11750 373000000
25: 12000 370400000
26: 12250 367800000
27: 12500 366000000
28: 12750 365800000
29: 13000 364000000
30: 13250 362200000
31: 13500 361200000
32: 13750 359400000
33: 14000 354400000
34: 14250 353400000
35: 14500 351600000
36: 14750 349000000
37: 15000 349600000
38: 15250 347000000
39: 15500 344400000
40: 15750 341000000
41: 16000 338400000
42: 16250 336600000
43: 16500 334800000
44: 16750 330600000
45: 17000 331200000
46: 17250 329400000
47: 17500 326000000
48: 17750 325000000
49: 18000 323200000
50: 18250 318200000
51: 18500 314800000
52: 18750 314600000
53: 19000 313600000
        K  Ganancia

In [ ]:
best_idx  <- which.max(res_k$Ganancia)
K_offline <- res_k$K[best_idx]
G_offline <- res_k$Ganancia[best_idx]
cat(">> K_offline (valid) =", K_offline, "| ganancia =", G_offline, "\n")
# (opcional) guardar tabla K vs ganancia
fwrite(res_k, file = "ganancia_por_K_valid.csv")

>> K_offline (valid) = 11250 | ganancia = 375800000

In [ ]:
# 6) Importancia y guardado del modelo de valid (por prolijidad)
tb_importancia <- as.data.table(lgb.importance(modelo_valid))
fwrite(tb_importancia, file = "impo_valid.txt", sep = "\t")
lgb.save(modelo_valid, "modelo_valid.txt")

In [ ]:
write_yaml( PARAM, file="PARAM_valid.yml")

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Oct 12 04:22:47 2025"

# FINAL

Final Training Dataset

In [ ]:
# lectura del dataset
dataset <- fread("/content/datasets/competencia_01.csv.gz", stringsAsFactors= TRUE)

In [ ]:
# paso la clase a binaria que tome valores {0,1}  enteros
#  BAJA+1 y BAJA+2  son  1,   CONTINUA es 0
#  a partir de ahora ya NO puedo cortar  por prob(BAJA+2) > 1/40

dataset[,clase01 := ifelse(clase_ternaria %in% c("BAJA+2","BAJA+1"), 1L, 0L) ]
#dataset_train[,clase01 := ifelse(clase_ternaria %in% c("BAJA+2"), 1L, 0L)]

In [ ]:
dataset_train_final <- dataset[foto_mes %in% PARAM$train_final]
dataset_train_final[,.N,clase_ternaria]

  clase_ternaria N
1 CONTINUA       642824
2 BAJA+2           3938
3 BAJA+1           3447

In [ ]:
# dejo los datos en el formato que necesita LightGBM

dtrain_final <- lgb.Dataset(
  data= data.matrix(dataset_train_final[, campos_buenos, with= FALSE]),
  label= dataset_train_final[, clase01]
)

In [ ]:
param_final <- modifyList(PARAM$lgbm$param_fijos, PARAM$out$lgbm$mejores_hiperparametros)

param_final

$boosting
[1] "gbdt"

$objective
[1] "binary"

$metric
[1] "auc"

$first_metric_only
[1] FALSE

$boost_from_average
[1] TRUE

$feature_pre_filter
[1] FALSE

$force_row_wise
[1] TRUE

$verbosity
[1] -100

$seed
[1] 102191

$max_depth
[1] -1

$min_gain_to_split
[1] 0

$min_sum_hessian_in_leaf
[1] 0.001

$lambda_l1
[1] 6.771127

$lambda_l2
[1] 5.828662

$max_bin
[1] 31

$bagging_fraction
[1] 1

$pos_bagging_fraction
[1] 1

$neg_bagging_fraction
[1] 1

$is_unbalance
[1] FALSE

$scale_pos_weight
[1] 1

$drop_rate
[1] 0.1

$max_drop
[1] 50

$skip_drop
[1] 0.5

$extra_trees
[1] FALSE

$num_iterations
[1] 994

$learning_rate
[1] 0.04483601

$feature_fraction
[1] 0.1651085

$num_leaves
[1] 2047

$min_data_in_leaf
[1] 832

In [ ]:
# este punto es muy SUTIL  y será revisado en la Clase 05

param_normalizado <- copy(param_final)
param_normalizado$min_data_in_leaf <-  round(param_final$min_data_in_leaf / PARAM$trainingstrategy$undersampling)
param_normalizado$bagging_fraction <- 0.9
param_normalizado$bagging_freq     <- 1L

In [ ]:
# aplico el modelo a los datos sin clase
dfuture <- dataset[foto_mes %in% PARAM$future]

In [ ]:
# --- ensemble multi-seed ---
SEEDS <- c(102191, 230101, 999199, 878787, 761177, 161803, 550051, 420420, 314159, 271828)

preds_list <- vector("list", length(SEEDS))
impo_list  <- vector("list", length(SEEDS))

for (i in seq_along(SEEDS)) {
  si <- SEEDS[i]
  p  <- modifyList(param_normalizado, list(seed = si, bagging_seed = si, feature_fraction_seed = si))
  modelo_i <- lgb.train(data = dtrain_final, param = p)

  # guardo importancia por seed (luego promedio)
  impo_list[[i]] <- as.data.table(lgb.importance(modelo_i))[ , seed := si ]

  # guardo el modelo de cada seed
  lgb.save(modelo_i, sprintf("modelo_seed_%d.txt", si))

  # predicción de esta seed
  preds_list[[i]] <- predict(modelo_i, data.matrix(dfuture[, campos_buenos, with = FALSE]))
  rm(modelo_i); gc()
}

In [ ]:
# promedio
pred_mat <- do.call(cbind, preds_list)

# tabla de predicción final (promedio de semillas)
tb_prediccion <- dfuture[, .(numero_de_cliente, foto_mes)]
tb_prediccion[, prob := rowMeans(pred_mat)]   # o: apply(pred_mat, 1, median)

In [ ]:
# Importancia PROMEDIO del ensemble
tb_importancia <- rbindlist(impo_list, fill = TRUE)[
  , .(
      gain_mean   = mean(Gain, na.rm = TRUE),
      gain_median = median(Gain, na.rm = TRUE),
      freq_mean   = mean(Frequency, na.rm = TRUE)
    ),
  by = Feature
][order(-gain_mean)]

fwrite(tb_importancia, file = "impo_ensemble.txt", sep = "\t")
fwrite(tb_prediccion,  file = "prediccion.txt",     sep = "\t")

Aplico el modelo final a los datos del futuro

In [ ]:
# inicilizo el dataset  drealidad
drealidad <- realidad_inicializar( dfuture, PARAM)

Kaggle Competition Submit

In [ ]:
PARAM$cortes

 [1]  6000  6250  6500  6750  7000  7250  7500  7750  8000  8250  8500  8750
[13]  9000  9250  9500  9750 10000 10250 10500 10750 11000 11250 11500 11750
[25] 12000 12250 12500 12750 13000 13250 13500 13750 14000 14250 14500 14750
[37] 15000 15250 15500 15750 16000 16250 16500 16750 17000 17250 17500 17750
[49] 18000 18250 18500 18750 19000

In [ ]:
# genero archivos con los  "envios" mejores
# suba TODOS los archivos a Kaggle

# ordeno por probabilidad descendente
setorder(tb_prediccion, -prob)

dir.create("kaggle")

for (envios in PARAM$cortes) {

  tb_prediccion[, Predicted := 0L] # seteo inicial a 0
  tb_prediccion[1:envios, Predicted := 1L] # marco los primeros

  archivo_kaggle <- paste0("./kaggle/KA", PARAM$experimento, "_", envios, ".csv")

  # grabo el archivo
  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)],
    file= archivo_kaggle,
    sep= ","
  )

  res <- realidad_evaluar( drealidad, tb_prediccion)

  options(scipen = 999)
  cat( "Envios=", envios, "\t",
    " TOTAL=", res$total,
    "  Public=", res$public,
    " Private=", res$private,
    "\n",
    sep= ""
  )

}

Envios=6000	 TOTAL=-120000000  Public=-122066667 Private=-119114286
Envios=6250	 TOTAL=-125000000  Public=-127333333 Private=-124000000
Envios=6500	 TOTAL=-130000000  Public=-131400000 Private=-129400000
Envios=6750	 TOTAL=-135000000  Public=-136066667 Private=-134542857
Envios=7000	 TOTAL=-140000000  Public=-141200000 Private=-139485714
Envios=7250	 TOTAL=-145000000  Public=-145866667 Private=-144628571
Envios=7500	 TOTAL=-150000000  Public=-151933333 Private=-149171429
Envios=7750	 TOTAL=-155000000  Public=-156933333 Private=-154171429
Envios=8000	 TOTAL=-160000000  Public=-162666667 Private=-158857143
Envios=8250	 TOTAL=-165000000  Public=-167066667 Private=-164114286
Envios=8500	 TOTAL=-170000000  Public=-171933333 Private=-169171429
Envios=8750	 TOTAL=-175000000  Public=-176666667 Private=-174285714
Envios=9000	 TOTAL=-180000000  Public=-181400000 Private=-179400000
Envios=9250	 TOTAL=-185000000  Public=-186200000 Private=-184485714
Envios=9500	 TOTAL=-190000000  Public=-191466667 Private=-189371429
Envios=9750	 TOTAL=-195000000  Public=-196933333 Private=-194171429
Envios=10000	 TOTAL=-200000000  Public=-202266667 Private=-199028571
Envios=10250	 TOTAL=-205000000  Public=-207266667 Private=-204028571
Envios=10500	 TOTAL=-210000000  Public=-212866667 Private=-208771429
Envios=10750	 TOTAL=-215000000  Public=-218466667 Private=-213514286
Envios=11000	 TOTAL=-220000000  Public=-223800000 Private=-218371429
Envios=11250	 TOTAL=-225000000  Public=-228266667 Private=-223600000
Envios=11500	 TOTAL=-230000000  Public=-232800000 Private=-228800000
Envios=11750	 TOTAL=-235000000  Public=-237600000 Private=-233885714
Envios=12000	 TOTAL=-240000000  Public=-242200000 Private=-239057143
Envios=12250	 TOTAL=-245000000  Public=-247333333 Private=-244000000
Envios=12500	 TOTAL=-250000000  Public=-252800000 Private=-248800000
Envios=12750	 TOTAL=-255000000  Public=-257800000 Private=-253800000
Envios=13000	 TOTAL=-260000000  Public=-262533333 Private=-258914286
Envios=13250	 TOTAL=-265000000  Public=-266866667 Private=-264200000
Envios=13500	 TOTAL=-270000000  Public=-272466667 Private=-268942857
Envios=13750	 TOTAL=-275000000  Public=-277800000 Private=-273800000
Envios=14000	 TOTAL=-280000000  Public=-282800000 Private=-278800000
Envios=14250	 TOTAL=-285000000  Public=-287000000 Private=-284142857
Envios=14500	 TOTAL=-290000000  Public=-291866667 Private=-289200000
Envios=14750	 TOTAL=-295000000  Public=-297400000 Private=-293971429
Envios=15000	 TOTAL=-300000000  Public=-302400000 Private=-298971429
Envios=15250	 TOTAL=-305000000  Public=-307600000 Private=-303885714
Envios=15500	 TOTAL=-310000000  Public=-313533333 Private=-308485714
Envios=15750	 TOTAL=-315000000  Public=-319933333 Private=-312885714
Envios=16000	 TOTAL=-320000000  Public=-325800000 Private=-317514286
Envios=16250	 TOTAL=-325000000  Public=-331000000 Private=-322428571
Envios=16500	 TOTAL=-330000000  Public=-335600000 Private=-327600000
Envios=16750	 TOTAL=-335000000  Public=-340800000 Private=-332514286
Envios=17000	 TOTAL=-340000000  Public=-345466667 Private=-337657143
Envios=17250	 TOTAL=-345000000  Public=-350200000 Private=-342771429
Envios=17500	 TOTAL=-350000000  Public=-355000000 Private=-347857143
Envios=17750	 TOTAL=-355000000  Public=-360333333 Private=-352714286
Envios=18000	 TOTAL=-360000000  Public=-365266667 Private=-357742857
Envios=18250	 TOTAL=-365000000  Public=-369933333 Private=-362885714
Envios=18500	 TOTAL=-370000000  Public=-374600000 Private=-368028571
Envios=18750	 TOTAL=-375000000  Public=-380466667 Private=-372657143
Envios=19000	 TOTAL=-380000000  Public=-385133333 Private=-377800000

In [ ]:
write_yaml( PARAM, file="PARAM.yml")

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Oct 12 05:18:20 2025"