# Wokflow  **TEST** con Full Bayesiana

##  Big Picture

Este workflow es de testeo, hace la predicción final en 202106 el último mes para el cual podemos construir la clase_ternaria completa y por lo tanto medir la ganancia.

Se muestra el workflow con la Bayesian Optimization diseñada para que LightGBM maximice la ganancia en pesos argentinos
<br> En la Primera Competencia se maximizo la metrica global ROC AUC,  ahora pasamos a la metrica real que llamamos ganancia y que solo se concentra en los  11000 registros con mayor probabilidad de  {"BAJA+1","BAJA+2"}

Intencionalmente este notebook es un *semi-esqueleto*  al que usted deberá completar reutilizando código que ya generó para la Primera Competencia y nuevo código que resuelva las problemáticas presentes en esta competencia.

## Inicializacion

In [1]:
# limpio la memoria
Sys.time()
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

[1] "2025-11-08 05:00:35 UTC"

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  658079 35.2 1454702    77.7 1185646  63.4
Vcells 1221715  9.4 8388608    64.0 1975153  15.1

In [2]:
PARAM <- list()
PARAM$experimento <- "apo-001"
PARAM$semilla_primigenia <- 102191

In [3]:
setwd("/content/buckets/b1/exp")
experimento_folder <- PARAM$experimento
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

## Preprocesamiento

### Generacion de la clase_ternaria

In [4]:
Sys.time()
require( "data.table" )

# leo el dataset
dataset <- fread("~/buckets/b1/datasets/competencia_02_crudo.csv.gz" )

# calculo el periodo0 consecutivo
dsimple <- dataset[, list(
  "pos" = .I,
  numero_de_cliente,
  periodo0 = as.integer(foto_mes/100)*12 +  foto_mes%%100 )
]


# ordeno
setorder( dsimple, numero_de_cliente, periodo0 )

# calculo topes
periodo_ultimo <- dsimple[, max(periodo0) ]
periodo_anteultimo <- periodo_ultimo - 1


# calculo los leads de orden 1 y 2
dsimple[, c("periodo1", "periodo2") :=
  shift(periodo0, n=1:2, fill=NA, type="lead"),  numero_de_cliente
]

# assign most common class values = "CONTINUA"
dsimple[ periodo0 < periodo_anteultimo, clase_ternaria := "CONTINUA" ]

# calculo BAJA+1
dsimple[ periodo0 < periodo_ultimo &
  ( is.na(periodo1) | periodo0 + 1 < periodo1 ),
  clase_ternaria := "BAJA+1"
]

# calculo BAJA+2
dsimple[ periodo0 < periodo_anteultimo & (periodo0+1 == periodo1 )
  & ( is.na(periodo2) | periodo0 + 2 < periodo2 ),
  clase_ternaria := "BAJA+2"
]

# pego el resultado en el dataset original y grabo
setorder( dsimple, pos )
dataset[, clase_ternaria := dsimple$clase_ternaria ]

rm(dsimple)
gc()
Sys.time()

[1] "2025-11-08 05:00:36 UTC"

Loading required package: data.table

       used      (Mb)   gc trigger (Mb)   max used  (Mb)
Ncells    766923   41.0    1454702   77.7   1454702   77.7
Vcells 722144537 5509.6 1017394817 7762.2 845998909 6454.5

[1] "2025-11-08 05:00:58 UTC"

In [5]:
setorder( dataset, foto_mes, clase_ternaria, numero_de_cliente)
dataset[, .N, list(foto_mes, clase_ternaria)]

   foto_mes clase_ternaria N
1  201901   BAJA+1            645
2  201901   BAJA+2            729
3  201901   CONTINUA       122899
4  201902   BAJA+1            733
5  201902   BAJA+2            707
6  201902   CONTINUA       123961
7  201903   BAJA+1            708
8  201903   BAJA+2            751
9  201903   CONTINUA       124508
10 201904   BAJA+1            756
11 201904   BAJA+2            514
12 201904   CONTINUA       125268
13 201905   BAJA+1            517
14 201905   BAJA+2            692
15 201905   CONTINUA       125993
16 201906   BAJA+1            696
17 201906   BAJA+2            608
18 201906   CONTINUA       127430
19 201907   BAJA+1            611
20 201907   BAJA+2            680
21 201907   CONTINUA       128977
22 201908   BAJA+1            683
23 201908   BAJA+2            577
24 201908   CONTINUA       130883
25 201909   BAJA+1            581
26 201909   BAJA+2            582
27 201909   CONTINUA       132594
28 201910   BAJA+1            594
29 201910   BAJA+2            618
30 201910   CONTINUA       134798
⋮  ⋮        ⋮              ⋮
64 202010   BAJA+1            544
65 202010   BAJA+2            454
66 202010   CONTINUA       158171
67 202011   BAJA+1            456
68 202011   BAJA+2            616
69 202011   CONTINUA       159178
70 202012   BAJA+1            622
71 202012   BAJA+2            619
72 202012   CONTINUA       159756
73 202101   BAJA+1            622
74 202101   BAJA+2            825
75 202101   CONTINUA       160080
76 202102   BAJA+1            831
77 202102   BAJA+2           1032
78 202102   CONTINUA       160292
79 202103   BAJA+1           1039
80 202103   BAJA+2            951
81 202103   CONTINUA       161119
82 202104   BAJA+1            955
83 202104   BAJA+2           1130
84 202104   CONTINUA       161333
85 202105   BAJA+1           1134
86 202105   BAJA+2            842
87 202105   CONTINUA       161941
88 202106   BAJA+1            843
89 202106   BAJA+2           1134
90 202106   CONTINUA       162336
91 202107   NA             163459
92 202107   BAJA+1           1137
93 202108   NA             164822

### Eliminacion de Features

Completar a gusto LUEGO de realizar un analisis exploratorio de datos.
<br> No necesariamente en esta Segunda Competencia conviele eliminar los mismos campos que en la Primera ...

In [6]:
# Salsa Magica para 202106
dataset[, mprestamos_personales := NULL ]
dataset[, cprestamos_personales := NULL ]

### Data Quality

Se deben reparar los atributos del dataset que para un cierto mes TODOS sus valores son cero.
<br> Relevar en forma muy minuciosa en el dataset cuales son los  <atributo,mes> que estan dañados.
<br> Algunas alternativas de solución son:
* No hacer absolutamente nada, dejar el valor 0 tal cual está, a sabiendas que es incorrecto
* Reemplazar esos valores dañados por  NA
* Interpolar cada valor dañado por el valor del mes previo y el posterior
* Calcularlo a partir de un modelo, libreria  MICE

a este codigo de Data Quality  lo debera escribir usted

### Data Drifting

Se debe corregir el drifting natural que ocurre en loa datos, en particular los datos monetarios que se vieron fuertemente afectados por una alta inflación
<br> Posibles métodos son:
* No hacer absolutamente nada
* Ajuste de valores monetarios por indices del tipo :
   * IPC  Indice de Precios al Consumidor
   * Dolar Oficial
   * Dolar Blue
   * UVA  Unidad de Valor Adquisitivo

a este codigo de Data Drifting lo debera escribir usted

IPC

In [7]:
library(data.table)

# ================= IPC desde variaciones mensuales =================
# Variaciones mensuales (%) en orden 201901, 201902, ..., 202108  (32 valores)
ipc_var <- c(
  2.9, 3.8, 4.7, 3.4, 3.1, 2.7, 2.2, 4.0, 5.9, 3.3, 4.3, 3.7,
  2.3, 2.0, 3.3, 1.5, 1.5, 2.2, 1.9, 2.7, 2.8, 3.8, 3.2, 4.0,
  4.0, 3.6, 4.8, 4.1, 3.3, 3.2, 3.0, 2.5
)

# Genero la secuencia de foto_mes 201901..202108
seq_fm <- function(from_fm, to_fm){
  dseq <- seq(as.Date(paste0(from_fm,"01"), "%Y%m%d"),
              as.Date(paste0(to_fm,"01"), "%Y%m%d"), by="month")
  as.integer(format(dseq, "%Y%m"))
}
fm_seq <- seq_fm(201901L, 202108L)

stopifnot(length(ipc_var) == length(fm_seq))

ipc <- data.table(
  foto_mes = fm_seq,
  variacion_mensual = ipc_var
)

# Índice acumulado (base libre). Pongo 100 en el primer mes y acumulo.
ipc[, indice := 100 * cumprod(1 + variacion_mensual/100)]

# ================= Deflactar a una base elegida =================
base_mes <- 202108L            # sugerido: el último mes disponible
stopifnot(base_mes %in% ipc$foto_mes)

# Traigo el índice al dataset y calculo factor relativo a la base
setkey(ipc, foto_mes)
stopifnot("foto_mes" %in% names(dataset))
dataset <- ipc[dataset, on="foto_mes"]

indice_base <- ipc[foto_mes == base_mes, indice][1]
dataset[, defl_factor := indice / indice_base]  # >1 = precios más altos que la base

# Detecto columnas de montos (m* y Master_m*/Visa_m*)
montos_m_prefix <- grep("^m", names(dataset), value = TRUE)
montos_card     <- grep("^(Master|Visa)_m", names(dataset), value = TRUE)
montos_all <- unique(c(montos_m_prefix, montos_card))
montos_all <- montos_all[vapply(dataset[, ..montos_all], is.numeric, logical(1))]

# Deflactar IN-PLACE a pesos de 'base_mes'
for (cn in montos_all) {
  dataset[, (cn) := get(cn) / pmax(defl_factor, 1e-12)]
}

# (opcional) trazabilidad y limpieza
dataset[, ipc_base := base_mes]
dataset[, c("variacion_mensual","indice","defl_factor") := NULL]

cat(sprintf("IPC aplicado (base %d). Columnas deflactadas: %d\n", base_mes, length(montos_all)))

IPC aplicado (base 202108). Columnas deflactadas: 72

### Feature Engineering Intra-Mes

Crear variables nuevas a partir de las existentes dentro del mismo registro, **sin** ir a buscar información histórica.
<br> El siguiente código es un mínimo ejemplo, agregar nuevos features a gusto

In [8]:
# el mes 1,2, ..12 , podria servir para detectar estacionalidad
dataset[, kmes := foto_mes %% 100]

# creo un ctr_quarter que tenga en cuenta cuando
# los clientes hace 3 menos meses que estan
# ya que seria injusto considerar las transacciones medidas en menor tiempo
dataset[, ctrx_quarter_normalizado := as.numeric(ctrx_quarter) ]
dataset[cliente_antiguedad == 1, ctrx_quarter_normalizado := ctrx_quarter * 5.0]
dataset[cliente_antiguedad == 2, ctrx_quarter_normalizado := ctrx_quarter * 2.0]
dataset[cliente_antiguedad == 3, ctrx_quarter_normalizado := ctrx_quarter * 1.2]

# variable extraida de una tesis de maestria de Irlanda, se perdió el link
dataset[, mpayroll_sobre_edad := mpayroll / cliente_edad]

Sys.time()

[1] "2025-11-08 05:01:06 UTC"

### Feature Engineering Historico

In [9]:
if( !require("Rcpp")) install.packages("Rcpp", repos = "http://cran.us.r-project.org")
require("Rcpp")

Loading required package: Rcpp

In [10]:
# se calculan para los 6 meses previos el minimo, maximo y
#  tendencia calculada con cuadrados minimos
# la formula de calculo de la tendencia puede verse en
#  https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Introductory_Statistics_(Shafer_and_Zhang)/10%3A_Correlation_and_Regression/10.04%3A_The_Least_Squares_Regression_Line
# para la maxíma velocidad esta funcion esta escrita en lenguaje C,
# y no en la porqueria de R o Python

cppFunction("NumericVector fhistC(NumericVector pcolumna, IntegerVector pdesde )
{
  /* Aqui se cargan los valores para la regresion */
  double  x[100] ;
  double  y[100] ;

  int n = pcolumna.size();
  NumericVector out( 5*n );

  for(int i = 0; i < n; i++)
  {
    //lag
    if( pdesde[i]-1 < i )  out[ i + 4*n ]  =  pcolumna[i-1] ;
    else                   out[ i + 4*n ]  =  NA_REAL ;


    int  libre    = 0 ;
    int  xvalor   = 1 ;

    for( int j= pdesde[i]-1;  j<=i; j++ )
    {
       double a = pcolumna[j] ;

       if( !R_IsNA( a ) )
       {
          y[ libre ]= a ;
          x[ libre ]= xvalor ;
          libre++ ;
       }

       xvalor++ ;
    }

    /* Si hay al menos dos valores */
    if( libre > 1 )
    {
      double  xsum  = x[0] ;
      double  ysum  = y[0] ;
      double  xysum = xsum * ysum ;
      double  xxsum = xsum * xsum ;
      double  vmin  = y[0] ;
      double  vmax  = y[0] ;

      for( int h=1; h<libre; h++)
      {
        xsum  += x[h] ;
        ysum  += y[h] ;
        xysum += x[h]*y[h] ;
        xxsum += x[h]*x[h] ;

        if( y[h] < vmin )  vmin = y[h] ;
        if( y[h] > vmax )  vmax = y[h] ;
      }

      out[ i ]  =  (libre*xysum - xsum*ysum)/(libre*xxsum -xsum*xsum) ;
      out[ i + n ]    =  vmin ;
      out[ i + 2*n ]  =  vmax ;
      out[ i + 3*n ]  =  ysum / libre ;
    }
    else
    {
      out[ i       ]  =  NA_REAL ;
      out[ i + n   ]  =  NA_REAL ;
      out[ i + 2*n ]  =  NA_REAL ;
      out[ i + 3*n ]  =  NA_REAL ;
    }
  }

  return  out;
}")

In [11]:
# calcula la tendencia de las variables cols de los ultimos 6 meses
# la tendencia es la pendiente de la recta que ajusta por cuadrados minimos
# La funcionalidad de ratioavg es autoria de  Daiana Sparta,  UAustral  2021

TendenciaYmuchomas <- function(
    dataset, cols, ventana = 6, tendencia = TRUE,
    minimo = TRUE, maximo = TRUE, promedio = TRUE,
    ratioavg = FALSE, ratiomax = FALSE) {
  gc(verbose= FALSE)
  # Esta es la cantidad de meses que utilizo para la historia
  ventana_regresion <- ventana

  last <- nrow(dataset)

  # creo el vector_desde que indica cada ventana
  # de esta forma se acelera el procesamiento ya que lo hago una sola vez
  vector_ids <- dataset[ , numero_de_cliente ]

  vector_desde <- seq(
    -ventana_regresion + 2,
    nrow(dataset) - ventana_regresion + 1
  )

  vector_desde[1:ventana_regresion] <- 1

  for (i in 2:last) {
    if (vector_ids[i - 1] != vector_ids[i]) {
      vector_desde[i] <- i
    }
  }
  for (i in 2:last) {
    if (vector_desde[i] < vector_desde[i - 1]) {
      vector_desde[i] <- vector_desde[i - 1]
    }
  }

  for (campo in cols) {
    nueva_col <- fhistC(dataset[, get(campo)], vector_desde)

    if (tendencia) {
      dataset[, paste0(campo, "_tend", ventana) :=
        nueva_col[(0 * last + 1):(1 * last)]]
    }

    if (minimo) {
      dataset[, paste0(campo, "_min", ventana) :=
        nueva_col[(1 * last + 1):(2 * last)]]
    }

    if (maximo) {
      dataset[, paste0(campo, "_max", ventana) :=
        nueva_col[(2 * last + 1):(3 * last)]]
    }

    if (promedio) {
      dataset[, paste0(campo, "_avg", ventana) :=
        nueva_col[(3 * last + 1):(4 * last)]]
    }

    if (ratioavg) {
      dataset[, paste0(campo, "_ratioavg", ventana) :=
        get(campo) / nueva_col[(3 * last + 1):(4 * last)]]
    }

    if (ratiomax) {
      dataset[, paste0(campo, "_ratiomax", ventana) :=
        get(campo) / nueva_col[(2 * last + 1):(3 * last)]]
    }
  }
}

In [12]:
# Feature Engineering Historico
# Creacion de LAGs
setorder(dataset, numero_de_cliente, foto_mes)

# todo es lagueable, menos la primary key y la clase
cols_lagueables <- copy( setdiff(
  colnames(dataset),
  c("numero_de_cliente", "foto_mes", "clase_ternaria")
))

# https://rdrr.io/cran/data.table/man/shift.html

# lags de orden 1
dataset[,
  paste0(cols_lagueables, "_lag1") := shift(.SD, 1, NA, "lag"),
  by= numero_de_cliente,
  .SDcols= cols_lagueables
]

# lags de orden 2
dataset[,
  paste0(cols_lagueables, "_lag2") := shift(.SD, 2, NA, "lag"),
  by= numero_de_cliente,
  .SDcols= cols_lagueables
]

# agrego los delta lags
for (vcol in cols_lagueables)
{
  dataset[, paste0(vcol, "_delta1") := get(vcol) - get(paste0(vcol, "_lag1"))]
  dataset[, paste0(vcol, "_delta2") := get(vcol) - get(paste0(vcol, "_lag2"))]
}

Sys.time()

[1] "2025-11-08 05:02:21 UTC"

In [13]:
# parametros de Feature Engineering Historico de Tendencias
PARAM$FE_hist$Tendencias$run <- TRUE
PARAM$FE_hist$Tendencias$ventana <- 6
PARAM$FE_hist$Tendencias$tendencia <- TRUE
PARAM$FE_hist$Tendencias$minimo <- FALSE
PARAM$FE_hist$Tendencias$maximo <- FALSE
PARAM$FE_hist$Tendencias$promedio <- FALSE
PARAM$FE_hist$Tendencias$ratioavg <- FALSE
PARAM$FE_hist$Tendencias$ratiomax <- FALSE

In [14]:
# aqui se agregan las tendencias de los ultimos 6 meses

cols_lagueables <- intersect(cols_lagueables, colnames(dataset))
setorder(dataset, numero_de_cliente, foto_mes)

if( PARAM$FE_hist$Tendencias$run) {
    TendenciaYmuchomas(dataset,
    cols = cols_lagueables,
    ventana = PARAM$FE_hist$Tendencias$ventana, # 6 meses de historia
    tendencia = PARAM$FE_hist$Tendencias$tendencia,
    minimo = PARAM$FE_hist$Tendencias$minimo,
    maximo = PARAM$FE_hist$Tendencias$maximo,
    promedio = PARAM$FE_hist$Tendencias$promedio,
    ratioavg = PARAM$FE_hist$Tendencias$ratioavg,
    ratiomax = PARAM$FE_hist$Tendencias$ratiomax
  )
}

ncol(dataset)
Sys.time()

[1] 927

[1] "2025-11-08 05:03:14 UTC"

### Feature Engineering a partir de hojas de Random Forest

In [15]:
if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

Loading required package: lightgbm

In [16]:
AgregaVarRandomForest <- function() {

  cat( "inicio AgregaVarRandomForest()\n")
  gc(verbose= FALSE)
  dataset[, clase01 := 0L ]
  dataset[ clase_ternaria %in% c( "BAJA+2", "BAJA+1"),
      clase01 := 1L ]

  campos_buenos <- setdiff(
    colnames(dataset),
    c( "clase_ternaria", "clase01")
  )

  dataset[, entrenamiento :=
    as.integer( foto_mes %in% PARAM$FE_rf$train$training )]

  dtrain <- lgb.Dataset(
    data = data.matrix(dataset[entrenamiento == TRUE, campos_buenos, with = FALSE]),
    label = dataset[entrenamiento == TRUE, clase01],
    free_raw_data = FALSE
  )

  modelo <- lgb.train(
     data = dtrain,
     param = PARAM$FE_rf$lgb_param,
     verbose = -100
  )

  cat( "Fin construccion RandomForest\n" )
  # grabo el modelo, achivo .model
  lgb.save(modelo, file="modelo.model" )

  qarbolitos <- copy(PARAM$FE_rf$lgb_param$num_iterations)

  periodos <- dataset[ , unique( foto_mes ) ]

  for( periodo in  periodos )
  {
    cat( "periodo = ", periodo, "\n" )
    datamatrix <- data.matrix(dataset[ foto_mes== periodo, campos_buenos, with = FALSE])

    cat( "Inicio prediccion\n" )
    prediccion <- predict(
        modelo,
        datamatrix,
        type = "leaf"
    )
    cat( "Fin prediccion\n" )

    for( arbolito in 1:qarbolitos )
    {
       cat( arbolito, " " )
       hojas_arbol <- unique(prediccion[ , arbolito])

       for (pos in 1:length(hojas_arbol)) {
         # el numero de nodo de la hoja, estan salteados
         nodo_id <- hojas_arbol[pos]
         dataset[ foto_mes== periodo, paste0(
            "rf_", sprintf("%03d", arbolito),
             "_", sprintf("%03d", nodo_id)
          ) :=  as.integer( nodo_id == prediccion[ , arbolito]) ]

       }

       rm( hojas_arbol )
    }
    cat( "\n" )

    rm( prediccion )
    rm( datamatrix )
    gc(verbose= FALSE)
  }

  gc(verbose= FALSE)

  # borro clase01 , no debe ensuciar el dataset
  dataset[ , clase01 := NULL ]

}

In [17]:
# Parametros de Feature Engineering  a partir de hojas de Random Forest

# Estos CUATRO parametros son los que se deben modificar
PARAM$FE_rf$arbolitos= 20
PARAM$FE_rf$hojas_por_arbol= 16
PARAM$FE_rf$datos_por_hoja= 100
PARAM$FE_rf$mtry_ratio= 0.2

# Estos son quasi fijos
PARAM$FE_rf$train$training <- c( 202101, 202102, 202103)

# Estos TAMBIEN son quasi fijos
PARAM$FE_rf$lgb_param <-list(
    # parametros que se pueden cambiar
    num_iterations = PARAM$FE_rf$arbolitos,
    num_leaves  = PARAM$FE_rf$hojas_por_arbol,
    min_data_in_leaf = PARAM$FE_rf$datos_por_hoja,
    feature_fraction_bynode  = PARAM$FE_rf$mtry_ratio,

    # para que LightGBM emule Random Forest
    boosting = "rf",
    bagging_fraction = ( 1.0 - 1.0/exp(1.0) ),
    bagging_freq = 1.0,
    feature_fraction = 1.0,

    # genericos de LightGBM
    max_bin = 31L,
    objective = "binary",
    first_metric_only = TRUE,
    boost_from_average = TRUE,
    feature_pre_filter = FALSE,
    force_row_wise = TRUE,
    verbosity = -100,
    max_depth = -1L,
    min_gain_to_split = 0.0,
    min_sum_hessian_in_leaf = 0.001,
    lambda_l1 = 0.0,
    lambda_l2 = 0.0,

    pos_bagging_fraction = 1.0,
    neg_bagging_fraction = 1.0,
    is_unbalance = FALSE,
    scale_pos_weight = 1.0,

    drop_rate = 0.1,
    max_drop = 50,
    skip_drop = 0.5,

    extra_trees = FALSE
  )

In [18]:
# Feature Engineering agregando variables de Random Forest
#  aqui es donde se hace el trabajo
AgregaVarRandomForest()

Sys.time()

inicio AgregaVarRandomForest()
Fin construccion RandomForest
periodo =  201901
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201902
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201903
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201904
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201905
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201906
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201907
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201908
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201909
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201910
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201911
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201912
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202001
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202002
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202003
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202004
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202005
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202006
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202007
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202008
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202009
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202010
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202011
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202012
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202101
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202102
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202103
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202104
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202105
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202106
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202107
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202108
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20

[1] "2025-11-08 05:05:58 UTC"

In [19]:
ncol(dataset)
colnames(dataset)

[1] 1248

   [1] "foto_mes"
   [2] "numero_de_cliente"
   [3] "active_quarter"
   [4] "cliente_vip"
   [5] "internet"
   [6] "cliente_edad"
   [7] "cliente_antiguedad"
   [8] "mrentabilidad"
   [9] "mrentabilidad_annual"
  [10] "mcomisiones"
  [11] "mactivos_margen"
  [12] "mpasivos_margen"
  [13] "cproductos"
  [14] "tcuentas"
  [15] "ccuenta_corriente"
  [16] "mcuenta_corriente_adicional"
  [17] "mcuenta_corriente"
  [18] "ccaja_ahorro"
  [19] "mcaja_ahorro"
  [20] "mcaja_ahorro_adicional"
  [21] "mcaja_ahorro_dolares"
  [22] "cdescubierto_preacordado"
  [23] "mcuentas_saldo"
  [24] "ctarjeta_debito"
  [25] "ctarjeta_debito_transacciones"
  [26] "mautoservicio"
  [27] "ctarjeta_visa"
  [28] "ctarjeta_visa_transacciones"
  [29] "mtarjeta_visa_consumo"
  [30] "ctarjeta_master"
  [31] "ctarjeta_master_transacciones"
  [32] "mtarjeta_master_consumo"
  [33] "cprestamos_prendarios"
  [34] "mprestamos_prendarios"
  [35] "cprestamos_hipotecarios"
  [36] "mprestamos_hipotecarios"
  [37] "cplazo_fijo"
  [38] "mplazo_fijo_dolares"
  [39] "mplazo_fijo_pesos"
  [40] "cinversion1"
  [41] "minversion1_pesos"
  [42] "minversion1_dolares"
  [43] "cinversion2"
  [44] "minversion2"
  [45] "cseguro_vida"
  [46] "cseguro_auto"
  [47] "cseguro_vivienda"
  [48] "cseguro_accidentes_personales"
  [49] "ccaja_seguridad"
  [50] "cpayroll_trx"
  [51] "mpayroll"
  [52] "mpayroll2"
  [53] "cpayroll2_trx"
  [54] "ccuenta_debitos_automaticos"
  [55] "mcuenta_debitos_automaticos"
  [56] "ctarjeta_visa_debitos_automaticos"
  [57] "mttarjeta_visa_debitos_automaticos"
  [58] "ctarjeta_master_debitos_automaticos"
  [59] "mttarjeta_master_debitos_automaticos"
  [60] "cpagodeservicios"
  [61] "mpagodeservicios"
  [62] "cpagomiscuentas"
  [63] "mpagomiscuentas"
  [64] "ccajeros_propios_descuentos"
  [65] "mcajeros_propios_descuentos"
  [66] "ctarjeta_visa_descuentos"
  [67] "mtarjeta_visa_descuentos"
  [68] "ctarjeta_master_descuentos"
  [69] "mtarjeta_master_descuentos"
  [70] "ccomisiones_mantenimiento"
  [71] "mcomisiones_mantenimiento"
  [72] "ccomisiones_otras"
  [73] "mcomisiones_otras"
  [74] "cforex"
  [75] "cforex_buy"
  [76] "mforex_buy"
  [77] "cforex_sell"
  [78] "mforex_sell"
  [79] "ctransferencias_recibidas"
  [80] "mtransferencias_recibidas"
  [81] "ctransferencias_emitidas"
  [82] "mtransferencias_emitidas"
  [83] "cextraccion_autoservicio"
  [84] "mextraccion_autoservicio"
  [85] "ccheques_depositados"
  [86] "mcheques_depositados"
  [87] "ccheques_emitidos"
  [88] "mcheques_emitidos"
  [89] "ccheques_depositados_rechazados"
  [90] "mcheques_depositados_rechazados"
  [91] "ccheques_emitidos_rechazados"
  [92] "mcheques_emitidos_rechazados"
  [93] "tcallcenter"
  [94] "ccallcenter_transacciones"
  [95] "thomebanking"
  [96] "chomebanking_transacciones"
  [97] "ccajas_transacciones"
  [98] "ccajas_consultas"
  [99] "ccajas_depositos"
 [100] "ccajas_extracciones"
 [101] "ccajas_otras"
 [102] "catm_trx"
 [103] "matm"
 [104] "catm_trx_other"
 [105] "matm_other"
 [106] "ctrx_quarter"
 [107] "tmobile_app"
 [108] "cmobile_app_trx"
 [109] "Master_delinquency"
 [110] "Master_status"
 [111] "Master_mfinanciacion_limite"
 [112] "Master_Fvencimiento"
 [113] "Master_Finiciomora"
 [114] "Master_msaldototal"
 [115] "Master_msaldopesos"
 [116] "Master_msaldodolares"
 [117] "Master_mconsumospesos"
 [118] "Master_mconsumosdolares"
 [119] "Master_mlimitecompra"
 [120] "Master_madelantopesos"
 [121] "Master_madelantodolares"
 [122] "Master_fultimo_cierre"
 [123] "Master_mpagado"
 [124] "Master_mpagospesos"
 [125] "Master_mpagosdolares"
 [126] "Master_fechaalta"
 [127] "Master_mconsumototal"
 [128] "Master_cconsumos"
 [129] "Master_cadelantosefectivo"
 [130] "Master_mpagominimo"
 [131] "Visa_delinquency"
 [132] "Visa_status"
 [133] "Visa_mfinanciacion_limite"
 [134] "Visa_Fvencimiento"
 [135] "Visa_Finiciomora"
 [136] "Visa_msaldototal"
 [137] "Visa_msaldopesos"
 [138] "Visa_msaldodolares"
 [139] "Visa_mconsumospesos"
 [140] "Visa_mconsumosdolares"
 [141] "Visa_mlimitecompra"
 [142] "Visa_madelantopesos"
 [143] "Visa_madelantodolares"
 [144] "Visa_fultimo_cierre"
 [145] "Visa_mpagado"
 [146] "Visa_mpagospesos"
 [147] "Visa_mpagosdolares"
 [148] "Visa_fechaalta"
 [149] "Visa_mconsumototal"
 [150] "Visa_cconsumos"
 [151] "Visa_cadelantosefectivo"
 [152] "Visa_mpagominimo"
 [153] "clase_ternaria"
 [154] "ipc_base"
 [155] "kmes"
 [156] "ctrx_quarter_normalizado"
 [157] "mpayroll_sobre_edad"
 [158] "active_quarter_lag1"
 [159] "cliente_vip_lag1"
 [160] "internet_lag1"
 [161] "cliente_edad_lag1"
 [162] "cliente_antiguedad_lag1"
 [163] "mrentabilidad_lag1"
 [164] "mrentabilidad_annual_lag1"
 [165] "mcomisiones_lag1"
 [166] "mactivos_margen_lag1"
 [167] "mpasivos_margen_lag1"
 [168] "cproductos_lag1"
 [169] "tcuentas_lag1"
 [170] "ccuenta_corriente_lag1"
 [171] "mcuenta_corriente_adicional_lag1"
 [172] "mcuenta_corriente_lag1"
 [173] "ccaja_ahorro_lag1"
 [174] "mcaja_ahorro_lag1"
 [175] "mcaja_ahorro_adicional_lag1"
 [176] "mcaja_ahorro_dolares_lag1"
 [177] "cdescubierto_preacordado_lag1"
 [178] "mcuentas_saldo_lag1"
 [179] "ctarjeta_debito_lag1"
 [180] "ctarjeta_debito_transacciones_lag1"
 [181] "mautoservicio_lag1"
 [182] "ctarjeta_visa_lag1"
 [183] "ctarjeta_visa_transacciones_lag1"
 [184] "mtarjeta_visa_consumo_lag1"
 [185] "ctarjeta_master_lag1"
 [186] "ctarjeta_master_transacciones_lag1"
 [187] "mtarjeta_master_consumo_lag1"
 [188] "cprestamos_prendarios_lag1"
 [189] "mprestamos_prendarios_lag1"
 [190] "cprestamos_hipotecarios_lag1"
 [191] "mprestamos_hipotecarios_lag1"
 [192] "cplazo_fijo_lag1"
 [193] "mplazo_fijo_dolares_lag1"
 [194] "mplazo_fijo_pesos_lag1"
 [195] "cinversion1_lag1"
 [196] "minversion1_pesos_lag1"
 [197] "minversion1_dolares_lag1"
 [198] "cinversion2_lag1"
 [199] "minversion2_lag1"
 [200] "cseguro_vida_lag1"
 [201] "cseguro_auto_lag1"
 [202] "cseguro_vivienda_lag1"
 [203] "cseguro_accidentes_personales_lag1"
 [204] "ccaja_seguridad_lag1"
 [205] "cpayroll_trx_lag1"
 [206] "mpayroll_lag1"
 [207] "mpayroll2_lag1"
 [208] "cpayroll2_trx_lag1"
 [209] "ccuenta_debitos_automaticos_lag1"
 [210] "mcuenta_debitos_automaticos_lag1"
 [211] "ctarjeta_visa_debitos_automaticos_lag1"
 [212] "mttarjeta_visa_debitos_automaticos_lag1"
 [213] "ctarjeta_master_debitos_automaticos_lag1"
 [214] "mttarjeta_master_debitos_automaticos_lag1"
 [215] "cpagodeservicios_lag1"
 [216] "mpagodeservicios_lag1"
 [217] "cpagomiscuentas_lag1"
 [218] "mpagomiscuentas_lag1"
 [219] "ccajeros_propios_descuentos_lag1"
 [220] "mcajeros_propios_descuentos_lag1"
 [221] "ctarjeta_visa_descuentos_lag1"
 [222] "mtarjeta_visa_descuentos_lag1"
 [223] "ctarjeta_master_descuentos_lag1"
 [224] "mtarjeta_master_descuentos_lag1"
 [225] "ccomisiones_mantenimiento_lag1"
 [226] "mcomisiones_mantenimiento_lag1"
 [227] "ccomisiones_otras_lag1"
 [228] "mcomisiones_otras_lag1"
 [229] "cforex_lag1"
 [230] "cforex_buy_lag1"
 [231] "mforex_buy_lag1"
 [232] "cforex_sell_lag1"
 [233] "mforex_sell_lag1"
 [234] "ctransferencias_recibidas_lag1"
 [235] "mtransferencias_recibidas_lag1"
 [236] "ctransferencias_emitidas_lag1"
 [237] "mtransferencias_emitidas_lag1"
 [238] "cextraccion_autoservicio_lag1"
 [239] "mextraccion_autoservicio_lag1"
 [240] "ccheques_depositados_lag1"
 [241] "mcheques_depositados_lag1"
 [242] "ccheques_emitidos_lag1"
 [243] "mcheques_emitidos_lag1"
 [244] "ccheques_depositados_rechazados_lag1"
 [245] "mcheques_depositados_rechazados_lag1"
 [246] "ccheques_emitidos_rechazados_lag1"
 [247] "mcheques_emitidos_rechazados_lag1"
 [248] "tcallcenter_lag1"
 [249] "ccallcenter_transacciones_lag1"
 [250] "thomebanking_lag1"
 [251] "chomebanking_transacciones_lag1"
 [252] "ccajas_transacciones_lag1"
 [253] "ccajas_consultas_lag1"
 [254] "ccajas_depositos_lag1"
 [255] "ccajas_extracciones_lag1"
 [256] "ccajas_otras_lag1"
 [257] "catm_trx_lag1"
 [258] "matm_lag1"
 [259] "catm_trx_other_lag1"
 [260] "matm_other_lag1"
 [261] "ctrx_quarter_lag1"
 [262] "tmobile_app_lag1"
 [263] "cmobile_app_trx_lag1"
 [264] "Master_delinquency_lag1"
 [265] "Master_status_lag1"
 [266] "Master_mfinanciacion_limite_lag1"
 [267] "Master_Fvencimiento_lag1"
 [268] "Master_Finiciomora_lag1"
 [269] "Master_msaldototal_lag1"
 [270] "Master_msaldopesos_lag1"
 [271] "Master_msaldodolares_lag1"
 [272] "Master_mconsumospesos_lag1"
 [273] "Master_mconsumosdolares_lag1"
 [274] "Master_mlimitecompra_lag1"
 [275] "Master_madelantopesos_lag1"
 [276] "Master_madelantodolares_lag1"
 [277] "Master_fultimo_cierre_lag1"
 [278] "Master_mpagado_lag1"
 [279] "Master_mpagospesos_lag1"
 [280] "Master_mpagosdolares_lag1"
 [281] "Master_fechaalta_lag1"
 [282] "Master_mconsumototal_lag1"
 [283] "Master_cconsumos_lag1"
 [284] "Master_cadelantosefectivo_lag1"
 [285] "Master_mpagominimo_lag1"
 [286] "Visa_delinquency_lag1"
 [287] "Visa_status_lag1"
 [288] "Visa_mfinanciacion_limite_lag1"
 [289] "Visa_Fvencimiento_lag1"
 [290] "Visa_Finiciomora_lag1"
 [291] "Visa_msaldototal_lag1"
 [292] "Visa_msaldopesos_lag1"
 [293] "Visa_msaldodolares_lag1"
 [294] "Visa_mconsumospesos_lag1"
 [295] "Visa_mconsumosdolares_lag1"
 [296] "Visa_mlimitecompra_lag1"
 [297] "Visa_madelantopesos_lag1"
 [298] "Visa_madelantodolares_lag1"
 [299] "Visa_fultimo_cierre_lag1"
 [300] "Visa_mpagado_lag1"
 [301] "Visa_mpagospesos_lag1"
 [302] "Visa_mpagosdolares_lag1"
 [303] "Visa_fechaalta_lag1"
 [304] "Visa_mconsumototal_lag1"
 [305] "Visa_cconsumos_lag1"
 [306] "Visa_cadelantosefectivo_lag1"
 [307] "Visa_mpagominimo_lag1"
 [308] "ipc_base_lag1"
 [309] "kmes_lag1"
 [310] "ctrx_quarter_normalizado_lag1"
 [311] "mpayroll_sobre_edad_lag1"
 [312] "active_quarter_lag2"
 [313] "cliente_vip_lag2"
 [314] "internet_lag2"
 [315] "cliente_edad_lag2"
 [316] "cliente_antiguedad_lag2"
 [317] "mrentabilidad_lag2"
 [318] "mrentabilidad_annual_lag2"
 [319] "mcomisiones_lag2"
 [320] "mactivos_margen_lag2"
 [321] "mpasivos_margen_lag2"
 [322] "cproductos_lag2"
 [323] "tcuentas_lag2"
 [324] "ccuenta_corriente_lag2"
 [325] "mcuenta_corriente_adicional_lag2"
 [326] "mcuenta_corriente_lag2"
 [327] "ccaja_ahorro_lag2"
 [328] "mcaja_ahorro_lag2"
 [329] "mcaja_ahorro_adicional_lag2"
 [330] "mcaja_ahorro_dolares_lag2"
 [331] "cdescubierto_preacordado_lag2"
 [332] "mcuentas_saldo_lag2"
 [333] "ctarjeta_debito_lag2"
 [334] "ctarjeta_debito_transacciones_lag2"
 [335] "mautoservicio_lag2"
 [336] "ctarjeta_visa_lag2"
 [337] "ctarjeta_visa_transacciones_lag2"
 [338] "mtarjeta_visa_consumo_lag2"
 [339] "ctarjeta_master_lag2"
 [340] "ctarjeta_master_transacciones_lag2"
 [341] "mtarjeta_master_consumo_lag2"
 [342] "cprestamos_prendarios_lag2"
 [343] "mprestamos_prendarios_lag2"
 [344] "cprestamos_hipotecarios_lag2"
 [345] "mprestamos_hipotecarios_lag2"
 [346] "cplazo_fijo_lag2"
 [347] "mplazo_fijo_dolares_lag2"
 [348] "mplazo_fijo_pesos_lag2"
 [349] "cinversion1_lag2"
 [350] "minversion1_pesos_lag2"
 [351] "minversion1_dolares_lag2"
 [352] "cinversion2_lag2"
 [353] "minversion2_lag2"
 [354] "cseguro_vida_lag2"
 [355] "cseguro_auto_lag2"
 [356] "cseguro_vivienda_lag2"
 [357] "cseguro_accidentes_personales_lag2"
 [358] "ccaja_seguridad_lag2"
 [359] "cpayroll_trx_lag2"
 [360] "mpayroll_lag2"
 [361] "mpayroll2_lag2"
 [362] "cpayroll2_trx_lag2"
 [363] "ccuenta_debitos_automaticos_lag2"
 [364] "mcuenta_debitos_automaticos_lag2"
 [365] "ctarjeta_visa_debitos_automaticos_lag2"
 [366] "mttarjeta_visa_debitos_automaticos_lag2"
 [367] "ctarjeta_master_debitos_automaticos_lag2"
 [368] "mttarjeta_master_debitos_automaticos_lag2"
 [369] "cpagodeservicios_lag2"
 [370] "mpagodeservicios_lag2"
 [371] "cpagomiscuentas_lag2"
 [372] "mpagomiscuentas_lag2"
 [373] "ccajeros_propios_descuentos_lag2"
 [374] "mcajeros_propios_descuentos_lag2"
 [375] "ctarjeta_visa_descuentos_lag2"
 [376] "mtarjeta_visa_descuentos_lag2"
 [377] "ctarjeta_master_descuentos_lag2"
 [378] "mtarjeta_master_descuentos_lag2"
 [379] "ccomisiones_mantenimiento_lag2"
 [380] "mcomisiones_mantenimiento_lag2"
 [381] "ccomisiones_otras_lag2"
 [382] "mcomisiones_otras_lag2"
 [383] "cforex_lag2"
 [384] "cforex_buy_lag2"
 [385] "mforex_buy_lag2"
 [386] "cforex_sell_lag2"
 [387] "mforex_sell_lag2"
 [388] "ctransferencias_recibidas_lag2"
 [389] "mtransferencias_recibidas_lag2"
 [390] "ctransferencias_emitidas_lag2"
 [391] "mtransferencias_emitidas_lag2"
 [392] "cextraccion_autoservicio_lag2"
 [393] "mextraccion_autoservicio_lag2"
 [394] "ccheques_depositados_lag2"
 [395] "mcheques_depositados_lag2"
 [396] "ccheques_emitidos_lag2"
 [397] "mcheques_emitidos_lag2"
 [398] "ccheques_depositados_rechazados_lag2"
 [399] "mcheques_depositados_rechazados_lag2"
 [400] "ccheques_emitidos_rechazados_lag2"
 [401] "mcheques_emitidos_rechazados_lag2"
 [402] "tcallcenter_lag2"
 [403] "ccallcenter_transacciones_lag2"
 [404] "thomebanking_lag2"
 [405] "chomebanking_transacciones_lag2"
 [406] "ccajas_transacciones_lag2"
 [407] "ccajas_consultas_lag2"
 [408] "ccajas_depositos_lag2"
 [409] "ccajas_extracciones_lag2"
 [410] "ccajas_otras_lag2"
 [411] "catm_trx_lag2"
 [412] "matm_lag2"
 [413] "catm_trx_other_lag2"
 [414] "matm_other_lag2"
 [415] "ctrx_quarter_lag2"
 [416] "tmobile_app_lag2"
 [417] "cmobile_app_trx_lag2"
 [418] "Master_delinquency_lag2"
 [419] "Master_status_lag2"
 [420] "Master_mfinanciacion_limite_lag2"
 [421] "Master_Fvencimiento_lag2"
 [422] "Master_Finiciomora_lag2"
 [423] "Master_msaldototal_lag2"
 [424] "Master_msaldopesos_lag2"
 [425] "Master_msaldodolares_lag2"
 [426] "Master_mconsumospesos_lag2"
 [427] "Master_mconsumosdolares_lag2"
 [428] "Master_mlimitecompra_lag2"
 [429] "Master_madelantopesos_lag2"
 [430] "Master_madelantodolares_lag2"
 [431] "Master_fultimo_cierre_lag2"
 [432] "Master_mpagado_lag2"
 [433] "Master_mpagospesos_lag2"
 [434] "Master_mpagosdolares_lag2"
 [435] "Master_fechaalta_lag2"
 [436] "Master_mconsumototal_lag2"
 [437] "Master_cconsumos_lag2"
 [438] "Master_cadelantosefectivo_lag2"
 [439] "Master_mpagominimo_lag2"
 [440] "Visa_delinquency_lag2"
 [441] "Visa_status_lag2"
 [442] "Visa_mfinanciacion_limite_lag2"
 [443] "Visa_Fvencimiento_lag2"
 [444] "Visa_Finiciomora_lag2"
 [445] "Visa_msaldototal_lag2"
 [446] "Visa_msaldopesos_lag2"
 [447] "Visa_msaldodolares_lag2"
 [448] "Visa_mconsumospesos_lag2"
 [449] "Visa_mconsumosdolares_lag2"
 [450] "Visa_mlimitecompra_lag2"
 [451] "Visa_madelantopesos_lag2"
 [452] "Visa_madelantodolares_lag2"
 [453] "Visa_fultimo_cierre_lag2"
 [454] "Visa_mpagado_lag2"
 [455] "Visa_mpagospesos_lag2"
 [456] "Visa_mpagosdolares_lag2"
 [457] "Visa_fechaalta_lag2"
 [458] "Visa_mconsumototal_lag2"
 [459] "Visa_cconsumos_lag2"
 [460] "Visa_cadelantosefectivo_lag2"
 [461] "Visa_mpagominimo_lag2"
 [462] "ipc_base_lag2"
 [463] "kmes_lag2"
 [464] "ctrx_quarter_normalizado_lag2"
 [465] "mpayroll_sobre_edad_lag2"
 [466] "active_quarter_delta1"
 [467] "active_quarter_delta2"
 [468] "cliente_vip_delta1"
 [469] "cliente_vip_delta2"
 [470] "internet_delta1"
 [471] "internet_delta2"
 [472] "cliente_edad_delta1"
 [473] "cliente_edad_delta2"
 [474] "cliente_antiguedad_delta1"
 [475] "cliente_antiguedad_delta2"
 [476] "mrentabilidad_delta1"
 [477] "mrentabilidad_delta2"
 [478] "mrentabilidad_annual_delta1"
 [479] "mrentabilidad_annual_delta2"
 [480] "mcomisiones_delta1"
 [481] "mcomisiones_delta2"
 [482] "mactivos_margen_delta1"
 [483] "mactivos_margen_delta2"
 [484] "mpasivos_margen_delta1"
 [485] "mpasivos_margen_delta2"
 [486] "cproductos_delta1"
 [487] "cproductos_delta2"
 [488] "tcuentas_delta1"
 [489] "tcuentas_delta2"
 [490] "ccuenta_corriente_delta1"
 [491] "ccuenta_corriente_delta2"
 [492] "mcuenta_corriente_adicional_delta1"
 [493] "mcuenta_corriente_adicional_delta2"
 [494] "mcuenta_corriente_delta1"
 [495] "mcuenta_corriente_delta2"
 [496] "ccaja_ahorro_delta1"
 [497] "ccaja_ahorro_delta2"
 [498] "mcaja_ahorro_delta1"
 [499] "mcaja_ahorro_delta2"
 [500] "mcaja_ahorro_adicional_delta1"
 [501] "mcaja_ahorro_adicional_delta2"
 [502] "mcaja_ahorro_dolares_delta1"
 [503] "mcaja_ahorro_dolares_delta2"
 [504] "cdescubierto_preacordado_delta1"
 [505] "cdescubierto_preacordado_delta2"
 [506] "mcuentas_saldo_delta1"
 [507] "mcuentas_saldo_delta2"
 [508] "ctarjeta_debito_delta1"
 [509] "ctarjeta_debito_delta2"
 [510] "ctarjeta_debito_transacciones_delta1"
 [511] "ctarjeta_debito_transacciones_delta2"
 [512] "mautoservicio_delta1"
 [513] "mautoservicio_delta2"
 [514] "ctarjeta_visa_delta1"
 [515] "ctarjeta_visa_delta2"
 [516] "ctarjeta_visa_transacciones_delta1"
 [517] "ctarjeta_visa_transacciones_delta2"
 [518] "mtarjeta_visa_consumo_delta1"
 [519] "mtarjeta_visa_consumo_delta2"
 [520] "ctarjeta_master_delta1"
 [521] "ctarjeta_master_delta2"
 [522] "ctarjeta_master_transacciones_delta1"
 [523] "ctarjeta_master_transacciones_delta2"
 [524] "mtarjeta_master_consumo_delta1"
 [525] "mtarjeta_master_consumo_delta2"
 [526] "cprestamos_prendarios_delta1"
 [527] "cprestamos_prendarios_delta2"
 [528] "mprestamos_prendarios_delta1"
 [529] "mprestamos_prendarios_delta2"
 [530] "cprestamos_hipotecarios_delta1"
 [531] "cprestamos_hipotecarios_delta2"
 [532] "mprestamos_hipotecarios_delta1"
 [533] "mprestamos_hipotecarios_delta2"
 [534] "cplazo_fijo_delta1"
 [535] "cplazo_fijo_delta2"
 [536] "mplazo_fijo_dolares_delta1"
 [537] "mplazo_fijo_dolares_delta2"
 [538] "mplazo_fijo_pesos_delta1"
 [539] "mplazo_fijo_pesos_delta2"
 [540] "cinversion1_delta1"
 [541] "cinversion1_delta2"
 [542] "minversion1_pesos_delta1"
 [543] "minversion1_pesos_delta2"
 [544] "minversion1_dolares_delta1"
 [545] "minversion1_dolares_delta2"
 [546] "cinversion2_delta1"
 [547] "cinversion2_delta2"
 [548] "minversion2_delta1"
 [549] "minversion2_delta2"
 [550] "cseguro_vida_delta1"
 [551] "cseguro_vida_delta2"
 [552] "cseguro_auto_delta1"
 [553] "cseguro_auto_delta2"
 [554] "cseguro_vivienda_delta1"
 [555] "cseguro_vivienda_delta2"
 [556] "cseguro_accidentes_personales_delta1"
 [557] "cseguro_accidentes_personales_delta2"
 [558] "ccaja_seguridad_delta1"
 [559] "ccaja_seguridad_delta2"
 [560] "cpayroll_trx_delta1"
 [561] "cpayroll_trx_delta2"
 [562] "mpayroll_delta1"
 [563] "mpayroll_delta2"
 [564] "mpayroll2_delta1"
 [565] "mpayroll2_delta2"
 [566] "cpayroll2_trx_delta1"
 [567] "cpayroll2_trx_delta2"
 [568] "ccuenta_debitos_automaticos_delta1"
 [569] "ccuenta_debitos_automaticos_delta2"
 [570] "mcuenta_debitos_automaticos_delta1"
 [571] "mcuenta_debitos_automaticos_delta2"
 [572] "ctarjeta_visa_debitos_automaticos_delta1"
 [573] "ctarjeta_visa_debitos_automaticos_delta2"
 [574] "mttarjeta_visa_debitos_automaticos_delta1"
 [575] "mttarjeta_visa_debitos_automaticos_delta2"
 [576] "ctarjeta_master_debitos_automaticos_delta1"
 [577] "ctarjeta_master_debitos_automaticos_delta2"
 [578] "mttarjeta_master_debitos_automaticos_delta1"
 [579] "mttarjeta_master_debitos_automaticos_delta2"
 [580] "cpagodeservicios_delta1"
 [581] "cpagodeservicios_delta2"
 [582] "mpagodeservicios_delta1"
 [583] "mpagodeservicios_delta2"
 [584] "cpagomiscuentas_delta1"
 [585] "cpagomiscuentas_delta2"
 [586] "mpagomiscuentas_delta1"
 [587] "mpagomiscuentas_delta2"
 [588] "ccajeros_propios_descuentos_delta1"
 [589] "ccajeros_propios_descuentos_delta2"
 [590] "mcajeros_propios_descuentos_delta1"
 [591] "mcajeros_propios_descuentos_delta2"
 [592] "ctarjeta_visa_descuentos_delta1"
 [593] "ctarjeta_visa_descuentos_delta2"
 [594] "mtarjeta_visa_descuentos_delta1"
 [595] "mtarjeta_visa_descuentos_delta2"
 [596] "ctarjeta_master_descuentos_delta1"
 [597] "ctarjeta_master_descuentos_delta2"
 [598] "mtarjeta_master_descuentos_delta1"
 [599] "mtarjeta_master_descuentos_delta2"
 [600] "ccomisiones_mantenimiento_delta1"
 [601] "ccomisiones_mantenimiento_delta2"
 [602] "mcomisiones_mantenimiento_delta1"
 [603] "mcomisiones_mantenimiento_delta2"
 [604] "ccomisiones_otras_delta1"
 [605] "ccomisiones_otras_delta2"
 [606] "mcomisiones_otras_delta1"
 [607] "mcomisiones_otras_delta2"
 [608] "cforex_delta1"
 [609] "cforex_delta2"
 [610] "cforex_buy_delta1"
 [611] "cforex_buy_delta2"
 [612] "mforex_buy_delta1"
 [613] "mforex_buy_delta2"
 [614] "cforex_sell_delta1"
 [615] "cforex_sell_delta2"
 [616] "mforex_sell_delta1"
 [617] "mforex_sell_delta2"

### Reduccion dimensionalidad con canaritos asesinos

Intencionalmente este código no se brinda
<br> El objetivo de esto es reducir la dimensionalidad del dataset unicamente para que la Bayesian Optimization corra mas rápido
<br> Tambien se puede probar con Boruta

## Modelado

### Target Engineering

In [20]:
# paso la clase a binaria que tome valores {0,1}  enteros
#  BAJA+1 y BAJA+2  son  1,   CONTINUA es 0
#  a partir de ahora ya NO puedo cortar  por prob(BAJA+2) > 1/40

dataset[, clase01 := ifelse(clase_ternaria %in% c("BAJA+2","BAJA+1"), 1L, 0L)]

### Training Strategy

Se hace una estrategia de entrenamiento muy sencilla, tomando todos los meses posibles, SIN eliminar nada x pandemia ni por ningun otro motivo

* future = 202108  obviamente completo

* final_train =  [201901, 202106] sin undersampling de los CONTINUA

* training
   * testing = 202106
   * training = [201901, 202104]  donde se consideran el 5% de los CONTINUA

In [21]:
PARAM$trainingstrategy$testing <- c(202104)

PARAM$trainingstrategy$training <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102
)

PARAM$trainingstrategy$undersampling <- 0.05


PARAM$trainingstrategy$positivos <- c( "BAJA+1", "BAJA+2")

In [22]:
# los campos en los que se entrena
campos_buenos <- copy( setdiff(
    colnames(dataset), c("clase_ternaria","clase01","azar"))
)

#### Registros  cambio las proporciones de POS/NEG

In [23]:
# Undersampling, van todos los "BAJA+1" y "BAJA+2" y solo algunos "CONTINIA"

set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset[, azar := runif(nrow(dataset))]
dataset[, training := 0L]

dataset[  foto_mes %in%  PARAM$trainingstrategy$training &
  (azar <= PARAM$trainingstrategy$undersampling | clase_ternaria %in% c("BAJA+1", "BAJA+2")),
  training := 1L
]

### Optimizacion de Hipeparámetros

Se optimizan los hiperparámetros maximizando la ganancia.

In [24]:
if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

In [25]:
dtrain <- lgb.Dataset(
  data= data.matrix(dataset[training == 1L, campos_buenos, with = FALSE]),
  label= dataset[training == 1L, clase01],
  free_raw_data= TRUE
)

cat("filas", nrow(dtrain), "columnas", ncol(dtrain), "\n")
Sys.time()

filas 215803 columnas 1247

[1] "2025-11-08 05:06:01 UTC"

In [26]:
# defino los datos de testing
dataset_test <- dataset[foto_mes %in% PARAM$trainingstrategy$testing]

# precalculo el campo de la ganancia
dataset_test[, gan := -20000.0 ]
dataset_test[ clase_ternaria=="BAJA+2", gan := 780000]

# precalculo la test_matrix
test_matrix <- data.matrix(dataset_test[, campos_buenos, with= FALSE])

cat("filas", nrow(dataset_test), "columnas", ncol(dataset_test), "\n")
Sys.time()

filas 163418 columnas 1252

[1] "2025-11-08 05:06:03 UTC"

In [27]:
# paquetes necesarios para la Bayesian Optimization
if(!require("DiceKriging")) install.packages("DiceKriging")
require("DiceKriging")

if(!require("mlrMBO")) install.packages("mlrMBO")
require("mlrMBO")

Loading required package: DiceKriging

Loading required package: mlrMBO

Loading required package: mlr

Loading required package: ParamHelpers

Loading required package: smoof

Loading required package: checkmate


Attaching package: ‘checkmate’


The following object is masked from ‘package:DiceKriging’:

    checkNames

In [28]:
# Especificacion de la cantidad de iteraciones de la Bayesian Optimization
# 50 es razonable
PARAM$hipeparametertuning$BO_iteraciones <- 30 # un 50 seria mas razonable

In [29]:
# parametros fijos del LightGBM
PARAM$lgbm$param_fijos <- list(
  objective= "binary",
  metric= "custom",
  first_metric_only= TRUE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  verbosity= -100,
  force_row_wise= TRUE, # para evitar warning
  seed= PARAM$semilla_primigenia,
  extra_trees = FALSE,

  max_depth = -1L, # -1 significa no limitar,  por ahora lo dejo fijo
  min_gain_to_split = 0.0, # min_gain_to_split >= 0.0
  min_sum_hessian_in_leaf = 0.001, #  min_sum_hessian_in_leaf >= 0.0
  lambda_l1 = 0.0, # lambda_l1 >= 0.0
  lambda_l2 = 0.0, # lambda_l2 >= 0.0

  bagging_fraction = 1.0, # 0.0 < bagging_fraction <= 1.0
  pos_bagging_fraction = 1.0, # 0.0 < pos_bagging_fraction <= 1.0
  neg_bagging_fraction = 1.0, # 0.0 < neg_bagging_fraction <= 1.0
  is_unbalance = FALSE, #
  scale_pos_weight = 1.0, # scale_pos_weight > 0.0

  drop_rate = 0.1, # 0.0 < neg_bagging_fraction <= 1.0
  max_drop = 50, # <=0 means no limit
  skip_drop = 0.5, # 0.0 <= skip_drop <= 1.0

  max_bin= 31
)

In [30]:
# Notar que se recorren algunos hiperparametros en forma logaritmica
#   y que con forbidden se tiene en cuenta el juego que hay entre min_data_in_leaf y num_leaves

PARAM$hipeparametertuning$hs <- makeParamSet(
  makeNumericParam("num_iterations", lower= 0.0, upper= 11.1, trafo= function(x) as.integer( round(2^x)) ),
  makeNumericParam("learning_rate", lower= -8.0, upper= -1.0, trafo= function(x) 2^x ),
  makeNumericParam("feature_fraction", lower= 0.05, upper= 1.0 ),
  makeNumericParam("min_data_in_leaf", lower= 0.0, upper= log2(nrow(dtrain)/2), trafo= function(x) as.integer(round(2^x)) ),
  makeNumericParam("num_leaves", lower= 1.0, upper= 10.0, trafo= function(x) as.integer(round(2^x)) ),
  forbidden= quote( (2^min_data_in_leaf)*(2^num_leaves) > nrow(dtrain) )
)

El parámetro **ksemillerio** indica se se hace semillerio DENTRO de la bayesiana
* 1 **no** se hace Ensemble Semillerio, apenas se corre un solo LightGBM
* mayor a 1, se hace un  k-Ensemble Semillerio

El parámetro  **repe** indica si dentro de la bayesiana se toman varias medidas y luego se promedian
<br> Esto se hace ya sea que se llama a un solo LightGBM o se haceun Ensemble Semillerio de LightGBMs
<br> Tener en cuenta que repe multiplica linealmente el tiempo de corrida de la Bayesian Optimization

In [31]:
PARAM$hipeparametertuning$ksemillerio <- 1L
PARAM$hipeparametertuning$repe <- 1L

In [32]:
if(!require("primes")) install.packages("primes")
require("primes")

Loading required package: primes

In [33]:
primos <- generate_primes(min = 100000, max = 1000000)
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
# me quedo con PARAM$semillerio  primos al azar
PARAM$BO$semillas <- sample(primos)[seq( PARAM$hipeparametertuning$ksemillerio * PARAM$hipeparametertuning$repe )]

cat( PARAM$BO$semillas)

974411

In [34]:
if(!require("rlist")) install.packages("rlist")
require("rlist")

Loading required package: rlist

In [35]:
# logueo al archivo BO_log.txt
loguear  <- function( reg, arch=NA, verbose=TRUE )
{
  t0 <- Sys.time()
  archivo <- arch
  if( is.na(arch) ) archivo <- paste0( folder, substitute( reg), ext )


  if( !file.exists( archivo ) )
  {
    # Escribo los titulos
    linea  <- paste0( "fecha\t", 
                      paste( list.names(reg), collapse="\t" ), "\n" )

    cat( linea, file=archivo )
  }

  # escribo el registro
  linea  <- paste0( format(t0, "%Y%m%d.%H%M%S"),  "\t",     # la fecha y hora
                    gsub( ", ", "\t", toString( reg ) ),  "\n" )

  cat( linea, file=archivo, append=TRUE )  # grabo al archivo

  if( verbose )  cat( linea )   # imprimo por pantalla
}

In [36]:
# esto esta en una funcion para que el garbage collector lo libere
# entrena, aplica el modelo a testing, y devuelve el vector de probabilidades

OneTrainPredict <- function(param_completo) {
    
  modelo <- lgb.train(
    data= dtrain,
    param= param_completo
  )
  gmodelo <<- modelo

  # aplico el modelo a los datos nuevos
  pred <- predict(
    modelo,
    test_matrix
  )

  return( pred )
}

In [37]:
# En el argumento x llegan los parametros de la bayesiana
#  devuelve la ganancia en datos de testing

# aqui se ira guardando la mejor iteracion de la bayesiana
gmejor <- list()
gmejor$iter <- 0
gmejor$gan <- -Inf

giter <- 0
if( file.exists("BO_log.txt") ){
  tb_BO <- fread("BO_log.txt")
  giter <- nrow(tb_BO) -1 
}

EstimarGanancia_lightgbm <- function(x) {

  giter <<- giter + 1
  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)

  vgan_mesetas <- c()  # las ganancias, tengo repe de ellas

  # loop de las repeticionies
  for( repe in seq( PARAM$hipeparametertuning$repe ) )
  {
     desde <- (PARAM$hipeparametertuning$repe-1)*PARAM$hipeparametertuning$ksemillerio + 1
     hasta <- desde + PARAM$hipeparametertuning$ksemillerio -1
     rsemillas <- PARAM$BO$semillas[ desde:hasta ]

     # vector inicial de probabilidades
     vpred_acum <- rep( 0.0, nrow(dataset_test) )

     # loop del semillerio
     for( sem in rsemillas ) # itero semillerio
     {
        param_completo$seed <- sem  # asigno se semilla
        vpred_acum <- vpred_acum + OneTrainPredict( param_completo )
        
        gc(full= TRUE, verbose= FALSE)
     }

     # Calculo de ganancia suavizada de la meseta
     tb_prediccion <- dataset_test[, list(gan)]
     tb_prediccion[, prob := vpred_acum ]

     setorder(tb_prediccion, -prob)
     tb_prediccion[, gan_acum := cumsum(gan)]

     # la meseta es un punto, mil para la izquierda, otros mil para la derecha
     tb_prediccion[, gan_meseta :=
       frollmean(
         x= gan_acum, n= 2001, align= "center",
         na.rm= TRUE, hasNA= TRUE
      )
     ]

     vgan_mesetas <- c(vgan_mesetas, tb_prediccion[, max(gan_meseta, na.rm = TRUE)] )
  }

  gan_mesetas_prom <- mean( vgan_mesetas ) 

  if( gan_mesetas_prom > gmejor$gan ){
    gmejor$gan <<- gan_mesetas_prom
    gmejor$iter <<- giter

    # hrabo importancia de variables
    fwrite( lgb.importance(gmodelo),
      file= paste0("impo_", giter, ".txt"),
      sep= "\t"
    )
  }

  # datos qeu voy a loguear
  xx <- copy(param_completo)
  xx$iter <- giter
  xx$metrica_mejor <- gmejor$gan
  xx$metrica_sd <- sd(vgan_mesetas)
  xx$metrica <- gan_mesetas_prom

  loguear( xx, "BO_log.txt")
  set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")  # le reordeno a mlrMBO

  return( gan_mesetas_prom ) #tiempo_corrida) )
}

In [38]:
# Aqui comienza la configuracion de la Bayesian Optimization
#  es compleja la configuracion de una Bayesian Optimization

# en este archivo quedan la evolucion binaria de la BO
kbayesiana <- "bayesiana.RDATA"

funcion_optimizar <- EstimarGanancia_lightgbm # la funcion que voy a maximizar

configureMlr(show.learner.output= FALSE)

# configuro la busqueda bayesiana,  los hiperparametros que se van a optimizar
# por favor, no desesperarse por lo complejo

obj.fun <- makeSingleObjectiveFunction(
  fn= funcion_optimizar, # la funcion que voy a maximizar
  minimize= FALSE, # estoy Maximizando la ganancia
  noisy= TRUE,
  par.set= PARAM$hipeparametertuning$hs, # definido al comienzo del programa
  has.simple.signature= FALSE # paso los parametros en una lista
)

# cada 600 segundos guardo el resultado intermedio
ctrl <- makeMBOControl(
  save.on.disk.at.time= 600, # se graba cada 600 segundos
  save.file.path= kbayesiana
) # se graba cada 600 segundos

# indico la cantidad de iteraciones que va a tener la Bayesian Optimization
ctrl <- setMBOControlTermination(
  ctrl,
  iters= PARAM$hipeparametertuning$BO_iteraciones
) # cantidad de iteraciones

# defino el método estandar para la creacion de los puntos iniciales,
# los "No Inteligentes"
ctrl <- setMBOControlInfill(ctrl, crit= makeMBOInfillCritEI())

# establezco la funcion que busca el maximo
surr.km <- makeLearner(
  "regr.km",
  predict.type= "se",
  covtype= "matern3_2",
  control= list(trace= TRUE)
)

Sys.time()

[1] "2025-11-08 05:06:04 UTC"

#### Corrida de la Bayesian Optimization

In [ ]:
# inicio la optimizacion bayesiana, retomando si ya existe
# es la celda mas lenta de todo el notebook

if (!file.exists(kbayesiana)) {
  bayesiana_salida <- mbo(obj.fun, learner= surr.km, control= ctrl)
} else {
  bayesiana_salida <- mboContinue(kbayesiana) # retomo en caso que ya exista
}

Sys.time()

Computing y column(s) for design. Not provided.

20251108.050616	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	9	0.00751513077819927	0.284858822397221	89	33	1	304424847.576212	NA	304424847.576212
20251108.050619	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	2	0.0325416602472422	0.293619126074546	12	173	2	304475202.398801	NA	304475202.398801
20251108.050644	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	452	0.177703738626204	0.67202623474562	1004	53	3	341824317.841079	NA	341824317.841079
20251108.050733	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	542	0.0122104653103434	0.461279257690437	235	39	4	341824317.841079	NA	338979930.034983
20251108.050735	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	11	0.0189202342506775	0.662187630768755	2	21	5	341824317.841079	NA	301394002.998501
20251108.050800	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	783	0.0497879637924253	0.61362855432549	42	7	6	342000189.905047	NA	342000189.905047
20251108.050802	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	1	0.0628664083959553	0.949055811878319	448	9	7	342000189.905047	NA	249083368.315842
20251108.050815	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	295	0.076126116616571	0.0972573854487939	5	14	8	342000189.905047	NA	341731014.492754
20251108.050828	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	46	0.276768623972521	0.779812755571574	23	778	9	342000189.905047	NA	338474642.678661
20251108.050830	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	3	0.472690146586708	0.212735701871926	9	3	10	342000189.905047	NA	289757471.264368
20251108.050943	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	1053	0.00515652594403099	0.572302655772993	17680	3	11	342000189.905047	NA	301512183.908046
20251108.051016	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	101	0.0098157235610199	0.997763551543425	1	673	12	342000189.905047	NA	332354222.888556
20251108.051022	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	170	0.330885419381382	0.876176979473632	1092	5	13	343698390.804598	NA	343698390.804598
20251108.051027	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	30	0.0219815569360442	0.395044265684953	148	137	14	343698390.804598	NA	328365937.031484
20251108.051133	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	780	0.0117747013133379	0.537171106003207	2461	25	15	343698390.804598	NA	341242208.895552
20251108.051136	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	16	0.158723595888739	0.179255788954178	2223	76	16	343698390.804598	NA	317296001.999
20251108.051149	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	181	0.00798936088941173	0.332694307802109	4	5	17	343698390.804598	NA	287335622.188906
20251108.051221	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	103	0.301056931212913	0.927463870434436	80	944	18	343698390.804598	NA	340598170.914543
20251108.051223	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	5	0.0920895334200053	0.368968552774857	10	244	19	343698390.804598	NA	319762838.58071
20251108.051225	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	3	0.00485006342052652	0.446952230673298	13	155	20	343698390.804598	NA	310115362.318841

[mbo] 0: num_iterations=9; learning_rate=0.00752; feature_fraction=0.285; min_data_in_leaf=89; num_leaves=33 : y = 3.04e+08 : 11.6 secs : initdesign

[mbo] 0: num_iterations=2; learning_rate=0.0325; feature_fraction=0.294; min_data_in_leaf=12; num_leaves=173 : y = 3.04e+08 : 2.6 secs : initdesign

[mbo] 0: num_iterations=452; learning_rate=0.178; feature_fraction=0.672; min_data_in_leaf=1004; num_leaves=53 : y = 3.42e+08 : 25.4 secs : initdesign

[mbo] 0: num_iterations=542; learning_rate=0.0122; feature_fraction=0.461; min_data_in_leaf=235; num_leaves=39 : y = 3.39e+08 : 49.1 secs : initdesign

[mbo] 0: num_iterations=11; learning_rate=0.0189; feature_fraction=0.662; min_data_in_leaf=2; num_leaves=21 : y = 3.01e+08 : 2.3 secs : initdesign

[mbo] 0: num_iterations=783; learning_rate=0.0498; feature_fraction=0.614; min_data_in_leaf=42; num_leaves=7 : y = 3.42e+08 : 24.4 secs : initdesign

[mbo] 0: num_iterations=1; learning_rate=0.0629; feature_fraction=0.949; min_data_in_leaf=448; num_leaves=9 : y = 2.49e+08 : 1.9 secs : initdesign

[mbo] 0: num_iterations=295; learning_rate=0.0761; feature_fraction=0.0973; min_data_in_leaf=5; num_leaves=14 : y = 3.42e+08 : 13.9 secs : initdesign

[mbo] 0: num_iterations=46; learning_rate=0.277; feature_fraction=0.78; min_data_in_leaf=23; num_leaves=778 : y = 3.38e+08 : 13.1 secs : initdesign

[mbo] 0: num_iterations=3; learning_rate=0.473; feature_fraction=0.213; min_data_in_leaf=9; num_leaves=3 : y = 2.9e+08 : 2.0 secs : initdesign

[mbo] 0: num_iterations=1053; learning_rate=0.00516; feature_fraction=0.572; min_data_in_leaf=17680; num_leaves=3 : y = 3.02e+08 : 72.9 secs : initdesign

[mbo] 0: num_iterations=101; learning_rate=0.00982; feature_fraction=0.998; min_data_in_leaf=1; num_leaves=673 : y = 3.32e+08 : 32.5 secs : initdesign

[mbo] 0: num_iterations=170; learning_rate=0.331; feature_fraction=0.876; min_data_in_leaf=1092; num_leaves=5 : y = 3.44e+08 : 6.0 secs : initdesign

[mbo] 0: num_iterations=30; learning_rate=0.022; feature_fraction=0.395; min_data_in_leaf=148; num_leaves=137 : y = 3.28e+08 : 4.7 secs : initdesign

[mbo] 0: num_iterations=780; learning_rate=0.0118; feature_fraction=0.537; min_data_in_leaf=2461; num_leaves=25 : y = 3.41e+08 : 66.7 secs : initdesign

[mbo] 0: num_iterations=16; learning_rate=0.159; feature_fraction=0.179; min_data_in_leaf=2223; num_leaves=76 : y = 3.17e+08 : 3.2 secs : initdesign

[mbo] 0: num_iterations=181; learning_rate=0.00799; feature_fraction=0.333; min_data_in_leaf=4; num_leaves=5 : y = 2.87e+08 : 12.4 secs : initdesign

[mbo] 0: num_iterations=103; learning_rate=0.301; feature_fraction=0.927; min_data_in_leaf=80; num_leaves=944 : y = 3.41e+08 : 32.1 secs : initdesign

[mbo] 0: num_iterations=5; learning_rate=0.0921; feature_fraction=0.369; min_data_in_leaf=10; num_leaves=244 : y = 3.2e+08 : 2.4 secs : initdesign

[mbo] 0: num_iterations=3; learning_rate=0.00485; feature_fraction=0.447; min_data_in_leaf=13; num_leaves=155 : y = 3.1e+08 : 2.1 secs : initdesign

20251108.051251	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	965	0.340585507029719	0.640568928245589	111	11	21	343698390.804598	NA	328616301.849075

[mbo] 1: num_iterations=965; learning_rate=0.341; feature_fraction=0.641; min_data_in_leaf=111; num_leaves=11 : y = 3.29e+08 : 23.7 secs : infill_ei

20251108.051332	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	663	0.0413858799714475	0.730550550860854	3471	35	22	352130954.522739	NA	352130954.522739

[mbo] 2: num_iterations=663; learning_rate=0.0414; feature_fraction=0.731; min_data_in_leaf=3471; num_leaves=35 : y = 3.52e+08 : 38.6 secs : infill_ei

20251108.051547	binary	custom	TRUE	TRUE	FALSE	-100	TRUE	974411	FALSE	-1	0	0.001	0	0	1	1	1	FALSE	1	0.1	50	0.5	31	806	0.0333814340306104	0.552495533375657	684	315	23	357809405.297351	NA	357809405.297351

[mbo] 3: num_iterations=806; learning_rate=0.0334; feature_fraction=0.552; min_data_in_leaf=684; num_leaves=315 : y = 3.58e+08 : 132.8 secs : infill_ei

## Produccion

Las decisiones que se toman para la construccion del modelo final son:
* Obviamente los datos donde se aplica el modelo es el mes  {202108} , que no tiene clase
* Los positvos son  POS={"BAJA+1", "BAJA+2"}, esta es una meticulosa decisión.
* Se entrena en los treinta meses del intervalo [201901, 202106]
* Se realiza undersampling al 10%
* Se utilizan los hiperparámetros optimos encontrados en la Bayesian Optimization
   * Se escala min_data_in_leaf

* Por experimentos en meses anteriores, se decide cortar en los 11000 registros con mayor probabildiad de POS={"BAJA+1", "BAJA+2"}, , esta es una *enorme* decisión.

### Final Training Strategy

In [ ]:
PARAM$train_final$future <- c(202106)

PARAM$train_final$training <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104
)

PARAM$train_final$undersampling <- 0.10

In [ ]:
# se filtran los meses donde se entrena el modelo final
dataset_train_final <- dataset[foto_mes %in% PARAM$train_final$training]

#### Registros cambio las proporciones de POS/NEG

In [ ]:
# Undersampling, van todos los "BAJA+1" y "BAJA+2" y solo algunos "CONTINIA"

set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset_train_final[, azar := runif(nrow(dataset_train_final))]
dataset_train_final[, training := 0L]

dataset_train_final[
  (azar <= PARAM$train_final$undersampling | clase_ternaria %in% c("BAJA+1", "BAJA+2")),
  training := 1L
]

dataset_train_final[, azar:= NULL] # elimino la columna azar

### Target Engineering

In [ ]:
# paso la clase a binaria que tome valores {0,1}  enteros
#  BAJA+1 y BAJA+2  son  1,   CONTINUA es 0
#  a partir de ahora ya NO puedo cortar  por prob(BAJA+2) > 1/40

dataset_train_final[,
  clase01 := ifelse(clase_ternaria %in% c("BAJA+2","BAJA+1"), 1L, 0L)
]

### Adaptacion Hiperparametros Optimos

Solamente escalo min_data_in_leaf  por  nrow(dataset_train_final) / nrow(dtrain)

In [ ]:
# leo el archivo donde quedaron los hiperparametros optimos
tb_BO <-  fread("BO_log.txt")
setorder( tb_BO, -metrica)  # ordeno por metrica descendente
tb_BO[1]

In [ ]:
# en la tabla ademas de los parametros del LightGBM, hay campos de salida
param_lgbm <- union( names(PARAM$lgbm$param_fijos),  names(PARAM$hipeparametertuning$hs$pars) )

PARAM$train_final$param_mejores <- as.list( tb_BO[1, param_lgbm, with=FALSE])

PARAM$train_final$param_mejores$min_data_in_leaf <- as.integer( round(PARAM$train_final$param_mejores$min_data_in_leaf * nrow(dataset_train_final[training == 1L]) / nrow(dtrain)))

cat( tb_BO[1, min_data_in_leaf] , PARAM$train_final$param_mejores$min_data_in_leaf, "\n")
PARAM$train_final$param_mejores

### Final Models

Aqui SIEMPRE voy a hacer un semillerio, independientemente de si en la Bayesian Optimization calculé un semillerio en cada iteración.
<br> Entreno un LightGBM para cada semilla,  y guardo el modelo dentro de la carpeta  **modelitos**
<br> Intencionalmente en una primera etapá se generan los modelos y graban, y en una segunda etapa se leen eso modelos y se aplican a los datos del futuro

APO controla cuantas veces se repite el modelo, que se usa para promediar ganancias y reportar en la Pseudo Competencia algo razonable
<br> El modelo puede ser un LightGBM simple (ksemillerio==1)  o un Ensemble Semillerio( ksemillerio > 1 )
<br> Lamentablmente APO necesita utilizar muchas semillas, y eso demanda TIEMPO de corrida

In [ ]:
# Semillerio Final
PARAM$train_final$APO <- 10
PARAM$train_final$ksemillerio  <- 10

PARAM$train_final$cortes <- c(10500, 11000, 11500, 12000)

In [ ]:
# valvula de seguridad anti atajos
if( PARAM$train_final$APO * PARAM$train_final$ksemillerio  < 100
  | PARAM$train_final$APO < 5
)  {
  # stop("No quiera overfitear")
  cat("No quiera overfitear")
}

In [ ]:
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
PARAM$train_final$semillas <- sample(primos)[seq( PARAM$train_final$ksemillerio*PARAM$train_final$APO )]
PARAM$train_final$semillas

In [ ]:
# dejo los datos en formato LightGBM
dtrain_final <- lgb.Dataset(
  data= data.matrix(dataset_train_final[training == 1L, campos_buenos, with= FALSE]),
  label= dataset_train_final[training == 1L, clase01],
  free_raw_data= FALSE
)

cat("filas", nrow(dtrain_final), "columnas", ncol(dtrain_final), "\n")
Sys.time()

In [ ]:
# genero los modelitos
dir.create( "modelitos", showWarnings= FALSE)

param_completo <- copy( PARAM$train_final$param_mejores)

for( sem in PARAM$train_final$semillas ) {

  arch_modelo <- paste0("./modelitos/mod_", sem, ".txt")
  if( !file.exists( arch_modelo ) )
  {
    param_completo$seed <- sem

    modelito <- lgb.train(
      data= dtrain_final,
      param= param_completo
    )

    lgb.save( modelito, filename= arch_modelo)
    rm(modelito)
    gc()
  }
}

Sys.time()

### Scoring

Se hace el predict() del modelo en los datos del futuro

In [ ]:
# dataset de future, donde en este caso estoy haciendo testing
dfuture <- dataset[foto_mes %in% PARAM$train_final$future ]
mfuture <- data.matrix(dfuture[, campos_buenos, with= FALSE])

dfuture[, ganancia := ifelse(clase_ternaria=="BAJA+2", 780000, -20000)]

In [ ]:
mganancias <- matrix( nrow=PARAM$train_final$APO, ncol= length(PARAM$train_final$cortes) )

if( file.exists("prediccion.txt") )
  file.remove("prediccion.txt")

In [ ]:
# aplico el modelo a los datos del future

for( vapo in seq(PARAM$train_final$APO) ) {
  # inicializacion en CERO
  vpred_acum <- rep(0.0, nrow(dfuture))
  qacumulados <- 0

  desde <- 1 + (vapo-1)*PARAM$train_final$ksemillerio
  hasta <- desde + PARAM$train_final$ksemillerio - 1
  semillas <- PARAM$train_final$semillas[desde:hasta]

  for( sem in semillas ) {

    arch_modelo <- paste0("./modelitos/mod_", sem, ".txt")
    if( file.exists( arch_modelo ) )
    {
      modelo_final <- lgb.load(arch_modelo) # leo del disco
      # hago el predict() y acumulo
      vpred_acum <- vpred_acum + predict(modelo_final, mfuture)
      qacumulados <- qacumulados + 1
      rm(modelo_final)
      gc()
    }
  }

  if( qacumulados > 0 ) {
    vpred_acum <- vpred_acum / qacumulados  # paso a probabildiad
    # tabla de prediccion, puede ser util para futuros ensembles
    #  ya que le modelo ganador va a ser un ensemble de LightGBMs

    tb_prediccion <- dfuture[, list(numero_de_cliente, foto_mes, ganancia)]
    tb_prediccion[, meta_modelo := vapo]
    tb_prediccion[, prob := vpred_acum ]
    setorder( tb_prediccion, -prob )
    tb_prediccion[, gan_acum := cumsum(ganancia)]
    tb_prediccion[, ganancia := NULL ]

    # acumulo las ganancias
    for( icor in seq(length(PARAM$train_final$cortes)) ){
      mganancias[ vapo, icor ] <- tb_prediccion[ PARAM$train_final$cortes[icor], gan_acum ]
    }

    # grabo las probabilidades del modelo
    fwrite(tb_prediccion,
      file= "prediccion.txt",
      sep= "\t",
      append= TRUE
    )

    rm(tb_prediccion)
    gc()
  }
}

Sys.time()

In [ ]:
mganancias

### Clasificacion

Se tomó la decisión de enviar a los 11000 registros con mayor probabilidad de POS={"BAJA+1","BAJA+"}
<br> esto se determinó en forma artesanal analizando meses anterior
<br> esta es una muy importante decisión

In [ ]:
# genero archivos con los  "envios" mejores
dir.create("kaggle", showWarnings=FALSE)

tb_prediccion <- fread("prediccion.txt")

In [ ]:
# genero archivos de fantasia, que NO son el que voy a subir a la Pseudo Competencia Kaggle
envios <- 11000

for( vapo in seq(PARAM$train_final$APO) ) {
  if( tb_prediccion[meta_modelo==vapo, .N] > 0 ) {
    tb_pred <- tb_prediccion[meta_modelo==vapo]
    setorder( tb_pred, -prob )
    tb_pred[, Predicted := 0L] # seteo inicial a 0
    tb_pred[1:envios, Predicted := 1L] # marco los primeros

    archivo_kaggle <- paste0("./kaggle/KA", PARAM$experimento, "_", vapo, "_", envios, ".csv")

    # grabo el archivo
    fwrite(tb_pred[, list(numero_de_cliente, Predicted)],
      file= archivo_kaggle,
      sep= ","
    )

    rm( tb_pred )
    gc()
  }
}

Sys.time()

### Subida a Pseudo Kaggle

Aqui viene la verdadera magia de  APO = A Prueba Overfiteres
<br>Se sube un submit a la Pseudo Competencia Kaggle cuya ganancia coincide casi exactamente con la ganancia MEDIA , promediada  APO veces

In [ ]:
colmedias <- colMeans( mganancias, na.rm=TRUE )
mcorte_mejor <- max(colmedias, na.rm=TRUE)
icorte_mejor <- which.max( colmedias )
corte_mejor <- PARAM$train_final$cortes[icorte_mejor]

In [ ]:
tbl <- as.data.table( as.list( colmedias ) )
colnames(tbl) <- paste0( "e", PARAM$train_final$cortes )
tbl[, experimento := PARAM$experimento ]

exp_gral <- "/content/buckets/b1/exp/apo-gral"
dir.create(exp_gral, showWarnings=FALSE)
fwrite( tbl,
  file= paste0( exp_gral, "/tb_experimentos.txt"),
  sep= "\t",
  append= TRUE
)

In [ ]:
colnames( mganancias ) <- paste0( "e", PARAM$train_final$cortes )
tbl_local <- as.data.table( mganancias )

fwrite( tbl_local,
  file= "tb_apo.txt",
  sep= "\t"
)

In [ ]:
icerca <- which.min(  abs( tb_prediccion$gan_acum - mcorte_mejor ) )
vmodelo <- tb_prediccion[ icerca, meta_modelo ]
tb_pred <- tb_prediccion[meta_modelo==vmodelo]

mcorte_mejor
icerca
tb_prediccion[ icerca]

In [ ]:
icerca <- which.min(  abs( tb_pred$gan_acum - mcorte_mejor ) )
icerca

In [ ]:
icerca <- which.min(  abs( tb_prediccion$gan_acum - mcorte_mejor ) )
vmodelo <- tb_prediccion[ icerca, meta_modelo ]
tb_pred <- tb_prediccion[meta_modelo==vmodelo]

icerca <- which.min(  abs( tb_pred$gan_acum - mcorte_mejor ) )
tb_pred[, Predicted := 0L] # seteo inicial a 0
tb_pred[1:icerca, Predicted := 1L] # marco los primeros

archivo_pseudo_kaggle <- paste0("./kaggle/KA", PARAM$experimento, "_",  icerca, ".csv")

# grabo el archivo
fwrite(tb_pred[, list(numero_de_cliente, Predicted)],
  file= archivo_pseudo_kaggle,
  sep= ","
)

In [ ]:
# la subida a Kaggle
comando <- "kaggle competitions submit"
competencia <- "-c  test-202106"
arch <- paste( "-f", archivo_pseudo_kaggle)
mensaje <-  paste0( "-m 'exp=", PARAM$experimento,
  " envios=", icorte_mejor,"'")

                    
linea <- paste( comando, competencia, arch, mensaje)
salida <- system(linea, intern=TRUE)
cat(salida)

In [ ]:
Sys.time()